### DISCUSSION TITLE
Changer la description / le titre d'une règle en fonction de l'évaluation

### DISCUSSION THREAD

**Discussion by mquandalle** [publicodes/publicodes#121] [Ideas]
Sur mon-entreprise, la description des champs comme "Salaire brut de base / Inscrit dans le contrat de travail" est spécifiée dans la base de règles, et automatiquement utilisée dans l'UI. Il me semble qu'il faudrait trouver un moyen, le plus élégant possible, de modifier ces descriptions en fonction du contexte — type de simulateur, réponses aux questions.

Mon cas d'usage est sur les stages (#582) : si le type de contrat est définie comme étant un « stage », il faudrait modifier l'UI pour remplacer le terme « salaire » par celui de « gratification de stage ». De même, comme discuté avec @johangirod, on peut avoir envie de modifier la description du champ « chiffre d'affaire » en fonction du contexte (« chiffre d'affaire minimum » dans le simulateur de rémunération, et simplement « chiffre d'affaire » dans un simulateur au niveau de la société).

**Comment by mquandalle** [comment]
De même il faudrait pouvoir modifier les questions ; par exemple si on a sélectionné "Apprentissage" :
> ~Le salarié~ L'apprenti profite-t-il de l'indemnité kilométrique vélo ?

**Comment by johangirod** [comment]
Je pense qu'il faut envisager les champs description comme une expression de type texte, qui pourrait être évalué tout au même titre que la formule. 
```yaml
frais . IKV:
   question: 
     variations:
       - si: contrat = apprentissage:
         alors: "L'apprenti profite-t-il de l'indemnité kilométrique vélo ?"
       - sinon: "Le salarié profite-t-il de l'indemnité kilométrique vélo?"
```

On pourrait imaginer avoir un mécanisme de templating : 
```yaml
désignation:
  formule:
    variations: 
      - si: contrat = apprentissage
        alors: "l'apprenti"
      - si: contrat = stage
        alors: "le stagiaire"
      - sinon: "le salarié

frais . IKV:
   question: |
     {{désignation}} profite-t-il de l'indemnité kilométrique vélo ?
```

Je n'ose imaginer les implications au niveau de la traduction. Mais sur le principe du moteur, ça serait plutôt facile et logique.
