### DISCUSSION TITLE
Pouvoir définir des variables locales à une règle sans passer par `nom`

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#163] [Ideas]
Update : cette fonctionnalité existe maintenant grâce au mécanisme `avec`

## Limites de l'existant
Il est possible aujourd'hui de définir des variables à l'intérieur d'une formule de calcul publicodes grâce au mot clé `nom`. C'est une fonctionnalité très utilisée, pratique pour ne pas avoir à redéfinir des règles constamment.

Ceci dit, cette fonctionnalité souffre de plusieurs limites : 

### 1. Il est impossible de l'utiliser à l'intérieur d'expression publicodes (sous forme infixe)
 
```yaml
prix final: 
   valeur: 157 € * (100% - 20%)
```
Dans cet exemple, si l'on veut extraire le prix et la réduction dans des variables intermédiaires, on est obligé de les définir séparément, ce qui est lourd.

```yaml
prix final: 
   valeur: prix de base * (100% - réduction)
prix final . prix de base: 157€
prix final . réduction: 20%
```

### 2. La réutilisation des variables locales, bien que possible, n'est pas intuitive
Exemple tiré de la base de règle mon-entreprise
```yaml
CSG non déductible: 
  produit:
    assiette: assiette 
    composantes:
      - taux:
          nom: taux
          valeur: 2.9%
      - attributs:
          nom: revenus de remplacement
        assiette: dirigeant . indépendant . IJSS . total
        taux: taux
  ```
La variable "taux" est définie dans la première partie de la "composante", et réutilisée dans la deuxième partie. C'est assez difficile à lire si l'on commence par la deuxième partie : le premier réflexe est de chercher la définition de `taux` dans une règle séparée.

### 3. Il est impossible de définir plusieurs variables d'un coup dans une règle

Lors de l'écriture de formulaire en publicodes, il est souvent plus lisible de définir plusieurs règles enfant directement dans la règle parente plutôt que de réécrire l'ensemble de l'espace de nom à chaque fois. Le fait que la création de nouvelle variable ne peut avoir lieu que dans le contexte de l'évaluation de la valeur de la règle m'oblige à utiliser une somme par exemple : 

```yaml
données assuré:
  non applicable si: situation . notification
  type: groupe
  titre: ''
  somme:
    - nom: nom
      type: texte
    - nom: prénoms
      type: texte
    - nom: numéro de sécurité sociale
      description: Saisissez les 15 chiffres de votre numéro tel qu'il apparaît sur la carte vitale par exemple.
      type: texte
    - nom: nationalité
      type: texte
    - nom: date de naissance
      type: date
```

## Solution envisagée 

On propose un nouveau mécanisme `avec` pour ajouter la possibilité de définir des variables en dehors de la formule de calcul.

Dans les exemples ci-dessus, cela donnerait : 

```yaml
prix final: 
   valeur: prix de base * (100% - réduction)
   avec: 
     prix de base: 137 €
     réduction: 20%
```

```yaml 
CSG non déductible: 
  produit:
    assiette: assiette 
    composantes:
      - taux: taux
      - attributs:
          nom: revenus de remplacement
        assiette: dirigeant . indépendant . IJSS . total
        taux: taux
  avec: 
    taux: 2.9%
```

```yaml
données assuré:
  non applicable si: situation . notification
  avec:
    nom:
      type: texte
    prénoms:
      type: texte
    numéro de sécurité sociale:
      description: Saisissez les 15 chiffres de votre numéro tel qu'il apparaît sur la carte vitale par exemple.
      type: texte
    nationalité:
      type: texte
    date de naissance:
      type: date
```

Un des avantages indéniable de cette proposition est la simplicité de son implémentation. Il s'agit d'une simple transformation statique.

#### `avec` est-il le bon mot-clé ? 
J'hésite notamment avec celui de `définition` qui est plus adapté pour l'usage 3 (et 2 ?). En plus, `définition` est sémantiquement plus clair : on définit des nouvelles règles enfants. 

#### Quel lien avec la définition de fonction ?
Dans le premier exemple, la règle 'prix final' est la définition de comment calculer une réduction sur un prix. Dans `avec` se trouvent des paramètres. Si l'on modifie un peu la règle, on peut avoir quelque chose comme : 
```yaml
prix final: 
   valeur: prix de base * (100% - réduction)
   avec: 
     prix de base: 
       unité: €
     réduction: 
       par défaut: 20%
```
Et là, on est très clairement sur une fonction avec des paramètres d'entrée typés et des valeurs par défaut.

#### Quel lien avec le mécanisme `recalcul` ?
Le mécanisme `recalcul ` utilise également le mot clé `avec` pour redéfinir des variables... Pourrait-on faire des liens, utiliser le même mécanisme derrière tout ça ?

#### Besoin de type objet dans publicodes ?
Y a-t-il vraiment besoin d'un type objet dans publicodes ? Est-ce qu'une syntaxe utilisant uniquement la définition de règle enfants et des listes ne suffirait pas ? C'est à creuser.

**Comment by johangirod** [comment]
Autre cas d'usage actuel : le mécanisme `une possibilité` demande de définir des sous variable, ce qui est très lourd via la déclaration de règles. Avec ce nouveau mécanisme, on transforme : 

```yaml
début d'activité:
  titre: Période de début d’activité
  question: À quelle période avez-vous débuté votre activité ?
  formulaire:
    type: select
  une possibilité:
    choix obligatoire: oui
    possibilités:
      - avant 2021
      - janvier 2021
      - février 2021
      - mars 2021
      - avril 2021
      - mai 2021
      - juin 2021
      - juillet 2021
...

début d'activité . avant 2021:
début d'activité . janvier 2021:
début d'activité . février 2021:
début d'activité . mars 2021:
début d'activité . avril 2021:
début d'activité . mai 2021:
début d'activité . juin 2021:
début d'activité . juillet 2021:
...
```

```
début d'activité:
  titre: Période de début d’activité
  question: À quelle période avez-vous débuté votre activité ?
  formulaire:
    type: select
  une possibilité:
    choix obligatoire: oui
    possibilités:
      - avant 2021
      - janvier 2021
      - février 2021
      - mars 2021
      - avril 2021
      - mai 2021
      - juin 2021
      - juillet 2021
      ...
  avec: 
    avant 2021:
    janvier 2021:
    février 2021:
    mars 2021:
    avril 2021:
    mai 2021:
    juin 2021:
    juillet 2021:
...
```
 > *NB* le mécanisme une possibilité dans l'état actuel est très lourd et peu intuitif à utiliser, mais c'est l'objet d'une autre discussion #10

**Comment by laem** [comment]
J'aime beaucoup ta proposition `avec`. 

Ça rappelle la construction `let` de clojure https://clojuredocs.org/clojure.core/let. 

Tu définis des variables locales à un calcul qui renvoie une valeur unique. 

Par contre, là où je vois un problème, c'est sur la génération de la doc. 

Dans cet exemple, clairement ta proposition `avec` est plus claire, car les variables sont définies localement pour une usage local. 

Mais du coup on ne génère pas de page pour ces variables. Dans cet exemple basique, tant mieux, c'est un avantage. Peut-être qu'il faudrait être explicite dans la documentation publicodes en disant : "attention, en définissant des variables locales, elles ne seront pas indexées par les moteurs de recherche. Si vous leur donnez du contenu intéressant, faites-en des variables". 

```yaml
prix final: 
   valeur: prix de base * (100% - réduction)
prix final . prix de base: 157€
prix final . réduction: 20%
```

**Reply by johangirod** [reply]
Dans l'état actuel des choses, les règles imbriquées (définies avec `nom`) ont bien une page dans la documentation. En revanche, elles apparaissent sans indirection dans la partie "Comment cette donnée est-elle calculée". Elles peuvent donc être indexées séparément, et la description apparaîtra dans leur page dédiée.

Exemple sur mon-entreprise : 
- https://mon-entreprise.urssaf.fr/documentation/contrat-salari%C3%A9/vieillesse
- https://mon-entreprise.urssaf.fr/documentation/contrat-salari%C3%A9/vieillesse/salari%C3%A9/d%C3%A9plafonn%C3%A9e

**Comment by Clemog** [comment]
Hello ! La solution semble géniale, notamment quand on voit le cas d'usage avec le mécanisme `une possibilité` !
(Un aparté sur recalcul, vraiment puissant pour les actions de NGC par exemple, avec un `avec` très intuitif)

Je veux bien une précision sur le cas d'usage n°3, je n'ai pas trop compris ?

A bientôt ! :)

**Reply by johangirod** [reply]
Nous utilisons publicodes sur mon-entreprise pour gérer des formulaires. Chaque règle correspond à un champ, un espace de nom correspond à un groupe et publicodes nous permet de gérer l'affichage de section/question en fonction des réponses saisie (via l'applicabilité). 

Dans ce contexte, on peut avoir besoin de créer des règles enfants directement depuis le parent, sans avoir à réécrire l'espace de nom entier à chaque fois. Aujourd'hui on détourne le mécanisme `somme` avec `nom` pour aboutir à ce comportement, mais ce serait plus à propos d'utiliser `avec`.

En tout cas, merci de ton retour, c'est super précieux d'avoir un avis d'un réutilisateur sur la conception des nouvelles fonctionnalités :)

**Comment by johangirod** [comment]
Le mot-clé `avec` est maintenant utilisable depuis la version 1.0.0-beta.36

**Comment by mquandalle** [comment]
Comme tu le notais dans le message initial on utilise le même mot clé `avec` pour cette fonctionnalité de définition de variables locales et pour le mécanisme de `recalcul`.

À mon sens on peut voir le recalcul comme une sorte d'appel à une fonction a qui ont fourni des paramètres, et qui garde la situation courante comme valeur par défaut pour tous les paramètres non spécifiés :

```yaml
activité partielle . indemnité complémentaire . cotisations:
  recalcul:
    règle: cotisations
    avec:
      assiette: indemnité complémentaire . assiette
      plafond de la sécurité sociale: plafond sans proratisation
```

```js
rules['activites partielle']['indemnité complémentaire']['cotisations'] = rules['cotisations']({
  assiette: rules['activites partielle']['indemnité complémentaire']['assiette']
  'plafond de la sécurité sociale': rules['plafond sans proratisation']
})
```

C'est finalement quelque chose d'assez commun, peut-être qu'on pourrait l'écrire sans préciser `recalcul` :

```yaml
activité partielle . indemnité complémentaire . cotisations:
  valeur: cotisations
  avec:
    assiette: indemnité complémentaire . assiette
    plafond de la sécurité sociale: plafond sans proratisation
```


Ça fusionne deux fonctionnalités un peu différentes, mais peut-on imaginer une situation où l'on voudrait définir une variable `x = 3` dans la définition d'une formule mais pas dans celles d'éventuelles autres formules référencées ?

Bon j'ai conscience que c'est assez foufou de rendre “transparent” un comportement aussi lourd qu'un recalcul mais pourquoi pas ?
