### DISCUSSION TITLE
Mécanisme “variations”

### DISCUSSION THREAD

**Discussion by mquandalle** [publicodes/publicodes#170] [Ideas]
Ça fait plusieurs fois que je me fais avoir à écrire une liste de conditions sans l’envelopper dans une mécanisme `variations` :

```yaml
aides . grand reims:
  valeur: 25% * vélo . prix
  plafond:
    - si: vélo . cargo électrique
      alors: 500€
    - si: vélo . électrique
      alors: 300€
    - sinon: 0€
 ```

Ici le code ne fonctionne pas car il manque la ligne `variations:` dans le plafond.

Ceci dit cette manière d'écrire n'est pas choquante, peut-être qu'on pourrait la supporter.

On aurait même envie d'aller plus loin et de rendre équivalent le `si` et le `applicable si`, ainsi dans une liste c'est le premier élément applicable qui serait utilisé.

**Comment by laem** [comment]
Intéressant ! Je me permets de mettre en lien avec le mécanisme "correspondance" (je ne retrouve plus l'issue qui en parle). 

Ici ton code est un tableau de correspondance, qui correspond très bien au principe de l'objet yaml. 

```yaml
correspondance: 
  cargo électrique: 500€ 
  électrique: 300€
  sinon: 0€
```
