### DISCUSSION TITLE
Vérifier le type des règles

### DISCUSSION THREAD

**Discussion by mquandalle** [publicodes/publicodes#196] [Ideas]
Note: malgré le titre il s'agit d'un ticket qui ne devrait pas avoir trop d'implications théoriques contrairement à d'autres tickets ouverts ;)

L'idée c'est que l'on a plusieurs utilisations très différentes des règles publicode mais que cela n'est pas bien pris en compte dans le code du moteur, et pas suffisamment explicite dans la base de règle. Je propose d'ajouter un attribut `type` sur chaque règle qui permette de distinguer une `question`, d'un `remplacement`, d'une `notification`, etc.

Cela permettrait d'avoir un contrôle plus rigoureux des attributs côté publicode, et d'avoir le pendant côté typescript qui permette de lever une erreur si l'on fait par exemple

```ts
rules
  .filter(rule => rule.type === "question")
  .forEach(question => console.log(question.replace)) // TypeError: pas d'attribut "remplace" sur une "question"
```

On pourrait aussi choisir les noms d'attributs les plus adaptés en fonction de chaque utilisation, par exemple lors de la refacto des notifications betagouv/mon-entreprise#1113, j'ai utilisé l'attribut `description` pour mettre le contenu avant nommé `message` par analogie avec les autres règles publicode, mais il serait sans doute plus clair de ré-utiliser un attribut nommé `message`.

Sans avoir creusé le sujet, voici les types de règles publicode que nous utilisons aujourd'hui : question, groupe, texte, paragraphe, notification, remplacement, “formule” (?) (par défaut). Il faudra ensuite bien spécifier quels sont les attributs que l'on trouve sur ces différents types de règles, ainsi que les éléments en commun (l’applicabilité par exemple, une “question” comme une “notification” s'appuie sur l'attribut `isApplicable`).

Par ailleurs je pense que le type d'une règle est aussi une info à mettre en avant pour les relecteurs humains, actuellement on utilise un `type: groupe` ou `type: notification`, voire on se base sur un attribut “ad-hoc” (`question` ou `remplace`) mais je me demande s'il ne faudrait pas introduire une syntaxe supplémentaire pour définir le type d'une règle directement sur la première ligne:

```yaml
[notification] contrat salarié . temps de travail . temps partiel . contrôle temps min:
  sévérité: avertissement
  applicable si: heures par semaine < 24 heures
  message: Le nombre minimum d'heures par semaine est 24. Il est possible de descendre plus bas dans certains cas seulement. [Plus d'infos](https://www.service-public.fr/particuliers/vosdroits/F32428).
```

J'ai toujours un peu de réticence à introduire de la nouvelle syntaxe, mais peut-être cela fait-il sens ici ?
