### DISCUSSION TITLE
Proposition : formattage et pluralisation des unités dans le langage

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#199] [Ideas]
Aujourd'hui la pluralisation des unités est gérée via une option `getUnitKey` à fournir lors de lors de l'instanciation du moteur. La principale limite de cette approche est qu'elle découple les informations de la pluralisation de l'écriture des règles.

Ainsi, en fonction de l'implémentation de cette fonction, le parsing des règles ne sera pas effectué de la même manière. Pour être idempotent, le parsing doit maintenant avoir les règles ET la fonction getUnitKey.

Le besoin derrière getUnitKey est 
1. De gérer la pluralisation
2. De gérer les différentes écritures synonymes pour une même unité (€ - euro, employé - salarié, an - année, h - heure, min - minute, jours ouvrés - jours travaillés, kg - kilogrammes) ...
3. De permettre à l'utilisateur de définir ses propres unités / classe d'équivalence

### Proposition
Je propose de déplacer cette logique directement dans le langage lui même. Ainsi, on aurait en début de fichier publicodes les unités spécifiques sur lequel il opère.

Par exemple :
```yaml
#- Unités
employé: 
  pluriel: employés
  équivalences:
    - salarié
an: 
  pluriel: ans
  équivalences:
    - année
    - 12 * mois
    -  365.25 jours
€: 
  équivalences:
    - euro
```

L'idée c'est d'avoir les informations spécifiques au parsing des règles directement dans le langage lui-même afin d'éviter ce phénomène de "double dépendance" qui implique de dépendre de JS et de publicode.

Par défaut on peut supposer qu'un certain nombre d'unité standard soit implémentée dans `publicode-core` (€, heure, années, jours, trimestres, masse, distance, minutes...)
