### DISCUSSION TITLE
Remplacement d'une règle avec composantes nommées

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#209] [Q&A] [answered]
Je ne sais pas si c'est directement lié mais je constate un problème dans un remplacement d'une règle avec un produit et des composantes, lui-même utilisé dans une règle elle aussi remplacée.

Il semble que les composantes, bien que correctement calculées, ne soient pas utilisées dans le remplacement de 2ème niveau. Le seul contournement que j'ai trouvé pour le moment c'est d'éliminer l'utilisation du mécanisme `composantes` en découpant ma règle en 2. En fait, même en 3 car `composantes` est utilisé dans mon cas pour la part employeur et salarié. Je me retrouve avec 1 règle pour la part employeur, 1 pour la part salarié et 1 autre pour le total...

Ex : 

```yaml
perso . cotisations . patronales:
  remplace: contrat salarié . cotisations . patronales
  formule: contrat salarié . cotisations . patronales + truc

perso . cotisations . salariales:
  remplace: contrat salarié . cotisations . salariales
  formule: contrat salarié . cotisations . salariales + truc
```

Ne fonctionne pas (la valeur des règles ci-dessus ne change pas)

```yaml

perso . contribution d'équilibre technique:
  remplace: contrat salarié . contribution d'équilibre technique
  formule:
    produit:
      assiette: perso . autre . règle . montant
      composantes:
        - attributs:
            nom: employeur
          taux: 60%
        - attributs:
            nom: salarié
          taux: 40%
```

Fonctionne

```yaml

perso . contribution d'équilibre technique:
  remplace: contrat salarié . contribution d'équilibre technique
  formule:
    somme:
      - employeur
      - salarié

perso . contribution d'équilibre technique . employeur:
  acronyme: CET
  remplace: contrat salarié . contribution d'équilibre technique . employeur
  cotisation:
    branche: retraite
    type de retraite: complémentaire
    destinataire: AGIRC-ARRCO
  formule:
    produit:
      assiette: perso . autre . règle . montant
      taux: 60%

perso . contribution d'équilibre technique . salarié:
  acronyme: CET
  remplace: contrat salarié . contribution d'équilibre technique . salarié
  cotisation:
    branche: retraite
    type de retraite: complémentaire
    destinataire: AGIRC-ARRCO
  formule:
    produit:
      assiette: perso . autre . règle . montant
      taux: 40%
```

Même problème ?

_Originally posted by @fmata in https://github.com/betagouv/publicodes/issues/207#issuecomment-1099721356_

**Comment by johangirod** [comment, marked as answer]
Je me suis permis de déplacer dans une discussion, car ce n'était pas tout à fait le même problème :)

Effectivement les remplacement déclarés sur une règle parente ne concernent pas les règles imbriqués automatiquement. Il faudra redéclarer le remplacement sur ces règles. Cela peut être fait en continuant d'utiliser la syntaxe de composante : 

```yaml
perso . contribution d'équilibre technique:
  remplace: contrat salarié . contribution d'équilibre technique
  formule:
    produit:
      assiette: perso . autre . règle . montant
      composantes:
        - attributs:
            nom: employeur
            remplace: contrat salarié . contribution d'équilibre technique . employeur
          taux: 60%
        - attributs:
            nom: salarié
            remplace: contrat salarié . contribution d'équilibre technique . salarié
          taux: 40%
```

On préfère expliciter les remplacements des règles imbriquées pour éviter des effets de bords difficilement traçables.

Cela répond au problème soulevé ?
