### DISCUSSION TITLE
Retravailler le mécanisme inversion

### DISCUSSION THREAD

**Discussion by mquandalle** [publicodes/publicodes#305] [Ideas]
Nous sommes aujourd'hui obligés de spécifier toutes les inversions possibles dans notre base de règle.

Nous pourrions inférer cette information automatiquement à partir de l'objectif, des valeurs disponibles ainsi que de l'arbre des dépendances. Cela permettrait de supprimer un paramétrage purement technique de notre base de règles métier.

**Comment by mquandalle** [comment]
Je ne suis plus sûr de ça. Pour rappel la logique d'une inversion consiste à trouver un `x` tel que `y=f(x)` pour un `y` donné. Dans le cas général, il faut bien aider `inversion` en lui donnant indiquant quelle règle essayer. Si on prend un exemple simple :

```
net = brut + primes - cotis
```

et que l'on veut calculer le brut, il faut bien indiquer au moteur qu'il faut essayer des valeurs de `net` et pas de `primes` ou de `cotis`.

Peut-être que cette indication ne devrait pas être dans la base de règles métier, mais au niveau de l'appel `evaluate` : en disant "trouve moi le net qui correspond à ce brut", ce qui permettrait d'ailleurs de rendre toutes les formules inversibles (exemple trouver le revenu imposable à partir de l'IR payé, etc.) sans se limiter aux quelques inversions définies dans la base de règles.

**Comment by mquandalle** [comment]
Comme je le disais dans mon message précédent, je pense que l'inférence d'inversion au sens de mon message initial n'est pas possible. Si je lui demande de calculer le salaire brut, comment le moteur peut-il deviner tout seul de faire varier le net et pas par exemple une prime ou un avantage en nature (ce qui marcherchait aussi).

Je crois donc qu'il faut pouvoir exprimer "le brut qui correspond à telle valeur du net" dans la situation en entrée, que pensez-vous de :

```js
engine.setSituation({
  'contrat salarié . salaire brut': {
    inversion: {
      'contrat salarié . salaire net': '3000 €/mois'
    }
  }
})
```

**Comment by johangirod** [comment]
J'ai pas mal retourné la problématique, et j'en arrive à la conclusion que c'est loin d'être simple.

Je partage le constat qu'il est peu lisible d'avoir une liste de règle dans le paramètre inversion du moteur. Par ailleurs, certaines inversions sont spécifiques à un contexte donné, on veut pouvoir inverser le salaire brut avec un CA pour le cas d'un dirigeant de SASU, mais cela n'a pas de sens pour un salarié.

### Avantages de la première approche proposée

La solution proposée est plutôt une bonne approche, et elle m'était sympathique intuitivement. D'autant plus qu'elle marche déjà ! Si je reprends légèrement la syntaxe, on retombe sur une expression publicode qui fonctionne sans avoir besoin de modifications supplémentaires : 

```js
engine.setSituation({
  'contrat salarié . salaire brut': '3000 €/mois',
  'contrat salarié . salaire brut': {
    "inversion numérique": {
      avec: ['contrat salarié . salaire net']
    }
  }
})
```

### Limites de la solution

L'inconvénient, c'est que cela demande à l'utilisateur de connaître les valeur "pivot", et les valeurs inversibles reliées. Ceci dit, c'est déjà le cas aujourd'hui (puisque tout n'est pas inversible comme tu le fait remarquer justement sur les primes).

En revanche, deux aspects m'ont particulièrement freinés : 
1. C'est à l'utilisateur d'apporter la connaissance des inversions possible, alors que certaines inversions sont communes, pour ne pas dire attendue. Par exemple, on s'attends tout naturellement à pouvoir calculer un net à partir d'un brut et vice-versa. C'est une connaissance qui semble logique de trouver dans la base de règle.
2. Cela alourdi l'usage de setSituation dans le cas des simulateurs. On se retrouve à devoir différencier au sein de notre code applicatif le champs de saisi du brut (setSituation({brut: 2000}) et ceux des autres valeurs (setSituation({brut: {inversion: {net: 5000}}}).

### Un nouveau besoin

Par ailleurs, il y a un besoin que j'ai rencontré avec le simulateur multi activité auto-entrepreneur, qui a été également remonté par des réutilisateur de publicodes (chez Karburan), et qu'on sera surement amené à rencontrer de nouveau avec la simulation à l'échelle de l'entreprise : j'ai nommé l'inversion multiple

Pour reprendre ton exemple : 
```
net = brut + primes - cotis
```

Que se passe-t-il si on souhaite ajuster le brut et les primes en fonction du net ? Si pour 3000€, on souhaite répartir à 80% dans le brut et 20% dans le primes par exemple. Ce n'est pas possible en l'état actuel.

J'ai rencontré ce besoin pour répartir un net après impôt dans les 3 types de CA pour les auto entrepreneur à activité mixte. Mais on l'aura également pour la répartition d'un revenu net entre dividende et salaire pour un dirigeant de SASU. 

### Une nouvelle idée

Je propose que l'inversion ne soit pas spécifiée sur la règles à calculer mais sur celle qui permette d'effectuer le calcul. 
Au lieu de : 

```yaml
brut: 
  inversion avec:
    - net
    - total chargé 
    - CA
```

On aurait : 
```yaml
net: 
  formule: xxx
  permet de calculer: brut
```

On pourrait même imaginer avoir des inversions possibles uniquement dans certains contexte : 
```yaml
dirigeant . assimilé salarié:
  permet de calculer: 
    valeur: brut
    avec: CA
```

Ou encore, des inversions multiples : 
```yaml
autoentrepreneur . net après impôt: 
  formule: xxx
  permet de calculer: 
    - CA . vente hébergement
    - CA . service BIC
    - CA . service BNC
```

```yaml
dirigeant . SASU :
  question: "êtes vous dirigeant de sasu ?"
  permet de calculer: 
    valeur: 
      - entreprise . dividende
      - entreprise . rémunération dirigeant
    avec: 
      - revenu net après impôt
```

Le dernier gros avantage serait de pouvoir spécifier des inversions en fonction de son contexte d'utilisation en ajoutant des règles spécifiques. 

Par exemple : 

```yaml
mon contexte . total chargé:
  valeur: contrat salarié . total chargé
  permet de calculer: 
    - brut: 80%
    - primes: 20%
```

C'est pour l'instant juste à l'état d'ébauche d'idée. Je pense que cela est amené à être calmement réfléchit, c'est tout de même un changement d'ampleur... Mais je suis curieux de connaître vos avis sur la question.
