### DISCUSSION TITLE
[SUGGESTION] Ajout d'un mécanisme "Moyenne"

### DISCUSSION THREAD

**Discussion by Clemog** [publicodes/publicodes#356] [Ideas]
Côté Nos Gestes Climat, on utilise de plus en plus Publicodes pour effectuer les calculs depuis les sources de données primaire afin de retravailler certains facteurs d'émission.

Je me rends compte que je suis amené à artificialiser de plus en plus le calcul de moyenne. Je me dis que ça pourrait être intéressant de l'implémenter comme un mécanisme (et surement pas très compliquer). L'idée serait de l'utiliser comme :

```yaml
calcul moyenne actuel:
  description: | 
  Ceci est la manière dont je calcule une moyenne actuellement, mais très peu pratique 
si on rajoute un élément dans la moyenne (risque d'oublier de changer le facteur, ici 3)
  formule: (a + b + c) / 3

a: 10
b: 50
c: 100

calcul moyenne envisagé:
  description: Ceci est la manière dont on pourrait calculer une moyenne
  moyenne:
    - a
    - b
    - c
```

On pourrait même envisager un système de pondération (pour le moment pas vraiment le besoin) et j'ai l'impression qu'on a besoin le système de liste ?

ping @laem @EmileRolley

Qu'en pensez-vous ?
