### DISCUSSION TITLE
Une valeur par défaut non binaire pour les questions booléennes

### DISCUSSION THREAD

**Discussion by Clemog** [publicodes/publicodes#390] [Ideas]
## Actuellement

Le moteur gère automatiquement les questions booléennes :

```
question booléenne:
  question: oui ou non ?
  par défaut: oui
```

### Avantages

Je n'ai pas forcément en tête l'historique de cette feature ni tout en tête sur les implications (je ne vois pas de paragraphe dédié dans la doc ?) mais selon moi l'avantage principal est l'allègement de l'écriture du code (pas besoin de créer les règles `rule . oui` / `rule . non`, pas besoin de décrire les possibilités de la question dans le modèle), la gestion des conditions est faciliter par le fait que la règle est set à `true` ou `false` implcitement

### Limites

Par défaut, c’est “oui” → 1 ou “non” → 0. 
Pour faire en sorte qu'une règle reste applicable et présente une valeur, on mettra alors à “oui” certaines règles que l’on aimerait pourtant être à “non” ou plutôt “moyenne” d’un point de vue design (exemple pour les 2 roues motorisés ou la clim côté NGC)

On aimerait donc pouvoir proposer une valeur par défaut indépendamment de la valeur affichée.

```yaml
logement . climatisation . empreinte climatiseurs:
  applicable si: présent
  formule: nombre * empreinte unitaire
  unité: kgCO2e

logement . climatisation . présent:
  question: Utilisez-vous un système de climatisation pour refroidir votre logement (climatiseur électrique, pompe à chaleur) ?
  # Valeur par défaut à oui pour l'intégrer dans l'empreinte moyenne
  par défaut: oui

logement . climatisation . empreinte unitaire:
  formule: 100
  unité: kgCO2e/climatiseur

logement . climatisation . nombre:
  applicable si: présent
  question: Combien de climatiseurs électriques possédez-vous ?
  # On a une valeur par défaut à 0.3 qui correspond à la moyenne 
  # et non à la valeur par défaut pour les possesseurs de système de climatisation
  par défaut: 0.3
  unité: climatiseur
```

## Nouvelle proposition

Ajouter/améliorer le mécanisme dans [Publi.codes](http://Publi.codes) ?

```yaml
# J'aimerais savoir si il y a 0 ou 1 pomme. Mais par défaut, il y en a une demie.
# Dans ce cas et actuellement, je ne peux pas le spécifier.

pommes:
  applicable si: présent
  formule: 1

pommes . présent:
  question: Avez-vous une pomme ?
  par défaut: non
```

Un "hack" fonctionne actuellement :

```yaml
pommes:
  applicable si: présent
    formule:
      variations:
        - si: usager = 'affirmatif'
          alors: 1
        - si: usager = 'négatif'
          alors: 0
        - si: usager = 'moyenne'
          alors: 0.5

pommes . présent:
  question: Avez-vous une pomme ?
  avec:
    moyenne:
  # Ces règles ne peuvent pas être "oui" on "non" car ces règles 
  # sont particulières pour publicodes.
    affirmatif:
      titre: Oui
    négatif:
      titre: Non
  par défaut: "'moyenne'"
  formule:
    une possibilité:
      choix obligatoire: oui
      # La règle "moyenne" n'est pas dans les propositions
      possibilités:
        - affirmatif
        - négatif
```

Cette écriture est assez lourde et ne résout que le pb des questions booléennes et non des questions avec plusieurs possibilités. 
Pour le premier point, on pourrait imaginer une solution plus élégante en intégrant une nouvelle feature dans Pulicodes.

Tentative:

```yaml
# pommes sera non applicable si la réponse à la question est 'non'
# Dans ce cas, on spécifie plus clairement ce qu'est la règle (qui renvoie donc un booléen), un peu sur le même format que "plusieurs possibilités"

pommes:
  question: Avez-vous une pomme ?
  formule:
    booléen:
      par défaut: 0.5 
      
      ou
  
pommes:
  question: Avez-vous une pomme ?
  formule: booléen
  par défaut: 0.5 
      
```

Lié en partie à https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1422 qui se veut plus complexe car introduit la notion de valeur par défaut via une échelle de répartition entre `plusieurs possibilités`. On pourrait envisager une solution d'abord pour ce cas, qui s'appliquerait naturellement aux questions booléennes (répartition entre le `oui` et le `non`) mais je me rends compte que j'ai du mal à définir une manière de l'écrire...

```yaml
panier:
  formule:
    variations:
      - si: panier . fruit = 'pomme'
        alors: nombre de pommes
      - si: panier . fruit = 'poire'
        alors: nombre de poires
     # par défaut: 25% * 10 pommes (par défaut) + 75% * 20 poires (par défaut) = 10

panier . fruit:
  question: Avez-vous des pommes ou des poires dans votre panier ?
  avec:
    pomme:
    poire:
  formule:
    une possibilité:
      choix obligatoire: oui
      possibilités:
        - pomme
        - poire
  par défaut:
    pomme: 50%
    poire: 25%

panier . fruit . nombre de pommes:
  question: Combien de pommes ?
  par défaut: 10

panier . fruit . nombre de poires:
  question: Combien de poires ?
  par défaut: 20
```

Ping @EmileRolley @laem

**Comment by EmileRolley** [comment]
Je me permet de clarifier la problématique @Clemog : tu aimerais **conditionner un calcul** sur le fait qu'une question (règle comportant un mécanisme `question`) ait **été répondu ou non** et le cas échéant sur **sa valeur retourné**e (ici `oui` ou `non`).

Il semblerait qu'il y ai déjà tous les mécanismes Publicodes pour cela. En effet :
- le mécanisme `applicable si` permet de conditionner sur la réponse booléenne d'une question,
- le mécanisme `est défini` permet de conditionner sur le fait que la question ai été répondu.

Ainsi, ton exemple sur le calcul de l'empreinte de la climatisation pourrait être réécrit de la façon suivante :

```yaml
logement:

logement . climatisation:
  formule:
    variations:
      - si: 
          est défini: présent
        alors: empreinte climatiseurs
      - sinon: empreinte climatiseurs par défaut

logement . climatisation . présent: 
  question: Utilisez-vous un système de climatisation pour refroidir votre logement (climatiseur électrique, pompe à chaleur) ?

logement . climatisation . empreinte climatiseurs:
  formule: nombre * empreinte unitaire
  unité: kgCO2e

logement . climatisation . empreinte climatiseurs par défaut:
  formule: 0.3 climatiseur * empreinte unitaire
  unité: kgCO2e

logement . climatisation . empreinte unitaire:
  formule: 100
  unité: kgCO2e/climatiseur

logement . climatisation . nombre:
  applicable si: présent
  question: Combien de climatiseurs électriques possédez-vous ?
  par défaut: 1
  unité: climatiseur
```
