### DISCUSSION TITLE
[Syntax] Renommer le mot-clé « avec »

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#409] [Polls]
Le mot clé « avec » est un mécanisme qui permet de définir des règles ayant comme espace de nom la règle courante. Il permet ainsi d'éviter de réécrire l'espace de nom complet à chaque fois, et utiliser l'indentation pour indiquer l'appartenance au même espace de nom.

On écrit : 
```yaml
a: 
  somme: 
    - x 
    - 5
  avec:
    x: 10
```
au lieu de 

```yaml
a: 
  somme: 
    - x 
    - 5
a . x : 10
```

## Problème avec l'existant

Le nom de ce mécanisme, `avec`, n'est pas idéal : 
1. on ne comprend pas directement que de nouvelles règles enfant seront créées
2. on peut penser qu'il agit comme le mécanisme `recalcul` : une modification de la valeur dans le contexte d'évaluation locale.

### 1. `avec` crée de nouvelles règles enfants silencieusement

En effet, cela n'est pas clair que les éléments listées sont des règles exposées, au même titre que les règles de « premier niveau ». Le mot clé laisse penser au contraire qu'il s'agit de variables locales privées, uniquement présente pour améliorer la lisibilité du calcul principal en le décomposant. 

Seule la lecture de la documentation permet de comprendre que ce n'est pas le cas.

### 2. `avec` ne change pas la valeur de la variable globalement

Dans l'exemple suivant : 
```yaml
x: 1
double x: 2 * x
a: 
  somme: 
    - x
    - double x
  avec:
    x: 10
```

Une lecture naïve peut interpréter le mot clé `avec` comme « modifie la valeur de x pour l'évaluation courante ». On s'attend donc à ce que `x` soit modifiée **globalement** lors du calcul courant. Or ce n'est pas le cas : `avec` redéclare la règle `x` dans l'espace de nom `a` et vient [« ombrager »](https://en.wikipedia.org/wiki/Variable_shadowing) la règle `x` déclarée à la racine. 

Par conséquent, l'évaluation de `a` donne « 10 + 2 * 1 ». On s'attend à ce que ce soit « 10 + 2 * 10 ».

![Copilot est d'accord](https://user-images.githubusercontent.com/1730702/205682715-9d5e4051-44be-4bcd-bbb2-b14533602dbc.png)

On s'attend à ce qu'`avec` fonctionne comme `recalcul`, qui utilise aussi le mot clé `avec`

## Proposition

Nous proposons de renommer `avec` pour éviter ces confusions. Voici les propositions (n'hésitez pas à commenter si vous en avez d'autres) :
1. `définitions`
2. `règles enfants`
3. `def`
4. `est défini ici`

**Comment by mquandalle** [comment]
Personnellement c'est une syntaxe que je n'ai jamais vraiment utilisé. Mais c'est très utilisé sur mon-entreprise, nosgestesclimat et les apps datagir (modele-numerique et benefriches). Pour voir toutes les utilisations: 

```sh
npx zx https://raw.githubusercontent.com/mquandalle/count-publicodes-lines/master/count-publicodes-lines.mjs
grep -r "avec:" -B 1 -A 3 /tmp/count-lines/
```

Je partage les critiques de l'existant, l'utilisation de `avec` est syntaxiquement très différente de la déclaration habituelle d'une règle `marègle: sa valeur` pour un comportement identique. À mon sens s'il y a introduction d'un mot clé type `def` pour définir des règles imbriquées, il serait logique de l'utiliser aussi pour définir des règles de premier niveau, le comportement serait alors plus intuitif.

Une idée peu réfléchie : 

```yaml
[def] à payer:
  somme:
    - cotisations
    - frais de dossier
   [def] frais de dossier: 10€

[def] cotisations:
  produit:
    assiette: 1000€
    [def] taux: 10%
```

Règles définies: `à payer`, `à payer . frais de dossier`, `cotisations`, `cotisations . taux`, une règle définie par utilisation du mot clé `def`.

Ou un symbole

```yaml
@ à payer:
  somme:
    - cotisations
    - frais de dossier
   @ frais de dossier: 10€

@ cotisations:
  produit:
    assiette: 1000€
    @ taux: 10%
```

Ça fait bizarre, mais dans tous les cas le principe que la définition d'une règle (imbriquée ou de premier niveau) se fasse d'une seule manière me semble désirable.
