### DISCUSSION TITLE
[Syntax] Changer le mécanisme `recalcul`

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#410] [Polls]
Aujourd'hui, recalcul accepte deux paramètres règle et avec :
```
b: 
  recalcul: 
    règle: a
    avec: 
      x: 4
```

## Problème avec l'existant
1. Le mot clé `règle` est trompeur : on peut en fait utiliser une expression
2. `recalcul` est trompeur, il s'agit d'un calcul en modifiant le contexte d'évaluation avec les valeurs passée en paramètre (on ne « recalcul » pas forcément une variable

### 1. Renommer `règle` en `valeur` et passer `recalcul` en mécanisme chainé 
On écrirait ainsi
```
x: 10
b:
  valeur: a
  type: €/an
  arrondi: oui
  titre: bla
  contexte:   
      x: 4
```

### 2. Renommer `recalcul avec`

Propositions : 
1. `calcul avec`
2. `avec le contexte`
3. `avec` (plus court, mais la migration v1.0 sera plus complexe cf #409)
4. `contexte`
