### DISCUSSION TITLE
Expression régulière

### DISCUSSION THREAD

**Discussion by AdrienRosi** [publicodes/publicodes#452] [General]
Bonjour à toutes et à tous,

Je voulais savoir s'il est possible (ou prévu) d'utiliser une expression régulière pour appliquer une règle ou une formule ?

Par exemple

```
code postal: "'97490'"

département d'outre-mer:
  variations:
    - si: ^974[0-9]{2}$
      alors: oui
      sinon: non
```

Merci pour ce beau projet.

**Comment by johangirod** [comment]
Bonjour Adrien, 

Pour l'instant, il n'est pas possible de faire du matching de chaine de caractère avec une expression régulière. À première vue, ce serait une fonctionnalité puissante et facile à ajouter. 

Cependant, il y a risque non négligeable de perte de lisibilité du code, particulièrement pour les juristes / experts-métiers qui peuvent être amenés à faire des sessions de pair avec des devs.

On pourrait imaginer commencer par ajouter des helpers « commence par », « termine par » et « contient » dans un premier temps, qui permettent de garder la lisibilité tout en répondant au cas d'usage cité.

Qu'en penses-tu ?

**Comment by AdrienRosi** [comment]
Cela me semble répondre à une majorité de cas d'usage. Cette fonction supposerait l'intégration des mots clés `et` et `ou` pour couvrir des expressions complexes de façon plus lisible, même si en l'état on peut toujours broder avec `une de ces conditions` et  `toutes ces conditions`.

Ayant découvert la lib hier, il me faudra un peu de temps pour proposer des PR mais la volonté de contribuer activement y est.

**Reply by johangirod** [reply]
Les mots clés `et` et `ou` existent déjà mais ne sont pas encore intégrés dans la grammaire des expressions "inline". 

Il est ainsi possible de faire : 
```yaml
et: 
  - condition 1
  - condition 2
```
mais pas 
```condition 1 ET condition 2```

Ce serait une modification assez facile à apporter ceci dit, il suffit de modifier la [grammaire du langage](https://github.com/publicodes/publicodes/blob/master/packages/core/src/grammar.ne)

**Reply by AdrienRosi** [reply]
OK pour résumer l'idée est d'arriver à : 

````
code postal: "'97490'"

# Version dépliée
département d'outre-mer:
  ou:
    - code postal commence par "971"
    - code postal commence par "972"
    - code postal commence par "973"
    - code postal commence par "974"
    - code postal commence par "976"
# Version inline
département d'outre-mer:
  ou:
    - code postal commence par "971" OU code postal commence par "972" OU code postal commence par "973" OU code postal commence par "974" OU code postal commence par "976"
````
