### DISCUSSION TITLE
looper sur les items d'un identifiant pour un calcul

### DISCUSSION THREAD

**Discussion by rogerburton** [publicodes/publicodes#46] [Q&A]
Bonjour,

je n'ai pas trouvé le moyen (ou la syntaxe) pour demander à un calcul de looper sur les items d'un identifiant.
Supposons une facture multilignes avec 4 items chacune comportant un prix htva et un taux de tva, comment opérer le calcul "total tva comprise" de ladite facture ?

désolé si ma question est triviale, je découvre ...
Merci

**Comment by mquandalle** [comment]
Bonjour et bienvenue !

C'est une bonne question :) Il n'est pour l'instant possible ni de définir un type liste, ni de faire une boucle sur les règles dans un espace de nom, et nous sommes donc obligés d'expliciter les items au niveau de la somme : https://github.com/betagouv/mon-entreprise/blob/d7f140334e67a8c16cff2ac9ea367d2cc87ddf2e/mon-entreprise/source/rules/salari%C3%A9.yaml#L1601-L1616. C'est un peu comme si dans Excel on pouvait faire `=A1+A2+A3` mais pas `=SOMME(A1:A3)`. C'est un point qui me paraît à améliorer mais il faut que nous réfléchissions un peu mieux à la manière dont ça peut s'intégrer en publicodes.

**Comment by mquandalle** [comment]
Et pouvoir faire une liste d'items dont chaque item à un attribut HT, un taux de TVA et une valeur TTC est un manque du langage, pour le moment on est obligés de créer des règles `item 1`, `item 2`, etc., voir cet exemple d'un utilisateur tiers https://github.com/Hotsnown/succession/blob/e3a0aed4ca7b3e9e72548b4bfb31c4f131a803ad/src/core/explain/rules/ordre1.ts#L9-L16 cc @Hotsnown

**Comment by revolunet** [comment]
Jai un peu la même question concernant les boucles, quand on a des répétitions de règles similaires

En 1ere piste je pensais naïvement à quelque chose comme:

```yaml
listes:
    sexes:
        - Homme
        - Femme
    tranches d'âge:
        - moins de 15 ans
        - de 15 à 25 ans
        - de 25 à 45 ans
        - plus de 45 ans

pour chaque tranche dans listes . tranches d'âge:
    effectifs . [tranche] . nombre:
        question: Effectifs pour "[tranche]" ?
        valeur: 0

total effectifs:
    somme:
        pour chaque tranche dans listes . tranches d'âge:
            - effectifs . [tranche] . nombre

# version pour itérer sur plusieurs listes
pour chaque tranche dans listes . tranches d'âge et chaque sexe dans listes . sexes:
    effectifs . [tranche] . [sexe] . nombre:
        question: Effectifs pour "[tranche] [sexe]" ?
        valeur: 0

total effectifs:
    somme:
        pour chaque tranche dans listes . tranches d'âge et chaque sexe dans listes . sexes:
            - effectifs . [tranche] . [sexe] . nombre

```
