### DISCUSSION TITLE
Explicitation des règles d'entrées (et de sortie) (WIP)

### DISCUSSION THREAD

**Discussion by EmileRolley** [publicodes/publicodes#554] [Ideas]
J'entame une petite réflexion sur la formalisation d'une syntaxe pour préciser les règles d'_entrées_ (les questions/règles avec valeurs par défaut) avec leur type attendue et ainsi pouvoir inférer une situation complètement typée pour chaque modèle et les mettre en avant dans la documentation par exemple. On pourrait également l'étendre pour les règles de _sorties_ même si par défaut on peut considérer que n'importe qu'elle règle puisse l'être.

Par exemple, pour les règles suivantes :

```yaml
salaire brut: 
  entrée: décimal
  question: Quel est votre salaire brut ?
  par défaut: 1500 €/mois

cotisations salariales:
  produit:
    - salaire brut
    - taux
  avec:
    taux: 21.7%

salaire net: salaire brut - cotisations salariales
```

On peut déterminer que la `salaire brut` est un paramètre du modèle qui attend un nombre décimal et les attributs `questions` et `par défaut` deviennent optionnels. Et le modèle peut exposer le type situation suivant :

```typescript
type Situation = {
  "salaire brut": number
}
```

On peut aller plus loins en affinant le type d'entrée attendue d'une règle :

```yaml
salaire brut: 
  entrée:
    type: décimal
    min: 0
  unité: €/mois
```

On peut également préciser si le champs de l'objet `Situation` est optionnel ou non avec la présence ou non du mécanisme `par défaut`.

Comme type de base il y aurait `décimal`, `entier`, `booléen` et `énumération`.

**Si la proposition parait est considérée comme utile, il faudrait formaliser la définition de cet attributs.**

**Comment by johangirod** [comment]
Je suis 100 % aligné sur le besoin de pouvoir générer la signature d'un paquet publicodes, et de réduire sa surface à un ensemble limité de règles exposées. 

Néanmoins, je ne suis pas certain que cela nécessite une nouvelle syntaxe. Car, en réalité, il est aujourd'hui possible d'avoir ce comportement à l'aide de deux fonctionnalités : l'inférence de type et les règles privées. Je propose doc d'améliorer ces deux aspects.

## 1. Inférence de type

Tout d'abord, l'inférence de type. Quoiqu'encore primaire, elle fonctionne à peu près ([voir la fonction](https://github.com/publicodes/publicodes/blob/9060a3cf923d6977a64c3fb898769b4a59be4130/packages/core/src/inferNodeType.ts#L17)). Elle permet notamment de récupérer le type d'une règle, ainsi que si cette dernière peut être rendue `non applicable`.

Il est par ailleurs possible de préciser le type d'un nœud non défini grâce à l'attribut `type` (non documenté). Ce dernier accepte les valeurs `number`, `boolean`, `string` et `date`. Par défaut, une constante non définie sans type et sans unité est considérée comme booléen. On peut également préciser si une règle accepte `non applicable` comme entrée en ajoutant `possiblement non applicable : oui` dans ses propriétés. 

Je serai d'avis d'améliorer / spécifier / documenter le comportement actuel. Je pense à : 
- Changer la langue des valeurs de `type` en français
- Exposer le type dans les retours de `evaluate` ou de `getRule`
- Spécifier des types plus précis qu'actuellement, quitte à ne pas les implémenter dans le moteur de vérification dans un premier temps (par exemple `decimal`, `entier`, `date`, `options` ou `énumération`).

## 2. Les règles privées

Il est possible de restreindre la surface d'un module grâce aux règles privées. 
```yaml
a: 
  privée: oui
  valeur: 4
b: a + 5
```
```js
engine.evaluate('a') // Erreur
```

Pour des raisons de rétrocompatibilité, toutes les règles sont publiques par défaut. Cependant, on pourrait ajouter une option de compilation pour inverser ce réglage, et rendre toutes les règles privées par défaut. Seules les règles spécifiées comme `accessible` seraient exposées. 

Pour avoir une signature encore plus fine : 
```
b: 
  accessible: lecture uniquement
```

## 3. Autres considérations

- Pour borner les valeurs d'entrée, on peut s'appuyer sur les mécanismes existants `plafond` et `plancher`. De même qu'`arrondi` par exemple.
- En revanche, je ne me baserai pas sur le mécanisme `par défaut` pour déterminer si une valeur est optionnelle. Par exemple : 
  ```yaml
  salaire mensuel:
    par défaut: 2500 €/mois
    valeur: salaire horaire * 121 heures
  salaire horaire: # ici salaire horaire peut être non défini, sans qu'il n'ait de valeur par défaut.
  ```
  On pourrait utiliser `possiblement non défini: non` (sur le même principe que `possiblement non applicable: oui`)
