### DISCUSSION TITLE
[Proposal] Sélecteurs et patrons de règles

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#561] [Ideas]
## Cette proposition caduque car remplacée par #566 

# Proposal : Sélecteurs et patrons de règles

Version : 1

## Contexte 

Une des fonctionalités manquante la plus demandée est la possibilité de définir des listes dans publicodes et d'avoir des mécanismes pour les manipuler.

Les cas d'usage associés sont repertoriés dans le ticket #392.

Cette proposition est l'une des deux existante visant à répondre à ces cas d'usage.
_(todo : faire la deuxième)_

## Principe

Le concept au coeur de cette proposition est de ne **pas introduire de type liste** de premier niveau dans publicodes, mais de d'utiliser les espaces de noms comme proxy. Nous verrons que cela permet de répondre aux différents cas d'usage sans introduire un nouveau type ou des nouveaux mécanismes. 

## Selecteurs

Les selecteurs permettent de définir un ensemble de règles. Ils peuvent être utilisés à chaque endroit ou une liste de règles est attendue. Par exemple, les mécanismes `somme` ou `inversion`.

#### Selecteur universel `[*]`

Ce selecteur permet de selectionner toutes les règles enfants directes d'un espace de nom.

Par exemple, dans le code suivant : 

```yaml
a:
a . b: 1
a . c: 2
a . b . d: 3
a . c . d: 4
d: 5
```

`a . [*]` selectionne toutes les règles enfants directes de `a` soit `a . b` et `a . c`. En revanche `a . b . d` n'est pas selectionné.

Il est possible d'insérer un selecteur à n'importe quel niveau de l'espace de nom. Par exemple, `a . [*] . d` selectionne `a . b . d` et `a . c . d`.

#### Selecteur récursif `[**]`

Ce selecteur permet de selectionner toutes les règles enfants directes et indirectes d'un espace de nom.

Dans l'exemple précédent, `a . [**]` selectionne `a . b`, `a . c` et `a . b . d`.

De même, `[**] . d` selectionne `a . b . d` et `a . c . d`, ainsi que `d`.

### Selecteurs dynamiques 

On peut définir des selecteurs dynamiques qui dépendent de la situation. Les selecteurs dynamiques sont définis dans un espace de nom `!selecteurs`.

Par exemple, on peut définir un selecteur qui selectionne les enfants de `a` dont la valeur est supérieure à 10.

```yaml
a:
  b: 5
  c: 15
  d: 20
```
  
```yaml
!selecteurs:
  supérieur à 10:
    condition: [valeur] > 10 ## Pour accéder à la valeur courante de la règle on utilise « [valeur] »
```

**Selecteurs:**
- `condition`: selectionne les enfants dont la condition est vraie (_TODO : utiliser `filtre` ?_)
- `nom`: selectionne les enfants dont le nom est égal à la valeur donnée
- `trié par`: trie les enfants et transforme en liste ordonnée

**Selecteurs sur les listes ordonnées**
_Actif après un tri ou déclarée via `liste` (voir plus bas)_
- `premier`: selectionne le premier enfant du selecteur
- `dernier`: selectionne le dernier enfant du selecteur
- `numéro: <n>`: selectionne l'enfant au numéro donné (commence à 1)
- `index: <n>`: selectionne l'enfant à l'index donné (commence à 0) (à voir si on veut simplifier la syntaxe en utilisant `<n>`)
- `premiers: <n>`: selectionne les n premiers enfants
- `derniers: <n>`: selectionne les n derniers enfants

On peut également combiner les selecteurs.

```yaml
!selecteurs: 
  plus petit élément supérieur à 10:
    - condition: [valeur] > 10
    - trié par: [valeur]
    - premier
```

Par défaut les selecteurs s'appliquent à l'ensemble des règles. 

```yaml
!selecteurs: 
  supérieur à 10:
    - **
    - condition: [valeur] > 10
```

### Utilisation avec des mécanismes

On peut utiliser ce type dans les appels aux mécanismes de [type liste](https://publi.codes/docs/manuel/mecanismes#les-m%C3%A9canismes-%C3%A0-liste)

```yaml
consommations:
  avec:
    menu: 16€
    café: 2€
    limonade: 4€

à payer:
  somme: consommations . [*]
```

Si l'on souhaite concaténer deux selecteurs, il suffit de les mettre dans un tableau.

```yaml
somme: 
  - consommations . janvier . [*]
  - consommations . février . [*]
```

À noter, on peut également inclure plusieurs niveaux de selecteurs.

```yaml
somme: 
  - consommations . [*] . [*]

```

**Nouveau mécanisme `nombre`**

Pour obtenir le nombre d'éléments d'un selecteur, on introduit un nouveau mécanisme `nombre de`. (question `nombre` ou `compte` ?)

```yaml
enfants:
  avec:
    alice:
      age: 10
    bob:
      age: 20

nombre d'enfants: 
  nombre de: enfants . [*]
```
pace de nom possède une valeur, celle ci est retournée dans la clé `valeur`.

### Règles indexées par des nombres (liste ordonnée)

Il est maintenant possible de définir un espace de nom dont les enfants sont indexées par des nombres. Pour cela, on utilise la syntaxe `liste`. Le selecteur `[n]` permet de selectionner tous les enfants indexés par un nombre. Pour accéder à la valeur d'un index, on utilise `[index: <n>]`. (à voir si on peut simplifier la syntaxe en utilisant `[<n>]`)

```yaml
enfants:
  liste:
    - nom: Alice
      date de naissance: 01/11/2024
    - nom: Bob
      date de naissance: 03/12/2004
  avec: 
    nombre: 
      nombre de: enfants . [n]
```

#### `select`
Pour évaluer un selecteur, on introduit une nouvelle méthode `select` dans l'API.

```js
import Engine from 'publicodes'
engine.select('consommations . [*]') 
// retourne [`consommations . menu`, `consommations . café`, `consommations . limonade`]
```

#### `evaluateJSON`
> _todo : à conserver ?_
Cette méthode permet d'évaluer un selecteur et de retourner les valeurs sous forme d'objet JSON.

```js
engine.evaluateJSON('consommations . [*]')
// retourne { menu: 16, café: 2, limonade: 4 }

engine.evaluateJSON('enfants . [n]')
// retourne [{ nom: 'Alice', date de naissance: '01/11/2024' }, { nom: 'Bob', date de naissance: '03/12/2004' }]
```

> _todo : setSituationJSON ?_ 

## Patrons de règles 

Les patrons de règles permettent de définir un modèle communs à un ensemble de règle. Dans la pratique, cela permet d'obtenir des comportements de typage d'objet et d'héritage.

> :::info
> **On propose le terme de « patron de règle » plutôt que « modèle de règle » pour éviter la confusion avec les modèles métiers.**
> :::

### Syntaxe

Pour définir un patron de règle, on utilise un selecteur suivi de `:`. Toutes les règles qui matchent le selecteur hériteront du patron de règle.

```yaml
a . [*]: # nouveau patron de règle
  # toutes les clés définies ici seront héritées par les règles enfants directes de a
```
> Todo : peux-t-on créer des règles dynamiquement à partir de patrons de règles ? à priori oui grâce au mécanisme `avec`. C'est à mieux définir

Cf exemple ci-dessous.

### Patrons de liste ordonnée

> Todo : à mieux définir

Lorsque l'on définit un patron à partir d'une liste ordonnée, on a accès à d'autres selecteurs spécifiques.

- `[précédent]`: selectionne l'enfant précédent
- `[précédents]`: selectionne tous les enfants précédents
- `[suivant]`: selectionne l'enfant suivant
- `[suivants]`: selectionne tous les enfants suivants

```yaml
mois . [*]: # Patron de règle qui s'applique à tous les mois
  avec:
    dépenses: 
    revenus: 
    solde: revenus - dépenses

mois . [trié par: date]:
  cumul: [précédent] . solde + solde # version 1
  cumul: 
    somme: [précédents] . revenus
    abattements: [précédents] . dépenses

```

## Implémentation des des cas d'usage
Avec les selecteurs et les patrons de règles, on peut implémenter les cas d'usages listés dans le ticket #392.

### 1. Opération TVA

> Supposons une facture multilignes avec 4 items chacune comportant un prix htva et un taux de tva, comment opérer le calcul "total tva comprise" de ladite facture ?

```yaml
facture . détail:
  ligne 1:
    avec: 
      prix HT: 13€
      TVA: 20%
  ligne 2:
    avec: 
      prix HT: 32€
      TVA: 5.5%
  ligne 3:
    avec: 
      prix HT: 10€
      TVA: 10%
  ligne 4:
    avec: 
      prix HT: 5€
      TVA: 20%
```

#### Proposition 1. Nouveau mécanisme `sommeprod`

Comme dans excel.

```yaml
facture . total:
  sommeprod:
    - détail . [*] . prix HT
    - 100% + détail . [*] . TVA
```
#### Proposition 2. Utilisation d'un patron de règle

```yaml
facture . détail . [*]: # Patron de règle qui s'applique à toutes les lignes
  avec:
    prix TTC: prix HT + TVA # une règle prix TTC est créée pour chaque ligne

facture . total: 
  avec: 
    HT:
      somme: détail . [*] . prix HT
    TTC:
      somme: détail . [*] . prix TTC
```
#### Utilisation pour typer des objets

Dans l'exemple ci-dessus, on peut également utiliser les patrons de règles pour s'assurer que chaque ligne de la facture est bien typée.

```yaml
facture . détail . [*]:
  avec:
    prix HT: 
      unité: €
    TVA: 
      unité: '%'
      par défaut: 20%
```

Toutes les lignes de la facture hériteront de ces règles.

### 2. Définir plusieurs enfants

```yaml
enfants: 
  liste: 

enfants . [*]: 
  avec:
    nom:
      type: texte
    date de naissance:
      type: date
    âge:
      durée:
        depuis: date de naissance
        unité: ans
    majeur: âge > 18 ans
```

```yaml
majorité: 18 ans

!selecteurs: 
  majeurs:
    condition: age > majorité

  triés par âge:
    trié par: age
  
  ainé: 
    - triés par age
    - premier


nom de l'ainé:
  valeur: enfants . [ainé] . nom

age moyen des enfants majeurs:
  moyenne: enfants . [majeurs] . age

age du plus jeune majeur: 
    valeur: enfants . [majeurs] [triés par age] [premier]. age

```

### 3. Réécrire les mécanismes de liste
> Ré-écrire les mécanismes barème/grile/etc comme des mécanismes opérant sur des listes. Doit permettre de mieux composer les mécanismes au sein des tranches, par exemple rendre une tranche à taux réduit non applicable dans certains cas (utile pour l'impôt sur les sociétés par exemple Simulateur d'impôt sur les sociétés betagouv/mon-entreprise#1230)

```yaml
# Recode le mécanisme barème

[**] barème: # s'applique à toutes les règles nommées barème
  somme: tranches . [n] . montant
  avec:
    assiette:
      description: Montant de l'assiette
    tranches: 
      description: Liste des tranches
      liste: 
    
    !selecteurs:
      tranches applicables: 
        - trié par: plafond
        - condition: 
            est applicable: [valeur]
    
    tranches . [n]: # Patron de règle qui s'applique à toutes les tranches
      avec:
        plafond: 
          description: Plafond de la tranche
        taux: 
          description: Taux de la tranche
    
    tranches . [tranches applicables]:   
      avec:
        montant: 
          description: Montant de la tranche
          produit: 
            - taux
            - le minimum de:
                - assiette
                - plafond
              abattement: [précédent] . plafond


barème:
  titre: Barème de l'impôt sur les sociétés
  avec:
    assiette: 10000€
    tranches: 
      liste:
        - avec:
            plafond: 10000€
            taux: 10%
        - avec:
            plafond: 20000€
            taux: 20% 
      
```

### 4. Ajouter des éléments aux listes avec `remplace`

```yaml
primes:
  somme: [*]
  avec:
    activité:
    exceptionnelle:

convention collective . bâtiment . primes:
  remplace: primes
  somme:
    - primes . [*]
    - ancienneté
  avec:
    ancienneté:
```

> Note : Autre possibilité, remplacement de selecteurs, mais ça va devenir compliqué

### 5. Pouvoir calculer un échéancier d'emprunt

```yaml
prêt: 
  avec: 
    montant: 100000 €
    taux annuel: 2%
    durée: 10 ans
    annuité: montant  * taux annuel / (1 - (1 + taux annuel) ** -durée)

année:

année . [2021]:
  avec: 
    capital restant dû: prêt . montant
    intérêts: capital restant dû * prêt . taux annuel


année . [n]:
  avec: 
    capital restant dû: [précédent] . capital restant dû - [précédent] . capital remboursé
    intérêts: capital restant dû * prêt . taux annuel
    capital remboursé: prêt . annuité - intérêts

```

### 6. FCU - récupérer les données du département renseigné
```yaml
!selecteurs: 
  département selectionné: départements . [nom: départements]

départements: 
    valeur: "'AIN'"
    possibilité: 
        - AIN
        - ...
        - YONNE

  avec: 
    AIN:
      djuChaudMoyen: 10 kg/W/m²
      djuFroidMoyen: 20 kg/W/m²
    ...
    YONNE:
      djuChaudMoyen: 15 kg/W/m²
      djuFroidMoyen: 25 kg/W/m²

départements . [*]:
  avec:
    dju chaud moyen:
      type: number
      unité: kg/W/m²
      requis: oui # nouveau mécanisme qui lève une erreur si la règle est non définie à l'évaluation
    dju froid moyen:
      type: number
      unité: kg/W/m²
      requis: oui   

djuchaudmoyen: [département selectionné] . djuChaudMoyen

```

### Liste d'aides applicables triées par leur montant

```yaml
!selecteurs: 
  aides applicables: 
    - aides . [**]
    - condition: 
        est applicable: [valeur]
    - trier par: montant 
```
```js
engine.select(`[aides applicables]`)
```
