### DISCUSSION TITLE
[Proposal] Espace de nom indexé par des nombres (« liste »)

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#566] [Ideas]
# Proposal : Espace de nom indexé par des nombres

## Contexte

Une des fonctionnalités manquantes les plus demandées est la possibilité de définir des listes dans publicodes et d'avoir des mécanismes pour les manipuler. 

Les cas d'usage associés sont répertoriés dans le ticket #392. Cette proposition vise à y répondre.

Une fois que le cadre et les principes seront validés, nous pourrons passer à l'étape 2 :  réfléchir à l'implémentation.

## Principe

Cette proposition introduit une façon de définir des listes en publicodes.

Les listes sont des **espaces de noms indexés par des entiers naturels**, qui partagent tous une **la même forme** (même type, même sous-règles).

### Définition de liste

**Syntaxe sans indentation**

```yaml
liste d'entiers:
liste d'entiers . [0]: 5
liste d'entiers . [1]: 10
liste d'entiers . [2]: 15
```

**Syntaxe avec indentation**

```yaml
liste d'entiers:
  liste:
    - 5
    - 10
    - 15

liste d'objets:
  liste:
    - avec:
        nom: 'Alice'
        age: 25
    - avec:
        nom: 'Bob'
        age: 30
```

- Le mot-clé `liste` permet de définir des règles enfants indexées par un entier, de la même manière que l'on peut définir des règles enfants en utilisant le mot-clé `avec`.
- La règle « racine » de la liste est une règle à part entière, elle peut avoir un champs description, une valeur, etc.
- Si un élément de la liste n'a pas le même type que les autres, une erreur est levée.
- Si on essaye de réaffecter un index déjà utilisé, le moteur lève une erreur (comme pour les espaces de noms classiques).

### Accès aux éléments d'une liste

Les éléments d'une liste sont accessibles par leur index avec la syntaxe `liste . [<index>]`.

```yaml

premier élément: liste d'entiers . [0]
```

Il est également possible d'accéder à un élément par son numéro ordinal (1-indexé) : `liste . n[<n>]`.

```yaml
année:
  liste:
    - 2020
    - 2021
    - 2022

année de début: année . n[1]
```

#### Index dynamique

L'index peut être une expression publicodes calculée dynamiquement.

```yaml
numéro selectionnée: 2
entier à afficher: liste d'entiers . n[numéro selectionnée]
```

#### Accès hors plage

Un élément accédé avec une valeur hors plage est `non applicable`.

### Copier une liste

Il est possible de copier la structure d'un espace de nom liste (indexé par des entiers) dans un autre.

```yaml
liste 2:
  liste: liste 1
```

_A noter : l'implémentation n'est pas encore précisée à ce stade_

#### Copie d'objet (namespaces)

De la même manière, il est dorénavant possible de copier un objet.

```yaml
objet 1:
  avec:
    nom: 'Alice'
    age: 25

objet 2:
  avec: objet 1
```

> **TODO** Est-ce que l'on garde le mot clé `avec` pour la copie où on en trouve un autre ? 
> **TODO** Est-ce que cela fait une copie profonde ?

### Opération sur les listes

Les mécanismes existants prenant un tableau en entrée (somme, moyenne, etc.) peuvent être utilisés sur les listes.

```yaml
somme: liste d'entiers
```

##### modifications
Permet de créer une nouvelle liste à partir d'une liste existante en appliquant une suite d'opérations.

```yaml
nombre supérieur à 10 en décroissant:
  liste:
    à partir de: liste d'entiers
    modifications:
      - garder si: valeur >= 10 # filtre
      - transformer en: valeur * 2
      - trier par: valeur
```

- `à partir de` : défini la liste sur laquelle on opère
- `modifications` : une suite d'opérations à appliquer dans l'ordre de déclaration. Si une seule opération est définie, elle peut être déclarée directement sous le mot clé `modifications`

Les modifications possibles sont
- `garder si` : permet de filtrer les éléments de la liste
- `trier par` : permet de trier les éléments de la liste.
- `transformer en` : permet de transformer les éléments de la liste (map)
- `ajouter à la fin` : permet d'ajouter un ou plusieurs éléments à la fin de la liste.
- `ajouter au début` : permet d'ajouter un ou plusieurs éléments au début de la liste.
- `premiers` : permet de sélectionner les premiers éléments d'une liste.
- `derniers` : permet de sélectionner les derniers éléments d'une liste.

Pour les modifications `garder si`, `trier par` et `transformer en`, on peut utiliser les règles pré-définies `valeur`, `i` et `n` pour accéder à la valeur et à l'index de l'élément courant.

Ce mécanisme n'est utilisable que dans un **contexte de liste**. C'est-à-dire :

- Dans un mécanisme qui attend une liste en entrée (somme, moyenne, etc.)
- Dans une règle qui défini une liste via le mot-clé `liste`

##### Accès aux éléments d'une liste

On ajoute également les mécanismes `premier élément de: <liste>`, `dernier élément de: <liste>` ainsi que le mécanisme `élément de:` pour accéder à un élément d'une liste par son index ou son numéro ordinal.

### Initialisation d'une liste

Il est possible d'initialiser une liste en précisant sa taille.

```yaml
nombres:
  liste:
    taille: 10
```

#### Liste dynamique

La taille d'une liste peut être définie dynamiquement.

```yaml
enfants:
  liste:
    taille: nombre
  avec:
    nombre: Combien d'enfants avez-vous ?
    par défaut: 0
```

#### Valeur d'initialisation

Pour affecter une valeur d'initialisation aux éléments d'une liste, on utilise la notation suivante :

```yaml
nombres . []: 5
```

Si des index ne sont pas définis, mais existent dans la taille de la liste, ils prennent la valeur d'initialisation.

```yaml
nombres:
  liste:
    taille: 5

nombres . [0]: 2
nombres . [1]: 3
nombres . []: 1

test:
  produit: nombres # Vaut 2 * 3 * 1 * 1 * 1
```

- Sans valeur d'initialisation, les éléments non définis valent `non défini`.
- Il est possible d'accéder à l'index courant dans une règle d'initialisation avec la variable `i` (ou `n` pour le numéro).

### 1. Opération TVA

_Supposons une facture multilignes avec 4 items chacune comportant un prix htva et un taux de tva, comment opérer le calcul "total tva comprise" de ladite facture ?_

<details>

<summary>Voir le code 🧑‍💻</summary>

```yaml
facture . lignes:
  liste:
    - avec:
        prix HT: 13€
        TVA: 20%
    - avec:
        prix HT: 32€
        TVA: 5.5%
    - avec:
        prix HT: 10€
        TVA: 10%
    - avec:
        prix HT: 5€
        TVA: 20%

facture . total:
  somme:
    à partir de: lignes
    modifications:
      - transformer en: prix HT * (1 + TVA)
```

</details>

### 2. Définir plusieurs enfants

_Supposons que l'on souhaite définir une liste d'enfants, et calculer l'âge moyen des enfants majeurs, l'âge du plus jeune majeur, et l'aîné._

<details>

<summary>Voir le code 🧑‍💻</summary>

```yaml
enfants:
  liste:
    taille: nombre
  avec:
    nombre:
      par défaut: 0

enfants . []:
  avec:
    nom:
      type: texte
    date de naissance:
      type: date
    âge: # âge est une « méthode » qui calcule l'âge en fonction de la date de naissance
      durée:
        depuis: date de naissance
        unité: an

enfants triés par âge:
  liste:
    à partir de: enfants
    modifications: 
      - trié par: âge

ainé:
  avec: enfants triés par âge . n[1]

age moyen des enfants majeurs:
  moyenne:
    à partir de: enfants
    modifications: 
      - filtre: 'âge >= 18'
      - map: âge

age du plus jeune majeur:
  premier élément de: 
    à partir de: enfants
    modifications: 
      - filtre: 'âge >= 18'
      - trié par: âge
      - map: âge
```

</details>

### 3. Réécrire les mécanismes de liste

_On cherche ici à réécrire le mécanisme [barème](https://publi.codes/docs/mecanismes#barème) nativement._

<details>

<summary>Voir le code 🧑‍💻</summary>

```yaml
impôt sur les sociétés . tranches:
  liste:
    - avec:
        plafond: 10000€
        taux: 10%
    - titre: tranche intermédiaire
      applicable si: date > 01/2025
      avec:
        plafond: 20000€
        taux: 15%
    - avec:
        plafond: 30000€
        taux: 20%

impôt sur les sociétés:
  avec:
    assiette: 10000€

  somme:
    à partir de: tranches
    modifications:
      - garder si: 
          est applicable: valeur
      - transformer en:
          produit:
            - taux
            - le minimum de:
                - assiette
                - plafond
              abattement: [i-1] . plafond
```

</details>

### 4. Ajouter des éléments aux listes avec `remplace`

_On souhaite ajouter des éléments à une liste existante avec le mécanisme `remplace`, par exemple ajouter une prime conventionnelle._

<details>

<summary>Voir le code 🧑‍💻</summary>

```yaml
primes:
  somme: primes
  liste:
    - titre: activité
      valeur: 100€
    - titre: exceptionnelle
      valeur: 50€
  
convention collective . bâtiment . primes:
  remplace: 
    l'espace de nom: primes # Nouvelle modalitée de remplacement, à condition que les espaces de nom soient de même forme.
  somme: primes
  liste: 
    à partir de: primes
    modifications:
      - ajouter à la fin:
          titre: ancienneté
          valeur: 200€

```

</details>

### 5. Pouvoir calculer un échéancier d'emprunt

_On souhaite calculer une liste de valeurs intermédiaires à partir d'une situation initiale. Par exemple, pour un prêt, le capital restant dû, les intérêts, le capital remboursé, etc._

<details>

<summary>Voir le code 🧑‍💻</summary>

```yaml
prêt:
  avec:
    montant: 100000 €
    taux annuel: 2%
    durée: 10 ans
    annuité: montant  * taux annuel / (1 - (1 + taux annuel) ** -durée)

prêt . année:
  liste:
    taille: durée

prêt . année . n[1]:
  avec:
    capital restant dû: montant

prêt . année . []:
  avec:
    capital restant dû:
      valeur: n[n-1] . capital resta dû
      abattement: n[n-1] . capital remboursé
    intérêts:
      produit:
        - n[n-1] . capital restant dû
        - prêt . taux annuel
    capital remboursé: annuité - intérêts
```

</details>

### Pourquoi ne pas créer un type liste de premier niveau ?

```yaml
ma liste: [1, 2, 3]
```
Cette idée correspond aux standard des langages de programmation. Pourquoi ne pas l'avoir dans publicodes ? Tout simplement car cela aboutirait à avoir deux fonctionalités (et écriture) différentes pour le même cas d'usage. Ce qui est en opposition avec un principe cœur du langage : être sobre en concepts.

Prenons l'exemple de l'implémentation en publicodes une liste d'enfant, avec un type liste de premier niveau. 

Cela demande d'introduire le type liste, mais également le type objet. En effet, chaque élément de la liste a des propriétés distinctes (ici `nom` et `date de naissance` par exemple). 
```yaml
enfants: 
  - nom: Alice
    date de naissance: 11/06/2001
  - nom: Younès
    date de naissance: 05/04/2024
```

Maintenant, comment référencer un élément de cette liste depuis une autre règle ? On peut imaginer la syntaxe suivante, qui est celle de javascript et de nombreux autres langages de programmations. 
```yaml
premier enfant: enfants[0]
nom du premier enfant: premier enfant.nom
```
On remarque immédiatement la similitude avec les espaces de nom, et la confusion que cela pourrait engendrer. 

En effet, dans publicodes, les **espaces de noms** encodent directement la **structure de la donnée**. On peut voir un ensemble de règles publicodes comme un **objet JSON** dont les valeurs des propriétés sont calculées à partir d'autres. 

En ce sens, il n'y a pas besoin d'introduire de type liste de premier niveau, juste un moyen de définir des listes dans la structure des espaces de nom (comme des listes dans un fichier JSON).

**Comment by EmileRolley** [comment]
Merci pour la proposition ! 

Je trouve ça très intéressant mais selon moi ce serait plus simple et compréhensible de ne pas faire de distinction entre les listes et les autres types primitifs comme les nombre et les booléens par exemple.

D'ailleurs le terme _liste_ me parait un peut trop dev-centré, je pense que parler de _tableau_ ou d'_ensemble_ parlerait à plus de personnes (à vérifer).

Je pense qu'il y a peut-être quelque chose à jouer sur la distinction objet/règle également mais je ne sais pas trop encore par quel angle l'aborder.

---

### Définition de liste 

> Ainsi, la règle racine de la liste est une règle à part entière, elle peut avoir un champs description, une valeur, etc. Pour distinguer la référence vers la règle racine d'une référence vers la liste on utilise la syntaxe liste d'entier [].

Est-ce que ça ne serait plus simple et compréhensible qu'un règle ne puisse pas avoir à la fois une valeur est une liste. Pour moi il faudrait considérer les listes comme les autres types primitifs (nombre, date, enumération, booléean) et que l'évaluation de la règle `liste d'objet` retourne un tableau.

### Accès aux éléments d'une liste

> Il est également possible d'accéder à un élément par son numéro ordinal (1-indexé) : liste [n <n>].

Tu aurais un cas d'usage qui justifierait cette syntaxe ? En effet, j'ai peur que ça complique la compréhension et puisse causer des bugs _bête_ sans réel bénéfice. (A la limite, si on souhaite se rapprocher de notation _moins informatiques_, j'opterai plutôt pour `ma liste [N=1]` ou `ma liste [X=1]`).

### Copier une liste

Le fait de considérer les liste comme une simple valeur, permettrait de simplement écrire :

```yaml
liste 1:
  liste:
    - 5
    - 10
    - 15

liste 2:
  liste: liste 1
```

Ou même plus simplement :

```yaml
liste 1:
  valeur:
    - 5
    - 10
    - 15

liste 1 bis:
  valeur: [5, 10, 15] # syntaxe YAML

liste 2: liste 1
```

### Copie d'objet

> De la même manière, il est dorénavant possible de copier un objet.

Je ne suis pas sûr de comprendre le lien avec les listes là. Est-ce que tu introduis une distinction entre les règles avec des espace de nom _absolu_ et les objet défini avec `avec` ?

### Initialisation d'une liste

> Il est possible d'initialiser une liste en précisant sa taille.

Si la taille est définie alors il n'est pas possible d'accéder à des éléments en dehors ? Comment le vérifier dynamiquement ?

Je ne suis pas sûr que ce soit utile de pouvoir préciser la taille des listes.

### Réaffectation d'un index

> Si on essaye de réaffecter un index déjà utilisé, le moteur lève une erreur.

Pourquoi ne voudrions-nous pas pouvoir modifier les éléments d'une liste ? Avoir uniquement des tableaux en lecture seule ne résoudrait pas les problématiques que nous souhaitons adresser avec ce nouveau type non ?

### API

#### setObjectSituation

> Nouvelle méthode pour mettre à jour la situation sans avoir à spécifier les espaces de noms complets pour chaque valeur.

Pourquoi ne serait-il pas possible de faire un `engine.setSituation({ nombres: [10, 20] })` ?

> Cette méthode fonctionne également avec les objets :

J'aime bien l'idée, mais dans ce cas là j'ai le sentiment que ce serait peut-être plus compréhensible de définir les règles comme des objets et avoir un seul `setSituation`.

## Implémentation des cas d'usages

### 1. Opération TVA

Ca devrait plutôt être :

```yaml
facture . total:
  somme:
    liste: lignes[]
    map: [valeur] . prix HT * (1 + [valeur] . TVA) # map est très dev non ?
```
