### DISCUSSION TITLE
[Proposal] Une CLI pour Publicodes

### DISCUSSION THREAD

**Discussion by EmileRolley** [publicodes/publicodes#567] [Ideas]
## Contexte

> Fait suite à https://github.com/publicodes/publicodes/discussions/562#discussioncomment-10729557.

Plusieurs [modèles](https://publi.codes/bibliotheque) Publicodes commencent à être publiés sur NPM. Cela permet de pouvoir rapidement les utiliser dans un projet JS :

```typescript
import rules from "publicodes-evenements";
import Engine from "publicodes";

const engine = new Engine(rules);

engine.setSituation({
  "informations . nombre de festivaliers": 3000,
  "informations . nombre de jours": 3,
  "transport . public . accessible en transports en commun": "non",
});
engine.evaluate("resultats . bilan par festivalier");
engine.evaluate("hébergement . public");
```

Et permet même de pouvoir réutiliser une partie des règles d'un modèle dans un autre modèle Publicodes (voir la [documentation](https://publi.codes/docs/manuel/importer-des-regles)) :

```yaml
importer!:
  depuis:
    nom: "@incubateur-ademe/nosgestesclimat"
  les règles:
    - alimentation . plats . végétalien . empreinte
    - alimentation . plats . végétarien . empreinte
    - alimentation . plats . viande 1 . empreinte
    - alimentation . plats . viande 2 . empreinte

alimentation . repas . végétalien:
  formule: nombre * nosgestesclimat . alimentation . plats . végétalien . empreinte
```

## Problème

Cette approche s'étant généralisée au fil des différents projets utilisant Publicodes, il **n'y a pas actuellement de réel standard sur la publication de modèle Publicodes**. Or, cela est nécessaire si l'on souhaite pouvoir garder une interopérabilité entre les modèles et faciliter leur compréhension et réutilisation.

Il existe le template GitHub [`modele-template`](https://github.com/publicodes/model-template) permettant de pouvoir facilement implémenter un nouveau modèle Publicodes avec tout un ensemble de scripts permettant la compilation et publication de modèle ainsi que la mise en ligne de la documentation. Cependant, utiliser un template rend **compliqué la maintenance dans le temps** : si le script de build est patché ce n'est pas évident de proprement récupérer les modifs au fur et à mesure dans un projet existant.

## Solution

Cela semble donc le moment de fournir une CLI permettant de **initialiser, compiler (résoudre les imports + optmisation), tester, packager et hoster la documentation**.

### Initialiser (`publicodes init`)

Permet d'initialiser un nouveau modèle Publicodes. Elle est un wrapper autour du package manager utilisé (`npm`, `yarn`, `pnpm` ou `bun`) est permet de générer un squelette de projet Publicodes.

#### API

```bash
$ publicodes init --help
Usage: publicodes init <name> [options]

Options:
  --npm           use npm as package manager (default)
  --yarn          use yarn as package manager
  --pnpm          use pnpm as package manager
  --bun           use bun as package manager
  -y, --yes       skip prompts
  -h, --help      display help for command
```

### Compiler (`publicodes build`)

Permet de compiler un modèle Publicodes. C'est-à-dire, générer un fichier JSON contenant toutes les règles du modèle avec les imports résolus ainsi qu'un ensemble de fichier JS permettant d'utiliser le modèle ainsi que des descriptions de type.

#### API

```bash
$ publicodes build --help

Usage: publicodes build <file> [options]

Options:
  -o, --output <folder>   output folder (default: "dist")
  -O, --optimize          optimize the model
  -w, --watch             rebuild on changes
  -h, --help              display help for command
```

#### Contenu du dossier `dist`

```
dist/
├── index.js
├── index.d.ts
├── model.json
└── extensions/
    ├── ...
    └── index.js
```

### Tester (`publicodes test`)

Permet de tester un modèle Publicodes. Pour cela il est nécessaire de définir une nouvelle syntaxe pour les tests.

Pour les tests _inline_, je propose la syntaxe suivante :

```yaml
<rule_name>:
  ...
  test:
    <description du test>:
      situation:
        {<rule_name>: <expression> | <node_value>}
      valeur attendue: <expression> | <node_value>
```

Ce qui donnerait pour l'exemple de la [documentation](https://publi.codes/docs/guides/jeux-de-tests) :

```yaml
taille:
  question: Quelle est votre taille (en cm) ?
  unité: cm

poids:
  question: Quel est votre poids (en kg) ?
  unité: kg

# Convertit la taille en mètres
taille mètres:
  valeur: taille
  unité: m

# Calcul l'IMC à partir de la taille en mètres
imc:
  valeur: poids / ((taille mètres) * (taille mètres))
  unité: kg / m²
  test:
    doit renvoyer le bon IMC pour (T=170,P=80):
      situation:
        taille: 170
        poids: 80
      valeur attendue:
        valeur: 27.68166089965398
        unité: kg/m²

# Affiche le résultat
résultat:
  applicable si: imc
  texte: |
    Votre IMC est de {{ imc }}
    Interprétation: {{ résultat . interpretation }}
  test:
    doit renvoyer la bonne interprétation pour (T=150,P=90):
      situation:
        taille: 150
        poids: 90
      valeur attendue: |
        Votre IMC est de 40 kg/m²
        Interprétation: obésité morbide ou massive

# Interprétations de l'IMC
résultat . interpretation:
  variations:
    - si: imc >= 40
      alors: "'obésité morbide ou massive'"
    - si: imc >= 35
      alors: "'obésité sévère'"
    - si: imc >= 30
      alors: "'obésité modérée'"
    - si: imc >= 25
      alors: "'surpoids'"
    - si: imc >= 18.5
      alors: "'poids normal'"
    - si: imc >= 16.5
      alors: "'maigreur'"
    - sinon: "'dénutrition'"
```

#### API

```bash
$ publicodes test --help

Usage: publicodes test <file> [options]

Options:
  -h, --help  display help for command
```

### Documenter (`publicodes doc`)

Permet de visualiser la documentation du modèle avec `@publicodes/react-ui`.

#### API

```bash
$ publicodes doc --help

Usage: publicodes doc [command] [options]

Commands:
  serve [options]  serve the documentation locally (default command)
  build [options]  build the documentation for hosting

Options:
  -o, --output <folder>  output folder (default: "doc-dist")
  -h, --help  display help for command
```

### Fichier de configuration (`publicodes.config.js`)

Il sera possible de configurer la CLI via un fichier `publicodes.config.js` créé à la racine du projet lors de l'initialisation.

Voici le fichier de configuration par défaut :

```typescript
import { RawPublicodes } from "publicodes";

export default {
  source: ["src/**/*.publicodes"],
  ignore: [],
  output: "dist",
  optimize: false, // could be an object corresponding to the options of @publicodes/tools/optimization

  onResolved: (model: RawPublicodes<String>): RawPublicodes<String> => {
    // Hook called when all the publicodes files have been resolved into a
    // JSON object.
    return model;
  },
};
```

Un modèle Publicodes est rarement publié seul, il est souvent accompagné de code JS supplémentaire (ex: personas, ui, etc...). Il est donc possible de définir un dossier `extensions` dans lequel on pourra mettre tout le code JS supplémentaire qui seront accessibles depuis le paquet :

```typescript
import rules, { personas } from "mon-modele-publicodes";
```

Il suffira de définir l'aborescence suivante :

```
extensions/
└── personas/
    ├── index.js
    ├── index.d.ts
    └── personas.json
```

Afin de pouvoir opérer des vérifications à partir des règles présentes dans le modèle, ces fichiers JS supplémentaires pourront être définis dans le hook `onResolved`.

## Questions

- Les textes de la CLI doivent-ils être rédigés en français ou en anglais ?
- Quel est le moyen le plus élégant pour gérer les extensions ?

**Comment by johangirod** [comment]
De très bonnes idées ! Quelques remarques et questions supplémentaires : 

### `init`

- En plus des packages manager, on peut imaginer pouvoir partir d'un [des exemples](https://github.com/publicodes/publicodes/tree/master/examples) avec le flag `--example`. Ces derniers seront à mettre à jour pour séparer la partie applicative et les règles dans deux paquets séparés.
- Dans l'idéal, on souhaiterait pouvoir l'exécuter dans un répertoire existant pour convertir un projet. Dans ce cas, elle pourrait poser des questions supplémentaires / tenter d'inférer les paramètres à renseigner dans `publicodes.config.js`

### `test`

En l'état actuel, je ne suis pas convaincu qu'il soit nécessaire d'ajouter cette commande. 
- Chaque développeur a ses préférences en matière de framework de test (vitest, mocha, jest, bun)
- Je doute de l'intérêt de colloquer les tests et les règles métiers testées au même endroit. Je trouve que cela alourdit considérablement la lecture, et c'est une pratique qui n'existe dans aucun autre langage de programmation à ma connaissance. Si on souhaite tout de même ajouter cette fonctionnalité, les tests devraient être définis dans des fichiers séparés (`.test.publicodes`), quitte à garder le comportement de les afficher dans la doc.
- En revanche, on pourrait imaginer que la commande `init` propose une option pour générer quelques dummy test avec un framework sélectionné (vitest par exemple).

### doc

Top comme commande ! Il manque juste l'option `--port` pour `serve`

### build

Je rajouterais bien l'option `--watch`

### publicodes.config.js

Très bonne idée. 

- `onResolved` : `onCompilationEnd` ? 
- à quoi sert `ignore ?

### extensions

Je suis partagé. D'un côté, cela simplifie la publication de paquet et de modèle métier associé, de l'autre, on se retrouve avec beaucoup de choses dans un même paquet, ce qui peut être plus dur à maintenir : 

- Il faut une étape de build supplémentaire pour les fichiers JS (avec une config ts associée).
- Les montées de version doivent prendre en compte les extensions
- La documentation du paquet doit à la fois présenter les règles publicodes et les extensions

Suggestions : 
- À minima, je séparerai les extensions dans un namespace dédié (`mon-modele-publicodes/mon-extension`)
- J'ajouterai une option pour initialiser un repos avec extension dans le `init`, (mais sans l'activer par défaut).
- L'autre possibilité est d'avoir deux paquets séparés, avec un exemple de repo bien configuré pour l'expérience de dev.

## Questions
> - Les textes de la CLI doivent-ils être rédigés en français ou en anglais ?

J'aurais tendance à dire anglais, pour continuer dans l'idée que tout ce qui est utilisé exclusivement par des dev (et n'a pas attrait au métier) soit en anglais. 

### Autres idées (à réfléchir)

- Ajouter une commande `publicodes changeset` qui propose une liste de changements depuis la dernière version publiée, avec une proposition de montée de version (patch, mineur, majeur).

**Reply by EmileRolley** [reply]
### `init`

> Dans l'idéal, on souhaiterait pouvoir l'exécuter dans un répertoire existant pour convertir un projet. Dans ce cas, elle pourrait poser des questions supplémentaires / tenter d'inférer les paramètres à renseigner dans publicodes.config.js

Oui c'est l'idée, soit tu execute la commande `init my-model` et ça te créer un nouveau sous-dossier `my-model`. Ou bien tu peux également simplement créer une fichier `publicodes.config.js`.

### `test`

> En l'état actuel, je ne suis pas convaincu qu'il soit nécessaire d'ajouter cette commande.

Je suis d'accord que ce n'est pas la priorité. En revanche, à voir un moyen de faire des tests unitaire built-in et on peut également imaginer rajouter du fuzzing par la suite, peut grandement encourager l'utilisation des tests. D'autant plus si ils peuvent être écrit inline. Et ce sera
de toute façon optionnel et reste orthogonale avec le fait de mettre en place un système de test custom plus complet.

> Je doute de l'intérêt de colloquer les tests et les règles métiers testées au même endroit. Je trouve que cela alourdit considérablement la lecture, et c'est une pratique qui n'existe dans aucun autre langage de programmation à ma connaissance. Si on souhaite tout de même ajouter cette fonctionnalité, les tests devraient être définis dans des fichiers séparés (.test.publicodes), quitte à garder le comportement de les afficher dans la doc.

Le fait d'avoir les tests dans le même fichier que le code testé est de plus en plus courant. C'est le cas pour [Rust](https://doc.rust-lang.org/book/ch11-01-writing-tests.html) ou [Zig](https://ziglang.org/documentation/master/#Zig-Test) par exemple. Cependant, au lieu d'ajouter un nouveau mécanisme, nous pourrions plutôt créer une nouvelle règle suffixée de ` . test` et ainsi permettre de ne pas nécessairement avoir à l'écrire eu même endroit et se retrouver avec des règles immenses :

```yaml
imc:
  valeur: poids / ((taille mètres) * (taille mètres))
  unité: kg / m²

imc . tests:
  - doit renvoyer le bon IMC pour (T=170,P=80):
      situation:
        taille: 170
        poids: 80
      valeur attendue:
        valeur: 27.68166089965398
        unité: kg/m²
```

### publicodes.config.js

> à quoi sert `ignore ?

Cela permet de pouvoir ignorer des fichiers publicodes que l'on ne souhaite pas compiler, c'est les même options que pour [`getModelFromSource`](https://publicodes.github.io/tools/functions/compilation.getModelFromSource.html)

### Extensions

> À minima, je séparerai les extensions dans un namespace dédié (mon-modele-publicodes/mon-extension)

Oui ça peut être une bonne idée :+1: 

> L'autre possibilité est d'avoir deux paquets séparés, avec un exemple de repo bien configuré pour l'expérience de dev.

Pour moi ce n'est pas forcément une bonne idée parce qu'on se retrouverait avec les problèmes que pour le template github.

De manière générale, j'ai l'intuition de vouloir lier les extensions (ce n'est peut-être pas la bonne terminologie d'ailleurs) aux règles Publicodes pour pouvoir tirer profits du typage et savoir qu'elles sont les règles disponibles dans le modèle ainsi que leurs types à terme, pour avoir le build qui casse dès que les deux ne sont pas iso.

Après une seconde option effectivement serait de considérer que tout ce qui ne concerne pas la compilation des règles Publicodes est libre d'être géré librement par les auteur.ice du paquet. Mais je me dis qu'il y a peut-être moyen et c'est peut-être l'occasion d'homogénéiser le tout.

## Questions

> > Les textes de la CLI doivent-ils être rédigés en français ou en anglais ?
>
> J'aurais tendance à dire anglais, pour continuer dans l'idée que tout ce qui est utilisé exclusivement par des dev (et n'a pas attrait au métier) soit en anglais.

Dans ce cas là on se retrouverait avec les messages d'erreur de l'engine en français au milieu des logs du la CLI en anglais ?

## Autres idées (à réfléchir)

> Ajouter une commande `publicodes changeset` qui propose une liste de changements depuis la dernière version publiée, avec une proposition de montée de version (patch, mineur, majeur).

Yes, carrément on peut imaginer pleins de petites commandes supplémentaires :+1: 

On pourra même rajouter la gestion des paquets et des dépendances pour les imports également.
