### DISCUSSION TITLE
[Proposal] Faire évoluer `une possibilité` vers un type `enum`

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#571] [Ideas]
## Introduction

L'objectif de cette proposition est d'améliorer le mécansime existant `une possibilité`. Les principaux objectifs sont :

- sortir `une possibilité` de la liste des mécanisme pour en faire une définition de type ;
- avoir une vérification statique des valeurs possibles ;
- proposer une interface javascript pour mieux manipuler ce type de règle # ;

Note : cette proposition est dans la continuité de #566 et de #572

## Types `choix unique` (ancien `une possibilité`)

```yaml
contrat:
  type: choix unique
  par défaut: +CDI # Nouveau constructeur de type pour les options, au lieu des double quotes
  options:
    CDI:
    CDD:
    Stage:
```

**À noter** :

- `options` permet de définir des sous-règles qui seront les options du choix

  1. elles sont automatiquement type booléen
  2. elles sont en lecture seule (pas possible de les modifier via `setSituation` ou le mécanisme `contexte`)
  3. elles valent `oui` si l'option est choisie, `non` sinon (ajout automatique d'une valeur par le compilateur `valeur: ^ = +<option>`)

- on peut définir d'autres sous-règles avec le mot clé `avec`, elles ne seront pas considérées comme des options
- un nouveau constructeur de type `+<option>` permet de définir la valeur l'option choisie. Les valeurs possibles sont les clés de `options`

- une vérification statique est effectuée à la compilation

  1. Pour s'assurer de la validité des égalités.

  ```yaml
  verification statique:
    valeur: contrat = +CSD # KO
  ```

  2. Y compris entre deux choix :

  ```yaml
  choix 1:
    options:
      a:
      b:
  choix 2:
    options:
      b:
      c:
  verification statique:
    valeur: choix 1 = choix 2 # OK car les deux types ont au moins une option en commun
  ```

  3. On peut imaginer un nouveau mécanisme [`correspondance`](https://github.com/betagouv/mon-entreprise/pull/824#issuecomment-571066288) qui associe des valeurs à des options, en levant une erreur si une option n'est pas définie.

- on peut copier les options d'une règle à une autre, comme pour `avec` (cf la [proposition des listes](https://github.com/publicodes/publicodes/discussions/566))
  ```yaml
  contrat 2:
    type: choix unique
    options: contrat
  ```

**Questions** :

- Le nom du type `choix unique` est-il clair ? Autres options : `selection`, `choix unique`, `une possibilité` ou `enum`
- Pourquoi avoir un constructeur de type avec une syntaxe spécifique pour les options  `a: +option 1` ?
  - **Avantages** : permet de distinguer les options des chaînes de caractères et éviter le côté magique de la conversion (qui peut être source d'erreur si on compare des références). On gagne en cohérence et en prédictibilité. Permet d'affecter des options directement à une variable, sans passer par une règle. Pas de double guillemets.
  - **Inconvénients** : une nouvelle syntaxe introduite, plus de complexité. Pas rétrocompatible.
- À faire : Possibilités de grouper les options (cf mon-entreprise) ?

### API

cf #572

```ts
interface Choice<Options> extends Rule {
	type: 'choix unique'

	options: Record<Options, ReadOnlyRule>
	applicableOptions(): Record<Options, ReadOnlyRule>

	value(): Options
	set(option: Options): void
}
```

## Types choix multiple (in progress)

```yaml
repas:
  type: choix multiple
  par défaut: +petit déjeuner +diner
  options:
    petit-déjeuner:
    déjeuner:
    diner:
```

```ts
interface MultipleChoice<Options> extends Rule {
	type: 'choix multiple'

	options: Record<Options, ReadOnlyRule>
	applicableOptions(): Record<Options, ReadOnlyRule>

	value(): Array<Options>
	set(option: Array<Options>): void

	setOption(option: Options, value: boolean): void
}
```

**À savoir**

- La valeur de `a = +<option>` est vrai si l'option est selectionnée, y compris si d'autres options sont selectionnées également.
- On peut comparer les valeurs de choix multiple avec un litéral : `a = +petit déjeuner +diner`
- On peut comparer des valeurs d'une règle `choix multiple` avec une valeur d'une règle `selection` si elles ont au moins une option en commun.
- Il est possible d'ajouter des options à une valeur précédente

  ```yaml
  suppléments:
    type: choix multiple
    options:
      végé:
      petits oignons:
      fromage:

  cout: # ...
  cout version végé:
    valeur: cout
    contexte:
      suppléments: suppléments +végé
  cout version viande:
    valeur: cout
    contexte:
      suppléments: suppléments -végé
  ```

- Les règles « options » sont en lecture et écriture
- Les règles « options » sont de type booléen
- La valeur suivante est automatiquement ajoutée aux règles « options » : `valeur: ^ = +<option>`, ce qui permet de calculer si l'option est selectionnée ou non

**Comment by EmileRolley** [comment]
## [WIP] Itération sur la proposition

Suite aux discussions avec @johangirod et @stacyharper, il semblerait que la première proposition de Johan soit obsolète. En effet, il semblerait que le réel besoin pour le langage est l'introduction d'un type énuméré. C'est-à-dire, **contraindre les valeurs possibles d'une règle à un ensemble de constantes donné**.

Le mécanisme actuel [`une possibilité`](https://publi.codes/docs/manuel/une-possibilite) qui accepte des références pour permettre de contraindre dynamiquement l'applicabilité des valeurs énumérées, me parait être un besoin d'UI pure : permettre de restreindre la liste d'options à afficher en fonction de la situation courante.

Je propose donc dans un premier temps d'implémenter une première version d'un type énumération (ou d'un type somme, voir les propositions de spécifications et d'implémentations) permettant de vérifier statiquement l'exhaustivité d'une comparaison d'une règle de type énuméré dans une variation, ou bien avec l'introduction d'un nouveau mécanisme de filtrage par motif. La problématique de pouvoir récupérer dynamiquement les valeurs possibles d'une énumération en fonction d'un contexte pour faciliter la création de simulateur, pourra être implémentée dans un second temps.

### Option 1 : type énuméré

Une première approche consisterait à implémenter un type énuméré _classique_ permettant de définir un ensemble de constantes que la règles pourrait accepter comme valeur.

#### Constantes

Pour la syntaxe des constantes, je propose de rester sur l'utilisation de simple apostrophes pour les chaines de caractères afin de rester cohérent avec la quasi majorité des langage de programmations et faciliter la migration des bases de code existantes : les comparaisons dans les expressions (ex: `règle a = 'val 1'`) resteront valides.

#### Syntaxe

Nous pourrions réutiliser l'ancien mécanisme `une possibilité`, ou bien introduire un nouveau mécanisme `énumération`, `énum` ou autre :

```yaml
règle a:
  une possibilité:
    - 'const 1'
    - 'const 2'

# contraindre l'utilisation d'une possibilité dans le mécanisme `type`
règle a':
  type:
    une possibilité:
  	  - 'const 1'
      - 'const 2'
      
règle a'':
  type:
    énumération:
      - 'const 1'
      - 'const 2'
```

#### Sémantique

Le type de toutes les règles l'exemple précédent serait donc le même : `{ 'const 1', 'const 2' }`.

#### Étendre le système de type actuelle

L'introduction du type énuméré nécessite d'étendre la définition de type avec :

1. La possibilité de référencer le type d'une autre règle :

```yaml
règle a: 
  type: # définition d'un nouveau type 'règle a' pouvant être réutilisé
    énumération:
      - 'const 1'
      - 'const 2

règle b:
  type: règle a # fait référence au type 'règle a' et non pas à sa valeur
```

> Dans cette example le type de la règle `règle b` est `règle a` qui vaut `{ 'const 1', 'const 2' }`. 

2. La possibilité de faire l'union (resp. l'intersection) de deux types :

``` yaml
règle a:
  type:
    énumération:
      - 'const 1'
      - 'const 2'
      
règle b:
  type:
    énumération:
      - 'const 2'
      - 'const 3'
      
règle c: # union
  type: règle a | règle b
 
règle d: # intersection
  type: règle a & règle b
```

Le type de `règle c` est donc `{ 'const 1', 'const 2', 'const 3' }` et de `règle d` est `{ 'const 2' }`.

### Option 2 : type somme _simple_

L'introduction de nouveau opérateur de type, pose la question de savoir si on ne souhaiterait pas homogénéiser le tout en considérant que le type énuméré n'est qu'un cas particulier d'un type somme possédant uniquement des constantes ou termes atomiques (`nombre`, `texte` et `booléen`) comme constructeurs.

C'est-à-dire que le type de `règle a` pourrait se définir simplement :

```yaml
règle a:
  type:
    union: # resp. intersection
      - 'const 1'
      - 'const 2'
```

Et `type(règle a) = { { 'const 1' }, { 'const 2' } }`.

Cela permettrait par exemple d'avoir une règle de type `'const 1'` :

```yaml
const 1:
  type: 'const 1'
  valeur: 'const 1'
```

Et donc de pouvoir retomber sur la possibilité d'avoir un calcul au runtime des termes applicables d'un type somme :

```yaml
règle a:
  type:
    union:
      - const 1
      - const 2
  avec:
    const 1:
      type: 'const 1'
      applicable si: # ...
      valeur: 'const 1'
    
    const 2:
      type: 'const 2'
      applicable si: # ...
      valeur: 'const 2'
```

## À trancher 

1. Sur quelle option souhaitons-nous partir ?
2. Quelle syntaxe adoptée ?

**Comment by stacyharper** [comment]
Ce qui me pose problème avec cette proposition c'est qu'elle ne traite que des noms. Un énum est une association entre des noms, et des constantes. Publicodes supporte plusieurs types génériques, qui me semble-t-il doivent tous pouvoir être utilisés en tant que constante d'énums. Et je pense qu'ajouter ces constantes en valeurs tranche pas mal de question.

En partant de ta proposition, `une possibilité` est un "chainable mecanism" pour mapper tout type de valeurs sur des noms. Il permet également de restreindre les valeurs identifiables, en retournant `non définie` (ou `non applicable`) lorsque aucun nom n'est associé à cette valeur. Le compilateur vérifie que les constantes ainsi que la valeur qui est mappé sont toutes du même type. Il assure aussi que chaque constante n'est associé qu'une seule fois.

Ca donne quelque chose comme ca:

```yaml
# avec un nombre

input a:
  type: nombre

règle a:
  valeur: input a # donne 'const 1' ou 'const 2' ou 'const 3' ou non définie
  une possibilité:
    const 1: 1
    const 2: 2
    const 3: 3

example a:
  variations:
    - si: règle a = 'const 1'
      alors: "ce sera le const 1"
    - si: règle a = 'const 2'
      alors: "ce sera le const 2"
    - si: règle a = 'const 3'
      alors: "ce sera le const 3"
    - sinon: "il n'est pas définie?"


# avec un texte

input b:
  type: texte

règle b:
  type: texte
  valeur: input b # donne 'const a' ou 'const b' ou 'const c' ou non définie
  une possibilité:
    const a: ma constante a
    const b: une seconde constante
    const c: la reponse c

example b:
  valeur: une valeur b
  applicable si: règle b
```

~~La syntaxe `une possibilité` me pose encore plusieurs questions. Elle implique un type emum, et donc prédate son mécanisme `type`. Faut-il associer les deux?~~ Au final non, tout comme `somme` impose un type nombre, `une possibilité` impose un type enum.

**Reply by stacyharper** [reply]
> permettant de vérifier statiquement l'exhaustivité d'une comparaison d'une règle de type énuméré dans une variation, ou bien avec l'introduction d'un nouveau mécanisme de filtrage par motif

Essayer de vérifier l'exhaustivité d'une variations ca ne me semble pas raisonnable du tout, donc on se rabattrais sur la deuxième approche, un mapping. Et il me semble que c'est exactement ce que fais le `une possibilité` dans ma proposition.

**Reply by stacyharper** [reply]
Pour ce qui est de pouvoir étendre un enum, faire des unions et intersections: J'ai quand même l'impression que ca recoupe avec le même besoin du `contexte`. A mon avis il faut qu'on trouve une solution pour adresser les deux cas. 

Pour relier ca a ton exemple: 

```yaml
règle a: 
  type: # définition d'un nouveau type 'règle a' pouvant être réutilisé
    énumération:
      - 'const 1'
      - 'const 2

règle b:
  type: règle a # fait référence au type 'règle a' et non pas à sa valeur
```

Je verrais encore plus générique, comme ca c'est utilisable avec `contexte`, ou tout autre mécanisme:

```yaml
règle a: 
  type: # définition d'un nouveau type 'règle a' pouvant être réutilisé
    énumération:
      - 'const 1'
      - 'const 2

règle b:
  prolonge: règle a
```

**Reply by stacyharper** [reply]
Un autre point qui me vient c'est qu'en l'état on peux supporter les choix multiples, via les operateurs bitwise:

```yaml
input a:
  type: nombre

règle a:
  valeur: input a
  une possibilité:
    const 1: 1 << 0
    const 2: 1 << 1
    const 3: 3 << 2

example a:
  variations:
    - si: règle a & 'const 1' && ~règle a & 'const 2'
      alors: "const 1 mais pas const 2"
    - si: règle a & ('const 1' | 'const 2')
      alors: "const 1 et/ou const 2"
```

**Reply by stacyharper** [reply]
Une question qui me reste c'est comment rattacher `'const 1'` à la définition de l'énum dans la rêgle en question. On cherche ici à faire référence a un attribut d'une règle, et on a pas de syntaxe pour cela. Ca me fais me dire qu'on devrais plutôt externaliser la définition des constantes:


```yaml
input a:
  type: nombre

const 1: 1
const 2: 2
const 3: 3

règle a:
  valeur: input a # donne 'const 1' ou 'const 2' ou 'const 3' ou non définie
  une possibilité:
    - const 1
    - const 2
    - const 3

example a:
  variations:
    - si: règle a = const 1
      alors: "ce sera le const 1"
    - si: règle a = const 2
      alors: "ce sera le const 2"
    - si: règle a = const 3
      alors: "ce sera le const 3"
    - sinon: "il n'est pas définie?"
```

Ca nous permet également de désactiver des enums qui ne sont pas applicables.

C'est encore plus élégant sous cette forme:

```yaml
input a:
  type: nombre

règle a:
  valeur: input a # donne 'const 1' ou 'const 2' ou 'const 3' ou non définie
  une possibilité:
    - const 1
    - const 2
    - const 3
  avec:
    const 1: 1
    const 2: 2
    const 3: 3

example a:
  variations:
    - si: règle a = règle a . const 1
      alors: "ce sera le const 1"
    - si: règle a = règle a . const 2
      alors: "ce sera le const 2"
    - si: règle a = règle a . const 3
      alors: "ce sera le const 3"
    - sinon: "il n'est pas définie?"
 ```

**Reply by EmileRolley** [reply]
> Ce qui me pose problème avec cette proposition c'est qu'elle ne traite que des noms.

Je ne suis pas sûr de comprendre à quoi tu fais référence en parlant de _noms_.

J'ai l'impression que mes exemples n'étaient pas assez exhaustifs. Dans mes exemples les chaines de caractères entre `'` sont bien des constantes et donc des valeurs manipulables, mais on peut bien évidement avoir d'autres types de valeurs (même si l'utilité réelle peut être discutée sans type algébrique) :

```yaml
type de motorisation:
  type:
    énumération:
      - 'thermique'
      - 'électrique'
      - 'hybride non rechargeable'
      - 'hybride rechargeable'

nombre de passagers:
  type:
    énumération:
      - 1 personne
      - 2 personne
      - 3 personne
      - 4 personne     
```

> Pour ce qui est de pouvoir étendre un enum, faire des unions et intersections: J'ai quand même l'impression que ca recoupe avec le même besoin du contexte.

C'est deux cas différents pour moi, l'un est des opérations sur des types et l'autre sur des valeurs. La syntaxe pourra être proche, mais on ne parle pas de la même chose.

Le seul point à généraliser selon moi est de pouvoir faire référence à la valeur du `contexte` d'une autre règle :

```yaml
petite voiture électrique:
  contexte:
    voiture . gabarit: 'petite'
    voiture . motorisation: 'électrique'
    
voiture électrique . empreinte:
  valeur: voiture . empreinte
  contexte: petite voiture électrique
```

Se pose néanmoins la question des contextes imbriqués.

> Un autre point qui me vient c'est qu'en l'état on peux supporter les choix multiples, via les operateurs bitwise:

Je ne l'ai pas précisé dans ma proposition, mais je ne pense pas qu'ajouter les _choix multiples_ soient une bonne idée. Là encore, c'est une notion purement d'UI de formulaire. D'un point de vue langage de programmation, ça reviendrait plutôt à ajouter la notion de collection/liste/tableaux.

**Reply by EmileRolley** [reply]
> C'est encore plus élégant sous cette forme:

C'est exactement le point de ma deuxième proposition :)

En remplaçant les constantes en chaines de caractères en nombre on trouve bien la même chose :

```yaml
règle a:
  type:
    union:
      - const 1
      - const 2
  avec:
    const 1:
      type: 1
      applicable si: # ...
      valeur: 1
    
    const 2:
      type: 2 # pourrait être contraint automatiquement si la règle est référencée dans un type union pour empêcher les remplaces.
      applicable si: # ...
      valeur: 2
```

Avec le type somme, on peut donc également introduire les types `non définie` et `non applicable` :

```yaml
règle a:
  type: 
    union:
      - nombre
      - non définie
      
règle b:
  type: 
    union:
      - nombre
      - non applicable
  applicable si: # ...
  valeur: 10
```

(Reste à déterminer si on souhaite réserver les mots clés des types atomiques pour éviter les clashs avec les références ou si on souhaite introduire une nouvelle syntaxe avec un préfixe particulier : `:nombre`, `:non définie`.)

**Reply by EmileRolley** [reply]
Pour le type `non définie` ça pourrait être simplement la combinaison d'un type atomique préfixé par `?` : `nombre | non définie` deviendrait `?nombre` et `!nombre` pour non applicable ?

**Reply by stacyharper** [reply]
Ah tant mieux si on converge dans une direction commune. J'ai par contre l'impression que tu cherches a définir des types, alors que moi c'est finalement juste un masque pour vérifier la valeur sur un ensemble de constante. Je comprends pas ce que signifie `type: 1` et `type: 2` dans ton exemple. Et je comprends pas pourquoi tu définie `union:` dans `type:`.

Par contre sur le sujet de la ré-utilisabilité on tombes pas d'accords. Je pense qu'utiliser la valeur comme une reference vers une autre règle est une très mauvaise idée. Ca rendrais le parsing, la résolution, et le report d'erreur très compliqué, et ca causerais des clash entre valeurs et noms de rêgles. Tu penses quoi de ma proposition `prolonge:`?

**Reply by stacyharper** [reply]
Pour ajouter un peu de contexte, j'essaie de m'inspirer de Golang sur le sujet. En go il n'y a pas de type enum. Ce qui est recommandé c'est de nommer des constantes pour pouvoir identifier des valeurs: https://gobyexample.com/enums

Ici `StateIdle`, `StateConnected`, `StateError`, et `StateRetrying` sont des noms apposé sur les constantes respectivement `0`, `1`, `2`, et `3`. Chez nous ca donnerais

```yaml
StateIdle: 0
StateConnected: 1
StateError: 2
StateRetrying: 3

ServerState:
  type: nombre
  valeur: input
  une possiblité:
    - StateIdle
    - StateConnected
    - StateError
    - StateRetrying
```

En poussant un peu plus loin on pourrais utiliser le même mécanisme pour mapper d'autres valeurs:

```yaml
ServerName:
  type: text
  valeur: input
  une possiblité:
    StateIdle: idle
    StateConnected: connected
    StateError: error
    StateRetrying: retrying
```

**Reply by EmileRolley** [reply]
> c'est de nommer des constantes pour pouvoir identifier des valeurs:

Oui c'est bien ce que je propose dans l'option 2, mais du coup pas besoin d'avoir un mécanisme spécifique pour les énumérations vu qu'il n'y en a plus.

**Reply by EmileRolley** [reply]
> J'ai par contre l'impression que tu cherches a définir des types

Oui, l'idée est de pouvoir exprimer ces contraintes de valeurs via le système de type. Pouvoir réduire le type nombre qui contient l'ensemble des nombres réels par un ensemble plus petit `{1, 2}`.

> Je comprends pas ce que signifie type: 1 et type: 2 dans ton exemple.

`type: 1` définie le type de l'ensemble composé uniquement du nombre 1.

>  Et je comprends pas pourquoi tu définie union: dans type:.

Car c'est un bien un nouveau type que l'ont défini, qui est l'union de plusieurs types.

C'est la même chose que le type union de TS : https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html.

Enfaite, c'est simplement intégrer dans le système de type ce qui est déjà utilisé pour générer les types des règles avec `une possibilité` en TS :

<img width="471" height="363" alt="image" src="https://github.com/user-attachments/assets/aede67be-e841-49d2-9179-780be2f44cc4" />

**Reply by EmileRolley** [reply]
> Ici StateIdle, StateConnected, StateError, et StateRetrying sont des noms apposé sur les constantes respectivement 0, 1, 2, et 3. Chez nous ca donnerais

Ce que je propose avec l'option 2, est d'aller plus loin que simplement restreindre les valeurs, en l'encodant dans le système de type et d'avoir le type de `ServerState` égal à `{ 0, 1, 2, 3 }` qui est beaucoup plus précis que le type `nombre`.

**Reply by stacyharper** [reply]
Admettons qu'on définisse des types ~~d'une seule valeur~~ sans valeur. Ensuite effectivement on crée une forme de `type:` pour définir des unions. Et qu'ensuite on s'en sorte avec l'overhaul complet du type checking. Apres pour pouvoir utiliser ces unions il va nous falloir au minima un `match:` pour pouvoir l'utiliser.

J'ai quand même l'impression que c'est énormément de changement pour n'obtenir qu'un `match` qui me semble ISO en terme de fonctionnalité à ce que je propose avec `une possiblité` en tant que map. ~~Et surtout, en dehors de ce cadre "une possibilité", est-ce qu'avoir des unions ca nous est bien utiles?~~ le plus j'y réfléchis, le plus je me dis que pour les formulaires, ce sera extrêmement utile

edit: je l'ai pas mentionné, mais ca implique aussi au passage de supporter les alias de types

**Reply by stacyharper** [reply]
Ca pourrais donner ca:

```yaml
# Alias de type

foo:
  type: vide
bar:
  type: vide
toot:
  type: foo | bar

exemple:
  type: nombre
  valeur: toot
  correspondance: # doit être exhaustif
    foo: 10
    bar: 35

exemple suite:
  valeur: exemple + 5
```

Le type checking doit s'assurer de tous les types:

```yaml
# Alias de type

foo:
  type: vide
bar:
  type: vide
toot:
  type: foo | bar

exemple:
  type: nombre | texte
  valeur: toot
  correspondance: # doit être exhaustif
    foo: 10
    bar: "foo"

exemple suite:
  valeur: exemple + 5 # erreur de compilation, mauvais type
```

Cas d'utilisation pour un formulaire en ligne:

```yaml
# Sous-partie d'un formulaire en ligne

accepte les CGU:
  type: vide
  _label: "j'accepte les CGU"
refuse les CGU:
  type: texte
  _label: "je refuse les CGU pour ces raisons:"
à accepté les CGU:
  correspondance: # (accepte les CGU | refuse les CGU) -> booléen
    accepte les CGU: oui
    refuse les CGU: non
  _label: "Acceptez vous les CGU, et sinon pourquoi:"
un branche necessitant les CGU:
  applicable si: à accepté les CGU
```

edit: le seul truc qui manque c'est de pouvoir effectivement mapper la valeur... je reflechis encore à comment ca pourrais prendre forme de maniere élégante. La forme verbeuse donnerais:

```yaml
foo:
  type: vide
bar:
  type: texte
toot:
  type: foo | bar

exemple:
  type: nombre | texte
  valeur: toot
  correspondance: # doit être exhaustif
    foo: 10
    bar:
      avec: this
      donne: "prexix" . this

exemple suite:
  valeur: exemple + 5 # erreur de compilation, mauvais type
```

**Reply by EmileRolley** [reply]
> Admettons qu'on définisse des types d'une seule valeur sans valeur.

Ma proposition est bien de garder des valeurs, il n'y a pas de type vide, mais des types de constantes :

```yaml
foo:
  type: 'foo' # pourra être inféré automatiquement
  valeur: 'foo' # n'est pas obligé de correspondre au nom de la règle
  
bar: 'bar'
  
toot:
  type: 'foo' | 'bar'

toot 2: # même type que toot (égalité structurelle)
  type: foo | bar

exemple:
  type: nombre
  correspondance:
    de: toot
    avec:
      'foo': 10
      'bar': 35

exemple suite:
  valeur: exemple + 5
```

> Apres pour pouvoir utiliser ces unions il va nous falloir au minima un match: pour pouvoir l'utiliser.

Pas nécessairement, on pourra toujours comparer les valeurs dans une variation classique comme c'est le cas actuellement ou avec un type énuméré/map :

```yaml

exemple:
  type: nombre
  valeur:
    variations:
      - si: toot = 'foo'
      	alors: 10
      - si: toot = 'bar'
      	alors: 35
```

**Reply by stacyharper** [reply]
Ah okay, ca c'est des symbols en [ruby](https://docs.ruby-lang.org/en/master/syntax/literals_rdoc.html#symbol-literals). Pour moi c'est encore un nouveau type primitif, mais ca n'invalide pas mon exemple.

```yaml
foo:
  type: symbole
  valeur: 'foo'

bar: 'bar' # type implicite symbole
```

> Pas nécessairement, on pourra toujours comparer les valeurs dans une variation classique comme c'est le cas actuellement ou avec un type énuméré/map :

Ici si `toot` est de type `symbole` alors okay. Mais on est bien d'accords que ca ca pète a la compilation?

```yaml
foo:
  type: symbole
  valeur: 'foo'

bar: 'bar'

toot:
  type: symbole | texte

exemple:
  valeur: toot = 'foo'
  # compilation error: can't compare types 'toot' and 'symbol'
  # dealiased to '(symbole | texte)' with 'symbole'
```

Et c'est la que `correspondance` entre en jeu:

```yaml
foo:
  type: symbole
  valeur: 'foo'

bar: 'bar'

toot:
  type: symbole | texte

exemple:
  type: nombre
  valeur:
    correspondance:
      symbole:
        avec: this # de type "symbole"
        valeur:
          variations:
          - si: this = 'foo'
            alors: 10
          - si: this = 'bar'
            alors: 35
      texte: 0
```

**Reply by EmileRolley** [reply]
Non non, c'est bien le type `'foo'` dont l'ensemble des valeurs possibles est `{ 'foo' }`.

**Reply by EmileRolley** [reply]
Ce sont les types littéraux de TS : https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types

**Reply by stacyharper** [reply]
> Non non, c'est bien le type 'foo' dont l'ensemble des valeurs possibles est { 'foo' }.

Je propose d'avancer, on parles vraiment de la même chose:

# Typescript

```typescript
function printText(s: string, alignment: "left" | "right" | "center") {
  ...
}
```

# Hare

```hare
type left = void;
type right = void;
type center = void;
type kind = (left | right | center);

fn print_text(s: str, k: kind) str = {
  ...
};
```

# Ruby

```ruby
def print_text(s:, kind:)
  case kind
  when :left
    ...
  when :right
    ...
  when :center
    ...
  end
end
```

**Comment by johangirod** [comment]
Merci beaucoup pour la discussion ! Je vais donner directement mon point de vue : je pense que l'option 1 que tu as proposée Émile répond à 1000% au cas d'usage. Par conséquent, je ne suis pas favorable a partir sur une solution plus puissante (type algébraïques / type somme) dans l'immédiat. 

Voici la proposition 1 remaniée à ma sauce. 


## 1. On peut définir un type enuméré via `type: une possibilité`. 

100% aligné avec ta proposition Émile. Je propose de garder "une possibilité" pour des raisons de familiarité avec la v1. Juste on le déplace sous "type" car c'est un type.

```yaml
ServerState:
  type: 
    une possiblité:
    - 'StateIdle'
    - 'StateConnected'
    - 'StateError'
    - 'StateRetrying'
```

## 2. On peut utiliser un type enum comme référence à une règle **directement enfant**

Cela permet de faire du pattern matching de manière rapide. Au lieu de : 

```yaml
ServerName:
  variations: 
    - si: ServerState = 'StateIdle'
      alors: 'idle'
    - si: ServerState = 'StateConnected'
      alors: 'connected'
    
```



```yaml
ServerName:
  valeur: ServerName . [ServerState] # Syntaxe à reflechir
  avec:
    StateIdle: 'idle'
    StateConnected: 'connected'
    StateError: 'error'
    StateRetrying: 'retrying'
```



Le nom des règles et leur type étant statiquement défini, cette syntaxe ne pose pas de problème a priori. Tout au plus elle nécessitera une passe supplémentaire lors de l'analyse de type (à voir). 

---

## Exemples développés : 


### Avec inférence de type
```yaml
type de maison: # type enum inféré
  variations: 
    - si: surface > 500 m²
      alors: 'chateau'
    - si: surface > 250 m²
      alors: 'grande'
    - si: surface > 100 m²
      alors: 'moyenne'
    - sinon: 'petite'
```


### Pattern matching exhaustif : valeur manquante
```yaml
devis entretien: # type nombre €
  valeur: [type de maison]     # Erreur ! il manque grande
  avec: 
    chateau: 10000 €
    moyenne: 1000 €
    petite: 500 €
```
### Pattern matching exhaustif : valeur en trop

Gratuit si on ajoute des avertissements sur le code mort: 

```yaml
devis entretien: # type nombre €
  valeur: [type de maison]     
  avec: 
    chateau: 10000 €
    grande: 5000€
    moyenne: 1000 €
    petite: 500 €
    minuscule: 50€ # Warning, jamais utilisé !
```

### Pattern matching cas par défaut

- Si  "!" alors la valeur est non applicable si elle n'est pas défini par les enfants
    ```yaml
        devis entretien:
        valeur: [type de maison]!     # si 'grande' alors valeur = non applicable
        avec: 
            chateau: 10000 €
            moyenne: 1000 €
            petite: 500 €
    ```
- Si "?", alors une valeur absente est non définie, on peut donc lui affecter une valeur par défaut
    ```yaml
        devis entretien: # type nombre €
        valeur: [type de maison]?     # si 'grande' alors valeur = non défini
        par défaut: 500 €
        avec: 
            chateau: 10000 €
            moyenne: 1000 €
            petite: 500 €
    ```

### Extension de type
On peut garder l'idée de `prolonge`

```yaml
type de maison: # type enum inféré
  variations: 
    - si: surface > 500 m²
      alors: 'chateau'
    - si: surface > 250 m²
      alors: 'grande'
    - si: surface > 100 m²
      alors: 'moyenne'
    - sinon: 'petite'

type de maison étendu: 
  une possibilité: 
    - prolonge: type de maison
    - 'yourte'
    - 'tinyhouse'
    - 'appartement'
    
```

### Utilisation comme dict

```yaml
region: 
  type: une possibilité

region . ain: 
  avec: 
    nom: "Ain"
    chef-lieu: "Bourgoin Jailleu"
    population: 10000 personnes
    superficie: 4000m²

region . allier: 
   avec: 
    nom: "Allier"
    chef-lieu: "???"
    population: 100000 personnes
    superficie: 4000 km²
    
densité région: 
  valeur: [region] . population / [region] . superficie

### Raccourcis (enum + match)

```yaml
nombre de joueurs:
  type: 'enum'
  une possibilité: 
    'un joueur': 1 joueur
    'deux joueurs': 2 joueur
    'trois joueurs': 3 joueur
    'quatre joueus': 4 joueur   


nombre de points à atteindre : [nombre de joueurs] / 4
```

---

J'ai l'impression que cette solution est simple, puissante, et couvre tout les cas d'usage. Avantage : proche de la v1. 

Ma proposition d'utiliser l'espace de nom pour le pattern matching est à discuter. On peut aussi utiliser un mécanisme dédié. Mais j'ai l'impression qu'on aura du mal à couvrir le cas « Utilisation comme dict » qui est très puissant selon moi. 

Ce dont je suis plutôt convaincu, c'est qu'on ne veut pas gérer les types algébraïques dès à présent dans publicodes.  Hors c'est ce que l'on fait si on commence avec : number | boolean.

- cela implique du pattern matching sur le type
- cela laisse la possibilité d'avoir plusieurs type dans les variations
- cela demande un système de type beaucoup plus lourd, et puissant, mais avec aussi potentiellement plus de cas indeterminé

Par ailleurs, Il faut faire attention à ne pas aller vers la solution la plus économe intellectuellement qui consisterait à reprendre le typage à la Typescript. Ce typage a été conçu comme "pansement" sur le langage Javascript, et souffre de nombreuses limites. Si on doit ajouter un système de type algébraïque, alors je sera plutôt favorable à me rapprocher des langages fonctionnels (Ocaml). 


Enfin, la raison principale est que plus on ajoute de "puissance" au langage, plus il perd en lisibilité, en accessibilité, et en prédictabilité. Je suis partisant d'avoir un langage le plus limité possible afin d'avoir une correspondance parfaite entre expressivité et forme idiomatique. Autrement dit, que pour un besoin, il y ait une seule façon de faire. 

Typiquement le cas d'usage CGU est déjà couvert aujourd'hui. Même si c'est un peu moins puissant, c'est plus lisible et suffisant pour le langage. Et c'est plus facile à convertir automatiquement en formulaire. 

```yaml
CGU acceptée:
  type: boolean

  avec: 
    raisons refus:
      applicable si: CGU acceptée = non
      description: "je refuse les CGU pour ces raisons"
      type: texte

  
un branche necessitant les CGU:
  applicable si: CGU acceptée
```
