### DISCUSSION TITLE
Une solution pour éviter de répeter l'espace de nom à chaque règle

### DISCUSSION THREAD

**Discussion by johangirod** [publicodes/publicodes#86] [Ideas]
# DISCLAIMING
Après discussion, les solutions esquissées dans ce premier post ne sont pas satisfaisantes. On préfèrera implémenter les idées suivantes : 
1. #163
2. #183

Les éléments à retenir de cette discussions sont : 
- https://github.com/betagouv/publicodes/discussions/86#discussioncomment-1625146
- https://github.com/betagouv/publicodes/discussions/86#discussioncomment-1554361

## Proposition (dépréciée)
Aujourd'hui, on se retrouve à réecrire systématiquement l'espace de nom à chaque nouvelle règle. C'est très verbeux,  lourd et ça apporte relativement peu d'informations. Surtout pour les fichiers qui ont un unique namespace (`contrat salarié` par exemple).

Le seul avantage c'est que ça permet de réorganiser les règles comme on le souhaite en associant aucune sémantique à l'ordre de définition. 

- **objection n°1** : il n'est pas totalement vrai qu'il n'y ait aucune sémantique à l'ordre de définition, on utilise ce dernier dans les formulaire généré par publicodes pour afficher les questions dans l'ordre donné (aide à la déclaration & mobilité). Par ailleurs, à score équivalent, les missingVariables feront remonter la règle la plus haute dans le texte
- **objection n°2** : Les règles sont quasiment toujours écrite dans l'ordre de leur espace de nom. Et lorsque ce n'est pas le cas, c'est plutôt un problème (lisibilité plus difficile) qu'une solution. Il semble plus sain d'enforcer que toutes les règles du même espace de nom soit définie au même endroit.

### Proposition

Il faudrait que l'espace de nom puisse être défini pour un ensemble de règles, sans avoir besoin de le répéter. Je vois quelques pistes en la matière, qui ne sont pas forcément exclusives. Dans tous les cas, la rétro compatibilité avec l'existant est de mise.

#### Piste 1 : le markdown #60 

On passe à une syntaxe axée document. Les espaces de nom correspondent à des titres. En ce sens, il n'est plus nécessaire de répéter l'espace de nom précédent. Par contre, il faut faire attention aux niveaux de titre (au nombre de `#`), et cela peut rendre les réorganisation plus prône aux erreurs.

Ceci dit, le markdown serait un des format accepté en entrée, et n'a pas vocation à remplacer complètement le yaml. Il faut donc trouver des solutions additionnelles pour ce dernier.

#### Piste 2 : namespacer un fichier via une commentaire

On peut imaginer un commentaire meta en haut de fichier qui namespace l'ensemble des règles définie dans le fichier
```yaml
# ~ espace : contrat salarié
~ racine : 
  descritption: Les règles du contrat salarié
  applicable si: employé

rémunération: 
temps de travail:
aides employeur:
...
```
On aurait le mot clé ~ racine qui permet de définir la règle racine de l'espace de nom.

#### Piste 3 : utiliser le (futur) type liste et le mécanisme `nom`

```yaml
contrat salarié: 
  liste:
    - nom: cotisations
    - nom: salaire
    - nom: temps de travail
```

Solution pas complètement satisfaisante, puisqu'elle force le type et la valeur des espace de nom à une liste, et qu'elle oblige à avoir une indentation potentiellement énorme.

#### Piste 4: à l'intérieur du fichier, en publicodes

La ça devient plus difficile, vu que l'on est limité par la syntaxe yaml. Si on veut garder le principe que les clés d'un objet n'ont pas d'ordre précis, on est obligué d'ajouter des règles méta spécifiques opérant sur des tableaux. Par exemple :

```yaml
~ espace = contrat salarié . temps de travail:
    ~ racine: 
       description: la quantité de temps de travail
    heures supplémentaires: 
      description: xxx
    temps partiel:
```

L'espace de nom s'appliquerait à toutes les règles de même niveau. On remarque l'apparition du `~` qui serait reservés aux meta publicodes (unités par exemple).

### Conclusion

Il reste encore des choses à éclaircir, et notamment la syntaxe, qui est est peut-être trop obscur et éloigne un peu publicodes de ses intentions de simplicité d'utilisation. Mais je pense qu'en utilisants ces différents mécanisme, on pourrait aboutir à une meilleur gestion des espaces de noms en publicodes, et pourquoi pas jeter les bases d'une meilleure gestion des dépendances entre fichiers avec une modularisation plus avancée.

#### Exemple taille réel
```yaml
# ~ espace = contrat salarié
~ racine: 
  description: Les règles du contrat salarié
  applicable si: employé

~ espace = frais professionnels:
  ~ racine: 
    unité: €/mois
    description: >-
      Les frais professionnels correspondent à des dépenses engagées par le salarié pour les besoins de son activité professionnelle. Ces frais sont ensuite remboursés par l’employeur.  

  part déductible: 

  titre restaurant:

**Comment by mquandalle** [comment]
En plus de la question sur la syntaxe, je pense que cette fonctionnalité nécessitera un support de l'éditeur de texte #49 pour pouvoir conserver l’expérience de développement actuelle, en particulier pour :
- afficher le nom complet d'une règle et pouvoir le copier/coller (on peut le faire avec les [code lens de VSCode](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup))
- rechercher parmi les règles comme on peut le faire aujourd'hui avec un <kbd>Ctrl</kbd>+<kbd>R</kbd> 
  ![image](https://user-images.githubusercontent.com/1730702/136962897-df19d2d4-5e8e-488b-8276-584f8d2dc40c.png)

**Comment by laem** [comment]
Quelques avis. 

La solution 1) markdown a à mon avis quelques problèmes. 

- comme je le dis dans [ce commentaire](https://github.com/betagouv/publicodes/discussions/60#discussioncomment-739021), je ne suis pas certain que les description, titre et note soient les informations les plus importantes, pourtant ce sont celles qui deviendraient "natives" au format de document et qui précéderaient le code, avec un risque de confusion : à quelle règle appartient cette description ? 
- je pense que la rédaction de fichiers markdown qui cite du code pourrait être utilisée plutôt dans l'optique de faire des "guides" ou "documentations". Ce serait un format **complémentaire**.
- le passage au markdown risque d'enlever la coloration syntaxique, notamment sur github, sauf à préfixer chaque bout de code par ` ```yaml ``` `, ce qui peut s'avérer pénible
- les titres en markdown sont là pour convier de l'information de description non rigoureuse. On transforme alors leur usage pour définir des informations qui se doivent d'être exactes. C'est le cas dans une clef yaml, qui doit être exacte.

@johangirod tu n'as pas envisagé la solution du nom de fichier ? 

Le nom de fichier serait simplement ajouté à toutes les variables du fichier. Alors ça pose le problème que le style actuel du fichier "fourre-tout" ne marcherait plus. Mais on pourrait établir la convention que tout ce qui est dans `index.yaml` ne serait pas préfixé, ce qui forcerait à mettre de l'ordre, utiliser des dossiers pour les hiérarchies, etc.

Autre solution : il s'agirait de nommer les fichiers différemment. 

Si le fichier s'appelle `index.yaml` ou `cotisations.yaml`, alors il ne se passe rien. S'il s'appelle `transport>.yaml` alors toutes ses variables seraient préfixées. Ou l'inverse, s'il s'appelle `~ mon implé.yaml`, alors c'est le bazar, et sans le préfixe `~`, c'est préfixé.

Note : cette solution peut être implémentée hors publicodes : le moteur importe du yaml, par un répertoire. Dans nosgestesclimat par exemple, ce serait a priori trivial de préfixer toutes les variables par leur nom de fichier[ via ce script clef.](https://github.com/datagir/nosgestesclimat/blob/master/scripts/rulesToJSON.js), et c'est franchement quelque chose qui nous ferait du bien.

L'avantage des noms de fichiers, c'est que ça permet de passer d'un namespace à l'autre avec Ctrl-P (ou équivalent).

**Reply by mquandalle** [reply]
Favorable à l'idée d'utiliser les noms de fichiers comme espaces de nom. Qu'en pense l'équipe CDTN @maxgfr ?

**Reply by laem** [reply]
Je teste la solution avec '>'. 
Petit problème avec une commande du type `mv fichier.yaml fichier>.yaml`, il faut entourer le nouveau nom  `"fichier>.yaml"` de guillements.

**Reply by maxgfr** [reply]
Super intéressante la discussion, merci de m'avoir notifié. Côté cdtn, ça peut clairement être un game changer.

Je pense que dans un premier temps qu'il serait intéressant d'avoir un merger intégré dans la gestion des yaml. Actuellement, nous utilisons [ce fichier](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-modeles/src/internal/merger.ts) qui a pour but de merger l'ensemble de nos [yaml](https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/code-du-travail-modeles/src/modeles/conventions). Ainsi, pourquoi pas créer un register dans lequel on place l'ensemble de nos fichiers, celui-ci aura pour but de les load (en utilisant par example [cette librairie](https://github.com/nodeca/js-yaml) et de resolve la gestion des namespaces partagés entre chaque fichier.

Concernant ensuite la problématique d'héritage du namespace dans le but de les raccourcir, vos propositions me semblent pas mal du tout.

Enfin, dabs notre use case, nous allons mettre en place de nouveaux simulateurs faisant références aux conventions collectives. Les conventions collectives risquent donc d'être share entre plusieurs simulateurs, où à l'inverse que chaque similateur ait ses propres conventions collectives. Cela pourra vite devenir ingérable au niveau des namespaces et/ou de la manière dont on gère nos fichiers.

**Reply by laem** [reply]
De mon côté l'expérimentation est ici : https://github.com/laem/futureco/tree/fv2/source/sites/publicodes/ferry

Trois fichier : 
- le JS qui charge le modèle avec ajout de préfixe
- le fichier index.yaml qui est un fourre tout
- le fichier services dont chaque variable sera préfixé

**Reply by maxgfr** [reply]
Ok, je vois très bien. De mon côté, il est vrai que je suis pas super fan d'avoir un fichier de la sorte comportant le namespace.

Créer une variable global au sein du yaml du style : `namespace courant: ferry . charges . service` ou `namespace: ferry . charges . service`, serait-il pas mieux ?

**Comment by mquandalle** [comment]
(suite au commentaire ci-dessus https://github.com/betagouv/publicodes/discussions/86#discussioncomment-1547909)

Une alternative, en gardant l'idée de définir un espace de nom par fichier, est de référencer les fichiers externes dans le fichier de base :

```yaml
indépendant:
  description: toutes les infos pour les indépendants

indépendant . profession libérale:
  publicode: ./profession-liberale.yaml
```

Toutes les règles définies dans `profession-liberale.yaml` deviennent alors accessibles via l'espace de nom `indépendant . profession libérale . x`

### Avantages

1. Les références vers les fichiers externes peuvent être “résolues” par publicodes, ce qui supprime le besoin d'un fichier `merger.js`
2. Il devient possible de référencer des fichiers publicodes édités par des tiers en utilisant leur URL (cf. https://github.com/betagouv/publicodes/discussions/89#discussioncomment-1537063)

  ```yaml
    salarié:
      description: toutes les infos pour les salariés
    
    salarié . prévis de retraite:
      # ici on utilise un lien vers un commit précis pour être sûr d'avoir la version désirée,
      # mais on pourrait aussi avoir un numéro de version dans l'URL qui permet des mises à jour rétro-compatibles
      publicode: https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/3bedbae58338eaa624a7c1c9ad0496a4cb4e2dad/packages/code-du-travail-modeles/src/modeles/contrat-salarie.yaml
  ```

3. Cela permet aussi de faire du “code splitting” au niveau des règles. On peut soit importer seulement le fichier `transports/ferry.yaml` pour un simulateur thématique, ou bien importer `transport.yaml` avec une référence vers les règles du ferry pour un simulateur plus général. 

### Difficultés

1. Au niveau de l'UI cela peut poser une difficulté car on pourra alors référencer les règles soit par leur nom dans le publicodes spécialisé par exemple `ferry . longueur`, soit avec le nom complet dans l'espace de nom d'un simulateur plus global, par exemple `transport . ferry . longueur`. On peut résoudre ce problème avec un contexte React pour préciser l'espace de nom : 

```js
// Ce composant serait importé depuis un simulateur “spécialisé” dans le calcul de l'impact d'un ferry
export const FerryExplanation = () => <img src="ferry.svg" width={evaluateRule('ferry . longueur').nodeValue} />

// Pour l'afficher sur un simulateur plus général, il faut préciser un espace de nom via un contexte React
import { Namespace } from 'publicodes-react'
export const TransportExplanation = () =>
  <Namespace.Provider value="transport">
    <FerryExplanation />
  </Namespace.Provider>
```

2. Si on veut importer un dossier avec 100 fichiers, cela peut être rébarbatif :

```yaml
préavis de retraite . convention collective:

prévis de retraite . convention collective . 3021:
  publicode: ./conventions-collectives/3021.yaml

prévis de retraite . convention collective . 3043:
  publicode: ./conventions-collectives/3043.yaml

prévis de retraite . convention collective . 3065:
  publicode: ./conventions-collectives/3043.yaml

# etc
```

On peut alors imaginer importer un répertoire complet

```yaml
préavis de retraite . convention collective:

prévis de retraite . convention collective:
  publicode: ./conventions-collectives/*.yaml
```

**Reply by maxgfr** [reply]
Je trouve l'idée assez séduisante, ça me rappelle un peu ce que peut faire un `index.ts` à la racine d'un dossier !

**Reply by laem** [reply]
Très intéressant ! 

Pas fan du mot clef "publicode:" par contre. Je dirais plutôt "import" ? Ou "fichier" ? Ou "sources" ? 

Par contre, si je me trompe pas, ça veut dire l'ajout de la gestion des fichiers directement dans la lib publicodes, alors qu'elle se contentait pour l'instant de charger un string. 

L'avantage, c'est que cette solution n'est pas incompatible avec ma proposition des noms de fichiers, car l'import dans cette dernière est géré par l'intégrateur avant de charger un gros JSON à publicodes. 

J'avoue personnellement avoir une préférence pour un import automatique. 

```yaml
indépendant . profession libérale:
  publicode: ./profession-liberale.yaml
  ```
  
  Dans cette proposition, je pense que la première réaction d'un contribueur qui n'est pas habitué à l'histoire des imports de code serait "ben pourquoi je dois écrire cette évidence" ? Le fait que tout ce qui est dans un fichier nommé "profession-libérale" se trouve dans le contexte "profession-libérale" me semble suffisemment logique.

**Reply by mquandalle** [reply]
Oui `import` c'est sans doute mieux

```yaml
indépendant . profession libérale:
  import: ./profession-liberale.yaml

salarié . prévis de retraite:
  import: https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/3bedbae58338eaa624a7c1c9ad0496a4cb4e2dad/packages/code-du-travail-modeles/src/modeles/contrat-salarie.yaml
```

Je n'ai pas d'avis tranché sur l'import automatique.
