### DISCUSSION TITLE
Implémentation alternative pour les recalculs

### DISCUSSION THREAD

**Discussion by mquandalle** [publicodes/publicodes#92] [Ideas]
Le mécanisme recalcul permet de calculer l'ensemble de l'arbre dans une situation modifiée par rapport à la situation parente.

## Problème

Actuellement l'implémentation consiste à instancier un nouveau moteur, puis à définir la situation d'entrée à partir de la situation parente et des modifications définies dans le recalcul.

Cette pose au moins deux problèmes :

1. L'arbre recalculé n'est accessible que depuis le mécanisme qui le définit, et on ne peut récupérer qu'une seule valeur. En conséquence, si on veut récupérer la valeur de deux règles dans une situation recalculée, on est obligés de redéfinir (et de recalculer) 2 fois le recalcul : 

```yaml
chômage partiel . revenu net habituel:
  formule:
    recalcul:
      règle: contrat salarié . rémunération . net
      avec:
        contrat salarié . activité partielle: non


chômage partiel . coût employeur habituel:
  formule:
    recalcul:
      règle: contrat salarié . prix du travail
      avec:
        contrat salarié . activité partielle: non
```

([voir le code sur mon-entreprise](https://github.com/betagouv/mon-entreprise/blob/4c728b0609b4058d1da997141ad9f775593c37ab/modele-social/r%C3%A8gles/ch%C3%B4mage-partiel.yaml#L3-L15))

2. L'utilisateur du moteur ne peut pas récupérer facilement les valeurs intermédiaires du recalcul. Cela vaut aussi pour la documention. En effet les “explications” qui sont fournies avec chaque nœud calculé doivent être sérialisables, ce qui n'est pas le cas de l'instance du moteur utilisée pour faire le recalcul. À la place on indique dans l'objet “explications” la situation utilisée par le recalcul, et c'est à l'utilisateur du moteur de ré-instancer un moteur avec cette situation modifiée.

```
const recalculEngine = engine
		.shallowCopy()
		.setSituation(explanation.parsedSituation)
```

https://github.com/betagouv/mon-entreprise/blob/4c728b0609b4058d1da997141ad9f775593c37ab/publicodes/ui-react/source/mecanisms/Recalcul.tsx#L22-L24

Ainsi cette contrainte d'instancier un moteur pour accéder aux variables intermédiaires nous oblige à le faire deux fois : une fois côté moteur publicodes, et une fois côté utilisateur / documentation.

## Proposition

L'idée serait de voir le recalcul comme une manière de faire un copier/coller statique de l'ensemble de l'arbre des règles, en renommant toutes les règles pour les inclure dans l'espace de nom du recalcul. Ainsi si on a un arbre avec les règles `A` et `B`, et une règle `C` qui fait un recalcul, on pourrait accéder aux règles `A` et `B` dans le contexte du recalcul `C` via `C . A` et `C . B`

![image](https://user-images.githubusercontent.com/1730702/140105216-b694c082-81dd-43ca-8ca2-97b05bc0e2d1.png)

Se pose éventuellement le problème d'une récursion infinie avec `C . C` mais c'est un problème déjà existant, que l'on résout actuellement dans la sémantique du recalcul en précisant qu'un recalcul dans un recalcul est non applicable.

Cette implémentation permettrait de résoudre les deux problèmes ci-dessus : on pourrait référencer plusieurs valeurs d'un même recalcul, et d'autre part on n'aurait pas besoin de ré-instancer un moteur pour documenter le recalcul.

Cela permet aussi de supprimer la spécificité d'évaluation du recalcul, qui devient une forme de transformation statique comme le remplacement, et simplifie l'implémentation d'autres fonctionnalités comme #54.

**Comment by johangirod** [comment]
J'ai un autre problème lié à l'implémentation actuelle du recalcul. 

Si nous prenons l'exemple suivant : 
```yaml
a: b + 10
b: 5

resultat: 
  recalcul:
    règle: a
    avec: 
      b: b * 2
```
[Voir dans le studio](https://publi.codes/studio?code=%0Aa%3A+b+%2B+10%0Ab%3A+5%0A%0Aresultat%3A+%0A++recalcul%3A%0A++++r%C3%A8gle%3A+a%0A++++avec%3A+%0A++++++b%3A+b+*+2)

Actuellement, la valeur de `b` est substituée par `b * 2` dans le recalcul, ce qui aboutit bien évidement à un cycle. Hors je ne suis pas certain que ce soit le comportement attendu.

Lorsqu'on entame un recalcul on veut passer les variables dans le contexte de l'appel, et non dans le contexte du recalcul lui même. On s'attend donc ici à avoir un recalcul de `a` avec la valeur de `b` qui vaut `5 * 2`. 

Il est à noté que ce changement peut être fait avec ou sans ta nouvelle proposition d'implémentation, mais ça me paraissait intéressant de regrouper les discussions sur ce mécanisme au même endroit.
