### ISSUE TITLE
Vérifier la saisie du mécanisme variations

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#145]
J'ai récemment eu un bug ou il manquait un tiret devant le `sinon:` du mécanisme variations, cela provoque une erreur de logique silencieuse.

```yaml
vélo: "'mécanique'"

prime vélo:
  variations:
    - si: vélo = 'électrique'
      alors: 200€
    - si: vélo = 'mécanique'
      alors: 100€
      sinon: 0€
```

[studio](https://publi.codes/studio?code=v%C3%A9lo%3A+%22%27m%C3%A9canique%27%22%0A%0Aprime+velo%3A%0A++variations%3A%0A++++-+si%3A+v%C3%A9lo+%3D+%27%C3%A9lectrique%27%0A++++++alors%3A+200%E2%82%AC%0A++++-+si%3A+v%C3%A9lo+%3D+%27m%C3%A9canique%27%0A++++++alors%3A+100%E2%82%AC%0A++++++sinon%3A+0%E2%82%AC%0A)

Ici pour un vélo mécanique on s'attend à 100€ de prime, mais on obtient 0€ à cause du tiret manquant sur la dernière ligne.
