### ISSUE TITLE
Remplacement qui change une variable en "undefined" de manière inattendue

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#201]
Dans l'exemple ci-dessous, `TVA` vaut `undefined` alors que la valeur attendue est `1 €`.

```yaml
promotion:
  applicable si: oui
  remplace:
    règle: prix
    par: 5 €

prix: 10 €

TVA: 20% * prix
```

[studio](https://publi.codes/studio?code=promotion%3A%0A++applicable+si%3A+oui%0A++remplace%3A%0A++++r%C3%A8gle%3A+prix%0A++++par%3A+5+%E2%82%AC%0A%0Aprix%3A+10+%E2%82%AC%0A%0ATVA%3A+20%25+*+prix%0A)

On retombe sur la bonne valeur en remplace le `applicable si` par un `valeur` à la ligne 2.

Il semble que ça soit lié au fait que la `nodeValue` de `promotion` soit `undefined` ce qu'il fait ce qui entraîne une contagion à toutes les formules ayant une référence remplacée.
