### ISSUE TITLE
Remplacement applicable quand la règle de définition est applicable

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#202]
## Comportement actuel
Aujourd'hui, un remplacement est **uniquement actif** si la **règle de définition** a une **valeur différente** de :
- non défini (`undefined`)
- non applicable (`null`)
- non (`false`)

### 1. Un remplacement sur une règle non définie n'est pas actif
```yaml
promotion:
  applicable si: oui
  remplace:
    règle: prix
    par: 5 €

prix: 10 €

TVA: 20% * prix
```
Dans l'exemple ci-dessus, on s'attend plutôt à ce que le remplacement soit actif par défaut.

### 2. Ambiguïté entre valeur remplacée et activation du remplacement

```yaml
exonération de cotisations minimales:
  applicable si: situation personnelle . RSA
  remplace:
    - invalidité et décès . assiette . plancher
    - maladie . assiette . plancher
    - retraite de base . assiette . plancher
  valeur: non
  références:
    secu-independants.fr: https://www.secu-independants.fr/cotisations/calcul-des-cotisations/cotisations-minimales/
```
https://github.com/betagouv/mon-entreprise/blob/585f9b133980bf47b860165546c6214df107110f/source/rules/dirigeant.yaml#L1040-L1046

il y a deux interprétations possibles :

1. Soit on remplace les règles listées par la valeur `non`
2. Soit _non_, on ne fait pas de remplacement

Aujourd'hui, c'est le cas 2 qui est opérant. Or ce cas est une exception par rapport au comportement de base.
Il faudrait simplifier le modèle et toujours activer le remplacement de la même manière.

## Proposition

**Un remplacement est actif si la règle de définition n'est pas `non applicable`**
