### ISSUE TITLE
Bug avec les règles imbriquées et composante 

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#207]
## Situation
```yaml
retraite CNAVPL: 
  produit:
    assiette:
      nom: revenu cotisé
      valeur: assiette des cotisations
      plancher: assiette minimale . retraite
    composantes:
      - attributs:
          nom: tranche T1
          arrondi: oui
        taux: 8.23%
        plafond: plafond sécurité sociale temps plein
      - attributs:
          nom: tranche T2
          arrondi: oui
        taux: 1.87%
        plafond: 5 * plafond sécurité sociale temps plein
```

L'assiette du produit est factorisée ici entre les deux composantes et déclare une variable imbriquée `revenu cotisé`.

## Attendu

On s'attend à pouvoir accéder à l'assiette via la référence `retraite CNAVPL . revenu cotisé`.

## Actuel

La règle imbriquée de l'assiette est créée après le développement des composantes en somme. Cela abouti à la création de deux règles imbriquées distinctes : 
-  `retraite CNAVPL . tranche T1 . revenu cotisé`
 - `retraite CNAVPL . tranche T2 . revenu cotisé`

**Comment by fmata** [comment]
Je ne sais pas si c'est directement lié mais je constate un problème dans un remplacement d'une règle avec un produit et des composantes, lui-même utilisé dans une règle elle aussi remplacée.

Il semble que les composantes, bien que correctement calculées, ne soient pas utilisées dans le remplacement de 2ème niveau. Le seul contournement que j'ai trouvé pour le moment c'est d'éliminer l'utilisation du mécanisme `composantes` en découpant ma règle en 2. En fait, même en 3 car `composantes` est utilisé dans mon cas pour la part employeur et salarié. Je me retrouve avec 1 règle pour la part employeur, 1 pour la part salarié et 1 autre pour le total...

Ex : 

```yaml
perso . cotisations . patronales:
  remplace: contrat salarié . cotisations . patronales
  formule: contrat salarié . cotisations . patronales + truc

perso . cotisations . salariales:
  remplace: contrat salarié . cotisations . salariales
  formule: contrat salarié . cotisations . salariales + truc
```

Ne fonctionne pas (la valeur des règles ci-dessus ne change pas)

```yaml

perso . contribution d'équilibre technique:
  remplace: contrat salarié . contribution d'équilibre technique
  produit:
    assiette: perso . autre . règle . montant
    composantes:
      - attributs:
          nom: employeur
        taux: 60%
      - attributs:
          nom: salarié
        taux: 40%
```

Fonctionne

```yaml

perso . contribution d'équilibre technique:
  remplace: contrat salarié . contribution d'équilibre technique
  formule:
    somme:
      - employeur
      - salarié

perso . contribution d'équilibre technique . employeur:
  acronyme: CET
  remplace: contrat salarié . contribution d'équilibre technique . employeur
  cotisation:
    branche: retraite
    type de retraite: complémentaire
    destinataire: AGIRC-ARRCO
  formule:
    produit:
      assiette: perso . autre . règle . montant
      taux: 60%

perso . contribution d'équilibre technique . salarié:
  acronyme: CET
  remplace: contrat salarié . contribution d'équilibre technique . salarié
  cotisation:
    branche: retraite
    type de retraite: complémentaire
    destinataire: AGIRC-ARRCO
  formule:
    produit:
      assiette: perso . autre . règle . montant
      taux: 40%
```

Même problème ?
