### ISSUE TITLE
Le taux effectif de l'impôt sur le revenu d'un revenu d'activité semble erroné

### ISSUE THREAD

**Issue by fmata** [publicodes/publicodes#223]
Bonjour,

En comparant le montant d'impôt sur le revenu et le taux effectif calculés par publicodes avec le montant et le taux PAS du simulateur officiel (https://simulateur-ir-ifi.impots.gouv.fr/calcul_impot/2022/simplifie/index.htm), il apparait une différence : publicodes calcule correctement le montant annuel de l'impôt mais surestime le taux et donc le montant prélevé sur la fiche de paie.

Exemple avec [une simulation à 4000€ bruts au barème standard](https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net?entreprise+.+SIREN=%27513051656%27&entreprise+.+activit%C3%A9+principale=%27Autres+activit%C3%A9s+informatiques%27&entreprise+.+cat%C3%A9gorie+juridique=%27EI%27&entreprise+.+cat%C3%A9gorie+juridique+.+EI+.+auto-entrepreneur=non&entreprise+.+date+de+cr%C3%A9ation=%2701%2F06%2F2009%27&entreprise+.+imposition=%27IR%27&entreprise+.+imposition+.+IR+.+type+de+b%C3%A9n%C3%A9fices=%27BNC%27&entreprise+.+imposition+.+IR+.+type+de+b%C3%A9n%C3%A9fices+.+BIC+et+BNC+possibles=oui&entreprise+.+imposition+.+r%C3%A9gime=%27d%C3%A9claration+contr%C3%B4l%C3%A9e%27&entreprise+.+nom=%27FLORENT+MATA%27&imp%C3%B4t+.+m%C3%A9thode+de+calcul=%27bar%C3%A8me+standard%27&salaire-brut=4000%E2%82%AC%2Fmois&%C3%A9tablissement+.+SIRET=%2751305165600017%27&%C3%A9tablissement+.+localisation=%7B%22objet%22%3A%7B%22nom%22%3A%22Marseille+11e+Arrondissement%22%2C%22code%22%3A%2213211%22%2C%22codesPostaux%22%3A%5B%2213011%22%5D%2C%22departement%22%3A%7B%22code%22%3A%2213%22%2C%22nom%22%3A%22Bouches-du-Rh%C3%B4ne%22%7D%2C%22region%22%3A%7B%22code%22%3A%2293%22%2C%22nom%22%3A%22Provence-Alpes-C%C3%B4te+d%27Azur%22%7D%2C%22codePostal%22%3A%2213011%22%2C%22taux+du+versement+transport%22%3A2%7D%7D&utm_source=sharing) sans répondre aux autres questions : 

Le simulateur officiel donne : 
- impôt annuel : 4550€
- taux PAS : 11.6%

publicodes : 
- impôt annuel : 4550€
- taux effectif : 12.84%

En fouillant un peu, j'ai trouvé l'explication sur la page du simulateur qui détaille l'obtention du taux PAS :

Simulateur officiel : 100 * impôt annuel / revenus imposables = 100 * 4550 / 39363 = 11.6%.
publicodes : 100 * impôt annuel / revenus imposables = 100 * 4550 / 35426 = 12.84%

Or `impôt . foyer fiscal . revenu imposable` utilise `revenu d'activité abattu` au lieu de `contrat salarié . rémunération . net imposable` :

```yaml
impôt . foyer fiscal . revenu imposable:
  formule:
    somme:
      - revenu d'activité abattu
      - applicable si:
          toutes ces conditions:
            - dirigeant . rémunération . imposable
            - entreprise . imposition . IR
        valeur: dirigeant . rémunération . imposable
      - bénéficiaire . dividendes . imposables
      - autres revenus imposables
```
Ok avec ce constat ? Voulez-vous apporter une correction ?

Ou peut être que `taux effectif` est utilisé ailleurs pour une autre raison, dans ce cas il faudrait ajouter une règle `taux du prélèvement à la source` telle que je viens de l'expliquer.

Merci
