### ISSUE TITLE
Enforce a consistent order for replacement rules

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#313]
If there are two replacement rules with the same target, which one will be applied first? See #312
Currently this is not specified in the documentation, and worst, in practice it seems to depend on the order of rule declarations, something that must not be relied upon.

**Comment by wiinxt** [comment]
Est ce que les `remplace` ne pourrais pas être sur la règle qui va être remplacé ?
Cela permettrais de choisir l'ordre et aussi de mieux se rendre compte que cette règle peut être remplacé

```yaml
frais de repas: 5 €/repas
    peut être remplacé par:
        - convention hôtels cafés restaurants . frais de repas restaurateur

convention hôtels cafés restaurants: oui
convention hôtels cafés restaurants . frais de repas restaurateur:
    remplace: frais de repas # à voir si on garde le remplace ici aussi
    valeur: 8 €/repas

montant repas mensuels: 10 repas * frais de repas
```
(désolé pour le français ^^)

**Comment by mquandalle** [comment]
Non car ce n'est pas la règle qui est replacé, mais les références vers cette règle. Il faut l'imagine comme une <kbd>Ctrl</kbd> + <kbd>R</kbd> directement sur le code source des règles.

Si on fait un replacement général ça ne change pas grand chose, mais un intérêt important de la fonctionnalité est de pouvoir remplacer les références dans un sous-ensemble de règles via l’utilisation de `dans` et `sauf dans`.

(Je me note d'expliquer tout ça dans un guide dédié #314)

**Comment by wiinxt** [comment]
Je pensais pas à modifier sont comportement mais juste la syntaxe dans les yaml.
Je savais pas qu'il y avait `dans` et `sauf dans`, tu aurais un exemple ?

**Comment by mquandalle** [comment]
Très sommaire https://publi.codes/docs/principes-de-base#remplacement

**Comment by wiinxt** [comment]
ah oui je comprend mieux du coup

**Comment by johangirod** [comment]
> Currently this is not specified in the documentation, and worst, in practice it seems to depend on the order of rule declarations, something that must not be relied upon.

Well, CSS does the same and it's not as bad as it sound. As long as it's clearly stated in the documentation and that it triggers a warning, that's fine by me.

However, I suggest to inverse the actual behaviour. Instead of the first rule specifying the replacement having precedence, I would rather see the last.

Indeed, it would allow for more specific rules to be further down the file, and so holding the generic first / specific last principle.

That being said, we should not be forced to rely on this solution (two replacement for the same rule) as often as it is now. The current limitation comes from #55. It would allow replacing a rule which replace another, and thus, explicitly stating the order of precedence directly in the code.

**Comment by wiinxt** [comment]
Mais du coup même si ce n'est pas la règle qui est remplacé mais la référence, on pourrais quand même avoir l'ordre de priorité sur la règle non ?

Le `remplace` est assez invisible quand on arrive sur une base de code, avoir un lien plus concret entre deux règle avec `remplace`+`peut être remplacé par` et qui permet aussi de résoudre le problème d'ordre je trouve ça pas trop mal

```yaml
temps de préparation: 20 min
  peut être remplacé par:
    - CUISINATOR9000
    - robot de cuisine
temps de cuisson: 20 min

robot de cuisine:
  remplace:
    - règle: temps de préparation
      sauf dans: temps original
      par: 10 min
  valeur: oui

CUISINATOR9000:
  remplace:
    - règle: temps de préparation
      sauf dans: temps original
      par: 1 min
  valeur: oui

temps original:
  formule: temps de préparation + temps de cuisson

temps modifié:
  formule: temps de préparation + temps de cuisson
```
