### ISSUE TITLE
Renommage des paramètres des remplacements

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#319]
Au lieu d'écrire : 
```yaml
a: 
  applicable si: x
  remplace: 
    règle: b
    dans: c
    par: 4€
```

on écrirait : 

```yaml
a: 
  applicable si: x
  avec:
    b: 
     remplace:  
       références à: b
       dans: c
     valeur: 4€
```

En gros : 
- Supprimer le mot clé `par`. Si on veut remplacer une règle, alors on créer une nouvelle règle avec la nouvelle valeur
- Changer le mot `règle` par `référence à`, ce qui correspond à ce que fait le remplacement. 

Et du coup, on peut en profiter pour ajouter #202  au mix, vu la refacto nécessaire. Comme ça on est clean \o/

**Comment by mquandalle** [comment]
Discuté ensemble : version course et `références à`

**Comment by johangirod** [comment]
@mquandalle je te pingue vu qu'on a un peu revu la syntaxe de `remplace` au dernier publicodes café.

**Comment by mquandalle** [comment]
D'accord sur le renommage des attributs, en revanche je trouve l'exemple `a: avec: b: remplace:` franchement ésotérique. #202 m'apparaît nécessaire pour retrouver l'équivalent de l'écriture actuelle mais avec les nouveaux noms d'attributs : 

```yaml
a: 
  applicable si: x
  valeur: 4€
  remplace: 
    références à: b
    dans: c
```
