### ISSUE TITLE
Renommer les paramètres de `recalcul`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#320]
Aujourd'hui, `recalcul` accepte deux paramètres `règle` et `avec` : 

```
b: 
  recalcul: 
    règle: a
    avec: 
      x: 4
```

Je propose de renommer : 
1. `règle` en `valeur` : on peut recalculer une expression, et les références dans cette expression pourront être remplacée.
2.  `avec` en `avec la situation` : pour ne pas confondre avec le mécanisme `avec`. Par ailleurs, cela correspond à l'implémentation actuelle du mécanisme `recalcul`

```
b: 
  recalcul: 
    valeur: a
    avec la situation: 
      x: 4
```

**Comment by mquandalle** [comment]
Je te suis sur 1, mais je pense que `valeur` ne doit pas être un mot clé obligatoire, car ça serait incohérent avec le reste du langage où c'est un mécanisme transparent. Autrement dit si on supporte `recalcul: valeur: a` on veut aussi supporter

```yaml
b:
  recalcul:
    somme:
      - a
      - 5
```

(ce qui n'est peut-être pas si simple sachant qu'on a besoin d'un attribut `avec (la situation)` qui n'est pas un "mécanisme inline")

Sur 2, je ne suis pas sûr de `avec la situation` car : 
- un peu verbeux
- ça serait la première occurrence du concept de situation exposée directement dans les mécanismes (`nom dans la situation` n'est pas exposé), et je ne suis pas sûr que ce concept soit vraiment nécessaire pour la sémantique ou pour l'implémentation d'un recalcul

Je vois l'intérêt de distinguer ce mot clé du mécanisme `avec`, à voir si on a d'autres idées de nommage.

**Comment by johangirod** [comment]
> Je te suis sur 1, mais je pense que valeur ne doit pas être un mot clé obligatoire, car ça serait incohérent avec le reste du langage où c'est un mécanisme transparent.

Mmmh je suis partiellement d'accord. Les mécanismes inlines s'utilisent avec le mot clé valeur. Ainsi `plafond` peut s'utiliser ainsi : 

```yaml
plafond: 
  plafond: 5
  valeur: 4
```
C'est d'ailleurs la transformation statique effectuée au parsing de : 

```yaml
valeur: 4
plafond: 5
```

Par conséquent, si on veut laisser l'usager la possibilité de spécifier valeur ou non, je serai pour transformer en mécanisme chainable. Ce qui est plutôt logique.

Cela donnerait : 

```yaml
b: 
   somme: 
      - a 
      - 5
  recalcul avec:
    a: 12
```

qui serait traduit en : 
```yaml 
b:
   recalcul avec: 
     valeur: 
      somme: 
        - a
        - 5
      recalcul avec:
        a : 12
```

**Comment by mquandalle** [comment]
Intéressant de considérer "recalcul" comme un mécanisme, mais mon cerveau peine à saisir la distinction entre ces deux formules

```yaml
a: 
  somme: 
    - x 
    - 5
  recalcul avec:
    x: 12

b: 
  somme: 
    - x 
    - 5
  avec:
    x: 12
```

On aurait presque envie d'unifier ces deux concepts

**Comment by johangirod** [comment]
C'est quelque chose que tu évoquais déjà ici : https://github.com/betagouv/publicodes/discussions/163#discussioncomment-2674448

Tu dis que c'est un peu « foufou », en réflechissant, je me demande si c'est une bonne idée. Faudrait-il vraiment relier le recalcul et la définition de variable imbriqué au pretexte qu'un des mots clé utilisé est le même ?

Je pense qu'il est plus sage pour l'instant de séparer ces deux notions, comme elles n'ont rien à voir dans leur implémentation, avant d'y voir plus clair avec le `recalcul` (cf https://github.com/betagouv/publicodes/discussions/92).

J'irai même jusqu'à renommer `recalcul avec` en `recalcul en modifiant` pour être plus clair à ce sujet.

Peut-être que dans le futur, on arrivera à faire converger tout ça. Car je pense qu'il y a effectivement un lien entre recalcul, définition de fonction et définition de variable local, et que ce lien est à chercher du côté conceptuel des variables libres et variables liées (https://fr.wikipedia.org/wiki/Variable_libre). Mais je pense qu'il faudra d'abord relier les concepts avant d'unifier la syntaxe pour éviter d'avoir des comportements erratiques :)

**Comment by mquandalle** [comment]
Dans ce cas on pourrait interdire d'utiliser un nom déjà présent dans l'espace de nom courant via `avec` ?

```yaml
x: 1

a: 
  somme: 
    - x 
    - 5
  avec:
    x: 12
```

> Erreur: vous ne pouvez pas utiliser `x` dans le mécanisme `avec` car ce nom est déjà utilisé dans l'espace de nom. Vous pouvez
> - soit utiliser un autre nom
> - soit définir une variable `a . x`
> - soit utiliser un recalcul si vous voulez faire un remplacement global de `x`

Ça permet de clarifier ultérieurement le comportement que l'on veut dans ce cas là
