### ISSUE TITLE
Supprimer le mécanisme `nom`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#411]
Il est possible de définir une règle enfant directement dans la formule de calcul grâce au mot clé `nom`

```yaml
a: 
  somme: 
    - nom: carottes
      valeur: 10 kg * 2 €/kg
    - nom: oignons
      valeur: 5 kg * 2.5 €/kg
```
équivaut à 
```yaml
a: 
  somme: 
    - carottes
    - oignons
a . carottes: 10 kg * 2 €/kg
a. oignons : 5 kg * 2.5 €/kg
```

## Problème

Cette syntaxe est redondante avec celle permettant de définir des règles enfants depuis une règle parente (qui utilise actuellement le mot clé `avec`, [en discussion](#409)). Par ailleurs, elle peut aboutir à des comportements non définis et entrainer des bugs #300). Elle n'est pas si lisible, et est présente pour des raisons historique (cette syntaxe précède le mot clé `avec`). 

## Proposition 
Supprimer cette syntaxe en lui préférant la version `avec`  

```yaml
a: 
  somme: 
    - carottes
    - oignons
  avec: 
    carottes: 10 kg * 2 €/kg
    oignons : 5 kg * 2.5 €/kg
```

**Comment by mquandalle** [comment]
Même si actuellement je n'utilise pas `avec` mais que j'utilise occasionnellement `nom`, le suppression de ce dernier en faveur du premier me semble se défendre. J'ai survolé les usages actuels de `noms:` (via [cette commande](https://github.com/publicodes/publicodes/discussions/409#discussioncomment-7465754)) et rien vu qui ne puisse être ré-écrit aussi clairement via `avec`. Sauf peut-être quand cela est combiné avec les `composantes`, comme ici : 

```yaml
# mon-entreprise/modele-social/règles/dirigeant/professions-libérales/CNAVPL.yaml
- attributs:
    nom: tranche T1
    arrondi: oui
    unité: €/an
  taux:
    nom: taux
    valeur: 8.23%
  plafond: plafond sécurité sociale
```

Mais bon est-ce un grand mal de ne plus pouvoir écrire ce code de cette manière ?
