### ISSUE TITLE
Supprimer la syntaxe spéciale pour `variation`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#417]
Aujourd'hui, `variation` peut s'utiliser avec une syntaxe exotique au niveau d'un autre mécanisme : 

```yaml
a: 
  produit:
    assiette: 5 €
    variations: 
      - si: x
        alors: 
          taux: 10% 
      - sinon: 
          taux: 5%
```

Je propose de supprimer cette syntaxe dans la v1
