### ISSUE TITLE
Supprimer l'attribut `plafond` du mécanisme `produit`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#418]
Le mécanisme `produit` possède un attribut `plafond` pour des raisons historiques : on souhaitait pouvoir simplement plafonner une assiette, avant l'arrivée des mécanismes chainés `valeur` et `plafond`

**Avant**
```yaml
chômage:
  produit:
    assiette: assiette cotisation
    plafond: 400% * plafond sécurité sociale
    taux: 4%
```

**Après**
```yaml
chômage:
  produit:
    - assiette cotisation
    - taux
   avec: 
     taux: 4%
```

Plus simple, plus clair, et idiomatique : il y a une seule et bonne manière de faire.
