### ISSUE TITLE
Le mécanisme `produit` accepte une liste en argument

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#419]
### Actuel

Le mécanisme produit accepte trois argument : 
```
produit: 
  assiette: 1000 €
  taux: 5%
  facteur: 2
  plafond: 500€
```

### Problème avec l'existant
- Ces arguments sont là pour des raisons historiques mais ne sont absolument pas connus ni clairs sur leur effet (cf #418)
- Ils sont liés au métier de mon-entreprise (calcul des cotisations sociales) mais ne sont pas forcément transposable aux autres (calcul empreinte carbone)
- Il y a une différence de syntaxe dans l'utilisation de `somme` et `produit` qui n'est pas justifiable (somme accepte une liste d'opérande, produit devrait accepter une liste de facteurs). 

### Solution

Changer la syntaxe de produit pour prendre en argument une liste :
```yaml
cotisation: 
  produit: 
    - assiette
    - taux
  avec: 
    assiette: 1000€
    taux: 5%
```

Big breaking en perspective donc n'hésitez pas à up / down et à commenter.
