### ISSUE TITLE
Rendre le mécanisme "taux progessif" plus générique

### ISSUE THREAD

**Issue by mquandalle** [publicodes/publicodes#421]
On a eu la discussion la semaine dernière sur le mécanisme `produit`, qui utilise actuellement des arguments "assiette", "taux", "facteur" qui sont connotés "calcul de cotisations". On a décidé qu'une écriture plus générale sous forme d'une liste de facteurs était préférable et tout aussi lisible quelque soit le domaine métier considéré, cf. #419 

Une question comparable se pose pour le [mécanisme `taux progressif`](https://publi.codes/docs/api/m%C3%A9canismes#taux-progressif)

Cas d'usage : imaginons que l'on veut choisir la durée de vie d'une voiture entre 15 et 20 ans (15 ans pour les petits rouleurs, 20 ans pour les gros rouleurs) et avoir une progression linéaire entre les 2 bornes pour éviter un effet de seuil. Cela est possible avec le mécanisme `taux progressif`.

```yaml
km parcourus par an: 14000 km/an

durée de vie véhicule:
  description: |
    On prend une durée de vie du véhicule entre 15 et 20 ans.
    Hypothèse qu'un véhicule qui roule moins annuellement durera plus d'années.
    On prend 5000km/an pour un petit rouleur et 20000km/an pour un gros rouleur.
    Entre les deux bornes on fait progresser linéairement la valeur de durée de vie en année.
  produit:
    assiette: 1 an
    taux:
      taux progressif:
        assiette: km parcourus par an
        tranches:
          - taux: 2000%
            plafond: 5000 km/an
          - taux: 1500%
            plafond: 20000 km/an
``` 

[voir l'exemple dans le studio](https://publi.codes/studio/dur%C3%A9e-de-vie-v%C3%A9hicule#km%20parcourus%20par%20an%3A%2014000%20km%2Fan%0A%0Adur%C3%A9e%20de%20vie%20v%C3%A9hicule%3A%0A%20%20description%3A%20%7C%0A%20%20%20%20On%20prend%20une%20dur%C3%A9e%20de%20vie%20du%20v%C3%A9hicule%20entre%2015%20et%2020%20ans.%0A%20%20%20%20Hypoth%C3%A8se%20qu'un%20v%C3%A9hicule%20qui%20roule%20moins%20annuellement%20durera%20plus%20d'ann%C3%A9es.%0A%20%20%20%20On%20prend%205000km%2Fan%20pour%20un%20petit%20rouleur%20et%2020000km%2Fan%20pour%20un%20gros%20rouleur.%0A%20%20%20%20Entre%20les%20deux%20bornes%20on%20fait%20progresser%20lin%C3%A9airement%20la%20valeur%20de%20dur%C3%A9e%20de%20vie%20en%20ann%C3%A9e.%0A%20%20produit%3A%0A%20%20%20%20assiette%3A%2010%20ans%0A%20%20%20%20taux%3A%0A%20%20%20%20%20%20taux%20progressif%3A%0A%20%20%20%20%20%20%20%20assiette%3A%20km%20parcourus%20par%20an%0A%20%20%20%20%20%20%20%20tranches%3A%0A%20%20%20%20%20%20%20%20%20%20-%20taux%3A%20200%25%0A%20%20%20%20%20%20%20%20%20%20%20%20plafond%3A%205000%20km%2Fan%0A%20%20%20%20%20%20%20%20%20%20-%20taux%3A%20150%25%0A%20%20%20%20%20%20%20%20%20%20%20%20plafond%3A%2020000%20km%2Fan) (cas d'usage issu de https://github.com/incubateur-ademe/nosgestesclimat/issues/2127#issuecomment-1824359943)

On voit que l'écriture n'est pas très compréhensible bien que la logique du mécanisme de "taux progressif" soit bien ce qu'on cherche à utiliser : 
- les termes "assiette", "tranches", et "multiplicateur" (non utilisé ici mais qui peut prêter à confusion) sont spécifiques aux besoins de mon-entreprise, et ne sont pas adaptés ici
- on doit obligatoirement passer par un "taux progressif" ce qui oblique à multiplier une valeur de base "1 an" pour pouvoir retrouver nos seuils de 15 ans et de 20 ans

Je n'ai pas réfléchi à une proposition concrète mais il me semble qu'il faudrait plutôt un mécanisme de valeur progressive, qui permette de définir des seuils avec une interpolation linéaire entre eux, à la manière par exemple des seuils dans les transitions CSS. Ce mécanisme pourrait alors être utilisé pour un taux progressif mais aussi pour n'importe quel autre type de valeur. Les termes "assiette" et "multiplicateur" disparaîtraient.
