### ISSUE TITLE
Le mécanisme `est non applicable` ne fonctionne pas lorsque `contexte` est utilisé

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#454]
## Cas minimum reproductible
```yaml
c: non
a: 
  applicable si: c
  contexte: 
    c: non
b: 
  est non applicable: a
```
:point_right:  [Voir dans le studio](https://publi.codes/studio/b#c%3A%20non%0Aa%3A%20%0A%20%20applicable%20si%3A%20c%0A%20%20contexte%3A%20%0A%20%20%20%20c%3A%20non%0Ab%3A%20%0A%20%20est%20non%20applicable%3A%20a)

## Comportement attendu 

Ici `b` vaut `non` alors que `a` est `non applicable`

Si on enlève la ligne `contexte` tout marche comme attendu
