### ISSUE TITLE
Nouveau mécanisme « alias »

### ISSUE THREAD

**Issue by JalilArfaoui** [publicodes/publicodes#471]
[Mon-entreprise](https://github.com/betagouv/mon-entreprise/) utilise une propriété `alias` dans certaines règles pour déclarer un «deuxième nom»  pour la règle, à titre purement de documentation.

Ne serait-il pas intéressant de l'intégrer à Publi.codes de manière à permettre de déclarer un nom de règle qui serait interchangeable avec le nom principal de la règle.

Cela permettrait
- d'introduire une souplesse dans la référence aux règles
- mais également de permettre le déplacement / renommage d'une règle sans changement cassant dans les clients en place

Exemple

```yaml
impôt . foyer fiscal . situation de famille:
  question: Quelle est votre situation familiale ?
  formule:
    une possibilité:
      choix obligatoire: oui
      possibilités:
        - célibataire
        - couple
        - veuf
  par défaut: "'célibataire'"
```

pourrait devenir 

```yaml
situation personnelle . famille . foyer fiscal:
  alias: impôt . foyer fiscal . situation de famille
  question: Quelle est votre situation familiale ?
  formule:
    une possibilité:
      choix obligatoire: oui
      possibilités:
        - célibataire
        - couple
        - veuf
  par défaut: "'célibataire'"
```

Idéalement, on pourrait même prévoir un mécanisme pour déprécier l'alias:

```yaml
situation personnelle . famille . foyer fiscal:
  alias: 
     règle: impôt . foyer fiscal . situation de famille
     déprécié: oui
  question: Quelle est votre situation familiale ?
  formule:
    une possibilité:
      choix obligatoire: oui
      possibilités:
        - célibataire
        - couple
        - veuf
  par défaut: "'célibataire'"
```
