### ISSUE TITLE
Problème de conversion d'unité avec le mécanisme de contexte

### ISSUE THREAD

**Issue by JalilArfaoui** [publicodes/publicodes#480]
En partant de cet exemple très simple qui marche :

```yaml
prix:
  avec:
    carottes: 2€/kg
    champignons: 5€/kg
    avocat: 2€/avocat

dépenses primeur:
  somme:
    - prix . carottes * 1.5 kg
    - prix . champignons * 500g
    - prix . avocat * 3 avocat

le truc:
  avec:
    TTC: dépenses primeur * 1.2
    TVA: dépenses primeur * 0.2

evalue:
  valeur: le truc . TTC
```

[Résultat OK](https://publi.codes/studio/evalue#prix%3A%0A%20%20avec%3A%0A%20%20%20%20carottes%3A%202%E2%82%AC%2Fkg%0A%20%20%20%20champignons%3A%205%E2%82%AC%2Fkg%0A%20%20%20%20avocat%3A%202%E2%82%AC%2Favocat%0A%0Ad%C3%A9penses%20primeur%3A%0A%20%20somme%3A%0A%20%20%20%20-%20prix%20.%20carottes%20*%201.5%20kg%0A%20%20%20%20-%20prix%20.%20champignons%20*%20500g%0A%20%20%20%20-%20prix%20.%20avocat%20*%203%20avocat%0A%0Ale%20truc%3A%0A%20%20avec%3A%0A%20%20%20%20TTC%3A%20d%C3%A9penses%20primeur%20*%201.2%0A%20%20%20%20TVA%3A%20d%C3%A9penses%20primeur%20*%200.2%0A%0Aevalue%3A%0A%20%20valeur%3A%20le%20truc%20.%20TTC%0A)

Mais si je veux forcer le prix des `carottes` via le mécanisme `contexte` de cette façon :

```yaml
prix:
  avec:
    carottes: 2€/kg
    champignons: 5€/kg
    avocat: 2€/avocat

dépenses primeur:
  somme:
    - prix . carottes * 1.5 kg
    - prix . champignons * 500g
    - prix . avocat * 3 avocat

le truc:
  avec:
    TTC: dépenses primeur * 1.2
    TVA: dépenses primeur * 0.2

evalue:
  valeur: le truc . TTC
  contexte: 
    prix . carottes: 2€/Kg
```

Le moteur a des difficultés avec les unités et semble prendre les `Kg` pour les `grammes` :

![image](https://github.com/publicodes/publicodes/assets/3037833/2d56634c-8c74-47f3-b2ac-ee76bcc4dd21)

[Reproduction](https://publi.codes/studio/evalue#prix%3A%0A%20%20avec%3A%0A%20%20%20%20carottes%3A%202%E2%82%AC%2Fkg%0A%20%20%20%20champignons%3A%205%E2%82%AC%2Fkg%0A%20%20%20%20avocat%3A%202%E2%82%AC%2Favocat%0A%0Ad%C3%A9penses%20primeur%3A%0A%20%20somme%3A%0A%20%20%20%20-%20prix%20.%20carottes%20*%201.5%20kg%0A%20%20%20%20-%20prix%20.%20champignons%20*%20500g%0A%20%20%20%20-%20prix%20.%20avocat%20*%203%20avocat%0A%0Ale%20truc%3A%0A%20%20avec%3A%0A%20%20%20%20TTC%3A%20d%C3%A9penses%20primeur%20*%201.2%0A%20%20%20%20TVA%3A%20d%C3%A9penses%20primeur%20*%200.2%0A%0Aevalue%3A%0A%20%20valeur%3A%20le%20truc%20.%20TTC%0A%20%20contexte%3A%20%0A%20%20%20%20prix%20.%20carottes%3A%202%E2%82%AC%2FKg%0A%0A)

Toutefois, si j'omets l'unité dans mon contexte, ça fonctionne comme attendu : 

```yaml
prix:
  avec:
    carottes: 2€/kg
    champignons: 5€/kg
    avocat: 2€/avocat

dépenses primeur:
  somme:
    - prix . carottes * 1.5 kg
    - prix . champignons * 500g
    - prix . avocat * 3 avocat

le truc:
  avec:
    TTC: dépenses primeur * 1.2
    TVA: dépenses primeur * 0.2

evalue:
  valeur: le truc . TTC
  contexte: 
    prix . carottes: 2
```

[Reproduction](https://publi.codes/studio/evalue#prix%3A%0A%20%20avec%3A%0A%20%20%20%20carottes%3A%202%E2%82%AC%2Fkg%0A%20%20%20%20champignons%3A%205%E2%82%AC%2Fkg%0A%20%20%20%20avocat%3A%202%E2%82%AC%2Favocat%0A%0Ad%C3%A9penses%20primeur%3A%0A%20%20somme%3A%0A%20%20%20%20-%20prix%20.%20carottes%20*%201.5%20kg%0A%20%20%20%20-%20prix%20.%20champignons%20*%20500g%0A%20%20%20%20-%20prix%20.%20avocat%20*%203%20avocat%0A%0Ale%20truc%3A%0A%20%20avec%3A%0A%20%20%20%20TTC%3A%20d%C3%A9penses%20primeur%20*%201.2%0A%20%20%20%20TVA%3A%20d%C3%A9penses%20primeur%20*%200.2%0A%0Aevalue%3A%0A%20%20valeur%3A%20le%20truc%20.%20TTC%0A%20%20contexte%3A%20%0A%20%20%20%20prix%20.%20carottes%3A%202%0A%0A)

**Comment by JalilArfaoui** [comment]
Aaaaahhh au temps pour moi !

Il faut juste écrire `kg` tout en minuscule !
Pourtant j'ai relu 10 fois à la recherche d'une typo !

Ça marche très bien en minuscules :

```yaml
prix:
  avec:
    carottes: 2€/kg
    champignons: 5€/kg
    avocat: 2€/avocat

dépenses primeur:
  somme:
    - prix . carottes * 1.5 kg
    - prix . champignons * 500g
    - prix . avocat * 3 avocat

le truc:
  avec:
    TTC: dépenses primeur * 1.2
    TVA: dépenses primeur * 0.2

evalue:
  valeur: le truc . TTC
  contexte: 
    prix . carottes: 2€/kg
```

Et du coup, je viens d'apprendre que la [bonne écriture est bien en minuscule](https://fr.wikipedia.org/wiki/Kilogramme)… J'étais persuadé qu'il fallait un grand `K`.

Désolé pour le dérangement !
