### ISSUE TITLE
Bug lors de la conversion d'unité dans les sommes

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#524]
## Comportement actuel
Dans le publicodes suivant, la valeur de `a` est 210.
```yaml
a: 
  somme: 
    - 1m / 10cm
    - 2
```
[voir le studio](https://publi.codes/studio/a#a%3A%20%0A%20%20somme%3A%20%0A%20%20%20%20-%201m%20%2F%2010cm%0A%20%20%20%20-%202)

## Comportement attendu 

On voudrait que la somme soit égale à `1m / 10cm = 10` + `2` = `12`
