### ISSUE TITLE
Bug lors de l'ajout d'un pourcentage dans le mécanisme somme

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#526]
### Comportement actuel
Dans l'expression
```yaml
a: 
  somme: 
    - 50
    - 50
    - 10%
```
a vaut 105

### Attendu

On s'attendait à ce que l'addition soit associative par la gauche. 
> a = `(50 + 50) + 10%` = ` 110`
