### ISSUE TITLE
Arrondi à une valeur proche

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#528]
Plutôt que d'arrondir à une décimale, on souhaiterait pouvoir arrondir à une valeur proche, par exemple, à 0.5 près. Pour cela, il suffirait de spécifier le chiffre sans préciser « décimale ».

```yaml
a: # vaut 18.5€ 
  valeur: 18.3 €
  arrondi: 0.5€
```

```yaml
a: # vaut 20 jours 
  valeur: 16 jours
  arrondi: 10 jours
```

```yaml
a: # vaut 102.2 cm
  valeur: 102.21cm
  arrondi: 0.1
```
