### ISSUE TITLE
🐛 Mécanisme `remplacement` ❌

### ISSUE THREAD

**Issue by pbourdu** [publicodes/publicodes#535]
Version concernée `1.5.0`

## Description du bug
J'utilise le mécanisme `remplacement` dans le cadre du calcul de la tranche marginale d'imposition (cf. impôt sur le revenu).
Le code `.publicodes` est [ici](https://gist.github.com/pbourdu/c61122c1ac3b1ac1d50ee10c3abf7734) et peut être directement utilisé dans [le studio publicodes](https://publi.codes/studio) (🤔 lien partageable ne fonctionnait pas...).

*Les trois dernières règles définies doivent permettre de trouver le pourcentage de taxation d'un euro de revenu marginal ajouté au revenu imposable.*

```yaml
impôt sur le revenu . contexte tranche marginale d'imposition:
  remplace:
    références à: revenu imposable
    dans: impôt brut avec un euro marginal
  valeur: revenu imposable + 1

impôt sur le revenu . impôt brut avec un euro marginal:
  valeur: impôt brut

impôt sur le revenu . tranche marginale d'imposition:
  valeur: ( impôt brut avec un euro marginal - impôt brut ) / 1
  type: pourcentage
  arrondi: oui
```

J'obtiens ces résultats : 
- `contexte tranche marginale d'imposition` : `180001` ✅ 
- `impôt brut` :  `58 144,48` ✅ 
- `impôt brut avec un euro marginal` :  `58 144,48` ❌ (attendu `58 144,93`)
- `tranche marginale d'imposition` :  `0`  ❌ (attendu `45%`)

En observant [le résultat de l'évaluation de `impôt brut avec un euro marginal`](https://gist.github.com/pbourdu/c61122c1ac3b1ac1d50ee10c3abf7734#file-evaluated-json). Pas de trace d'un remplacement de la valeur `revenu imposable` qui reste à `180000` contre les `180001` attendu 🤔 .

## Question en suspens
- [ ] [Autre bug](https://github.com/publicodes/publicodes/issues/467) identifié par @Clemog  sur le mécanisme ? Toujours d'actualité / Similitude ?
- [ ] Tenté de comprendre comment fonctionne le mécanisme, mais difficile de re-lire le code. Code principalement écrit par @johangirod, qu'est-ce que vous pensez de ce bug ? Vrai bug ou mauvaise utilisation ?
