### ISSUE TITLE
setSituation génère une erreur sur une valeur avec `une possibilité` 

### ISSUE THREAD

**Issue by martinratinaud** [publicodes/publicodes#537]
Pour France Chaleur Urbaine, nous avons la règle suivante

```yaml
mode affichage:
  par défaut: "'technicien'"
  une possibilité:
    choix obligatoire: oui
    possibilités:
      - "'grand public'"
      - "'technicien'"
```
En faisant `setSituation("mode affichage", "grand public")`, une erreur est levée disant que la possibilité n'est pas défini

Effectivement, en regardant la fonction `isAValidOption`, la présence de la valeur dans `possibilités` ne semble pas être testée.

De +, la lecture de la condition n'est pas très facile et pourrait être réécrite de la manière suivante

```ts
	// Parse the value to get the expression if it's a string
	const parsedSituationExpr =
		typeof value === 'string' ? parseExpression(value, dottedName) : undefined;

	const parsedRules = engine.getParsedRules();

	// Check if the parsed situation expression is valid
	const isExpressionValid =
		parsedSituationExpr &&
		'constant' in parsedSituationExpr &&
		parsedSituationExpr.constant.type === 'string';

	const ruleKey = isExpressionValid ? `${dottedName} . ${parsedSituationExpr.constant.nodeValue}` : '';

	const ruleExists = ruleKey in parsedRules;

	// Check if the "une possibilité" node exists in the rawNode
	const hasPossibilityNode =
		parsedRules[dottedName].rawNode?.['une possibilité'] ||
		parsedRules[dottedName].rawNode?.formule?.['une possibilité'] ||
		parsedRules[dottedName].rawNode?.valeur?.['une possibilité'];
       
        // TODO check if value exists in une possibilité > possibilités
	// Return true if the rule does not exist and possibility node exists
	return !ruleExists && hasPossibilityNode;
```

L'erreur vient surement de ce commit
https://github.com/publicodes/publicodes/commit/183e8728dfb0abca3074a2e89468eec23bfe96b0

Merci

**Comment by johangirod** [comment]
Cela vient du fait que le mécanisme `une possibilité` oblige de déclarer les possibilités comme des règles sous-jacente. La bonne syntaxe est donc la suivante : 
```yaml
mode affichage:
  par défaut: "'technicien'"
  une possibilité:
    choix obligatoire: oui
    possibilités:
      - grand public
      - technicien
  avec: 
    technicien: mode affichage = 'technicien'
    grand public: mode affichage = 'grand public'
```

Nous devrions spécifier le comportement actuel de ce mécanisme dans la doc, avant de le faire évoluer pour être plus facile d'utilisation.

https://github.com/publicodes/publicodes/issues/440
