### ISSUE TITLE
Bug mécanisme applicable si avec règle sans valeur

### ISSUE THREAD

**Issue by totakoko** [publicodes/publicodes#540]
J'ai un problème avec le mécanisme `applicable si`. Il semblerait que si la variable utilisée n'a pas de valeur, alors la condition s'applique.

Dans mon [exemple](https://publi.codes/studio/nom-d%C3%A9partement#code%20d%C3%A9partement%3A%0Anom%20d%C3%A9partement%3A%20nom%20d%C3%A9partement%0A%0Ad%C3%A9partements%3A%0Ad%C3%A9partements%20.%20dep%2001%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2201%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'AIN'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2002%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2202%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'AISNE'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2003%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2203%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'ALLIER'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement), le code département permet de remplacer des valeurs, et en fait le dernier s'applique quand il n'y a pas de code renseigné.

Un avis ?

**Comment by johangirod** [comment]
Effectivement, cela vient du fait qu'une valeur `non définie` est considérée comme `applicable`. 

Je vois deux manières de régler ce problème.
1. [Ajouter une valeur par défaut à code département](https://publi.codes/studio/nom-d%C3%A9partement#code%20d%C3%A9partement%3A%20%0A%20%20par%20d%C3%A9faut%3A%20%22'non%20renseign%C3%A9'%22%0Anom%20d%C3%A9partement%3A%20nom%20d%C3%A9partement%0A%0A%0Ad%C3%A9partements%3A%0Ad%C3%A9partements%20.%20dep%2001%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2201%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'AIN'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2002%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2202%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'AISNE'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2003%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2203%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'ALLIER'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0A)
2. [Rendre applicable `département` uniquement si `code département` est défini.](https://publi.codes/studio/nom-d%C3%A9partement#code%20d%C3%A9partement%3A%20%0Anom%20d%C3%A9partement%3A%20nom%20d%C3%A9partement%0A%0A%0Ad%C3%A9partements%3A%0A%20%20applicable%20si%3A%20%0A%20%20%20%20est%20d%C3%A9fini%3A%20code%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2001%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2201%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'AIN'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2002%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2202%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'AISNE'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0Ad%C3%A9partements%20.%20dep%2003%3A%0A%20%20applicable%20si%3A%20code%20d%C3%A9partement%20%3D%20%2203%22%0A%20%20avec%3A%0A%20%20%20%20nom%3A%0A%20%20%20%20%20%20valeur%3A%20%22'ALLIER'%22%0A%20%20%20%20%20%20remplace%3A%20nom%20d%C3%A9partement%0A)

**Comment by totakoko** [comment]
Le valeur par défaut justement on en veut pas.

En changeant la condition 
```yml
  applicable si:
    code département = "03"
```
vers
```yml
  applicable si:
    toutes ces conditions:
      - est défini: code département
      - code département = "03"
 ```

Ça a l'air de fonctionner, c'est juste beaucoup plus verbeux :sweat_smile:

**Comment by totakoko** [comment]
Pour `code département = xx` qui est applicable si `code département` est non défini, ça ne serait pas plus logique de faire l'inverse ? :thinking:

**Comment by johangirod** [comment]
Pour la solution 2, je pensais à factoriser l'applicabilité des remplacements de `département .  *` dans la règle `département` justement, pour éviter le côté verbeux :)

```yaml
départements:
  applicable si: 
    est défini: code département
départements . dep 01:
  applicable si: code département = "01"
  avec:
    nom:
      valeur: "'AIN'"
      remplace: nom département
```

> Pour code département = xx qui est applicable si code département est non défini, ça ne serait pas plus logique de faire l'inverse ? 🤔

C'est un choix de design : 
- Cela permet de récupérer toutes les missing variables des branches de variations non définis
- Et surtout cela évite d'avoir à préciser des valeur par défaut sur toutes les règles non définies. Car dans l'état actuel, une règle non applicable désactive tout ses enfants. Cela obligerait donc à ajouter des `valeur: oui` à tous les parents.

Pas contre changer le comportement, mais il faudra avoir ces point en tête.

**Comment by JalilArfaoui** [comment]
> Effectivement, cela vient du fait qu'une valeur `non définie` est considérée comme `applicable`. Ainsi, ici, `code département` est non défini, et par extension `code département = xx` l'est aussi, donc est applicable : tous les remplacements sont appliqués.

@johangirod je comprends que `code département = xx` soit considéré `applicable` même si `code département` est non défini, mais pour moi il devrait être évalué comme `falsy` et donc `applicable si: code département = "01"` devrait rendre le bloc `non applicable`.

Il me semble très contre-intuitif de se dire que 
`applicable si: code département = "01"` rend le bloc applicable si on a pas de code département

J’ai le même problème dans l’autre sens, mais c’est même plus problématique pour moi : 

[1er exemple](https://publi.codes/studio/autoentrepreneur#condition1%3A%20non%0Acondition2%3A%20non%0A%0Aautoentrepreneur%3A%0A%20%20par%20d%C3%A9faut%3A%20non%0A%20%20valeur%3A%20non%0A%20%20non%20applicable%20si%3A%0A%20%20%20%20une%20de%20ces%20conditions%3A%0A%20%20%20%20%20%20-%20condition1%0A%20%20%20%20%20%20-%20condition2%0A) :

```yaml
condition1: non
condition2: non

autoentrepreneur:
  par défaut: non
  valeur: non
  non applicable si:
    une de ces conditions:
      - condition1
      - condition2
```

`autoentrepreneur` prend bien sa valeur par défaut `non` car les conditions de non-applicabilité de sont pas réunies. Normal.

[2ème exemple](https://publi.codes/studio/autoentrepreneur#condition1%3A%20non%0Acondition2%3A%20oui%0A%0Aautoentrepreneur%3A%0A%20%20par%20d%C3%A9faut%3A%20non%0A%20%20valeur%3A%20non%0A%20%20non%20applicable%20si%3A%0A%20%20%20%20une%20de%20ces%20conditions%3A%0A%20%20%20%20%20%20-%20condition1%0A%20%20%20%20%20%20-%20condition2%0A)

```yaml
condition1: non
condition2: oui

autoentrepreneur:
  par défaut: non
  valeur: non
  non applicable si:
    une de ces conditions:
      - condition1
      - condition2
````

Là, `autoentrepreneur`  devient non-applicable, car une des conditions non applicabilité est réalisée. Normal.

Mais, surprise, [cas 3]()

```yaml
condition1: non
condition2: 

autoentrepreneur:
  par défaut: non
  valeur: non
  non applicable si:
    une de ces conditions:
      - condition1
      - condition2
```

Une des conditions de non-applicabilité est non définie, et la règle `autoentrepreneur` devient non pas non-applicable, même elle-même non définie !

**Comment by JalilArfaoui** [comment]
Ça donne des trucs très bizarres (à moins que ce soit un bug différent) :

```yaml
entreprise:
entreprise . catégorie juridique: "'EI'"
entreprise . catégorie juridique . EI:
  valeur: catégorie juridique = 'EI'

entreprise . catégorie juridique . EI . autoentrepreneur:
  par défaut: non
  non applicable si: truc

entreprise . catégorie juridique . SELARL: non
entreprise . catégorie juridique . SELAS: non

truc: 

dirigeant:
dirigeant . régime social:
  variations:
    - si: entreprise . catégorie juridique . EI . autoentrepreneur
      alors: "'auto-entrepreneur'"
    - si:
        une de ces conditions:
          - entreprise . catégorie juridique . EI
          - entreprise . catégorie juridique . SELARL
          - entreprise . catégorie juridique . SELAS
      alors: "'indépendant'"
```

[Studio](https://publi.codes/studio/dirigeant/r%C3%A9gime-social#entreprise%3A%0Aentreprise%20.%20cat%C3%A9gorie%20juridique%3A%20%22'EI'%22%0Aentreprise%20.%20cat%C3%A9gorie%20juridique%20.%20EI%3A%0A%20%20valeur%3A%20cat%C3%A9gorie%20juridique%20%3D%20'EI'%0A%0Aentreprise%20.%20cat%C3%A9gorie%20juridique%20.%20EI%20.%20autoentrepreneur%3A%0A%20%20par%20d%C3%A9faut%3A%20non%0A%20%20non%20applicable%20si%3A%20truc%0A%0Aentreprise%20.%20cat%C3%A9gorie%20juridique%20.%20SELARL%3A%20non%0Aentreprise%20.%20cat%C3%A9gorie%20juridique%20.%20SELAS%3A%20non%0A%0Atruc%3A%20%0A%0Adirigeant%3A%0Adirigeant%20.%20r%C3%A9gime%20social%3A%0A%20%20variations%3A%0A%20%20%20%20-%20si%3A%20entreprise%20.%20cat%C3%A9gorie%20juridique%20.%20EI%20.%20autoentrepreneur%0A%20%20%20%20%20%20alors%3A%20%22'auto-entrepreneur'%22%0A%20%20%20%20-%20si%3A%0A%20%20%20%20%20%20%20%20une%20de%20ces%20conditions%3A%0A%20%20%20%20%20%20%20%20%20%20-%20entreprise%20.%20cat%C3%A9gorie%20juridique%20.%20EI%0A%20%20%20%20%20%20%20%20%20%20-%20entreprise%20.%20cat%C3%A9gorie%20juridique%20.%20SELARL%0A%20%20%20%20%20%20%20%20%20%20-%20entreprise%20.%20cat%C3%A9gorie%20juridique%20.%20SELAS%0A%20%20%20%20%20%20alors%3A%20%22'ind%C3%A9pendant'%22%0A%0A)

Eh bien dans cet exemple :
- Si `truc` vaut `oui` -> `régime social` est `indépendant`
- Si `truc` vaut `non` -> `régime social` est toujours `indépendant`
- Mais si `truc` n’est pas défini,  -> `régime social` n’est pas défini !

**Comment by johangirod** [comment]
La valeur « non-définie » se propage en « contaminant » les calculs où elle apparait, c'est un comportement uniforme partout dans publicodes.

> Une des conditions de non-applicabilité est non définie, et la règle autoentrepreneur devient non pas non-applicable, même elle-même non définie !

Ça me semble très logique comme comportement. Si une condition de non applicabilité est non définie, on a pas assez de d'éléments pour rendre non applicable la règle, dans le doute elle reste applicable (sinon cela voudrait dire que l'on désactive toutes les règles sauf si elles sont explicitement applicable). 

C'est en revanche, un peu moins logique avec la condition `applicable si` que l'on a tendance à lire comme `applicable si et seulement si`. Je reconnais le fait que l'on s'attend à un comportement « par défaut » automatique dans ces mécanismes : 

- `applicable si` signifie « applicable uniquement si la condition est vrai, non applicable par défaut »
- `non applicable si` signifierai « non applicable uniquement dans le cas ou la condition est vrai, applicable par défaut »

C'est un changement très facile à faire, mais cassant. À ajouter pour une v2 si il n'y a pas de contre-indications. 

## Comment obtenir le comportement voulu en attendant

En ajoutant une valeur par défaut :

```yaml
condition1: non
condition2: 
  par défaut: non # soit au niveau de la condition

autoentrepreneur:
  par défaut: non
  valeur: non
  non applicable si:
    par défaut: non # soit au niveau du mécanisme
    une de ces conditions:
      - condition1
      - condition2
```

**Comment by JalilArfaoui** [comment]
> La valeur « non-définie » se propage en « contaminant » les calculs où elle apparait, c'est un comportement uniforme partout dans publicodes.

> >  Une des conditions de non-applicabilité est non définie, et la règle autoentrepreneur devient non pas non-applicable, même elle-même non définie !

> Ça me semble très logique comme comportement. Si une condition de non applicabilité est non définie, on a pas assez de d'éléments pour rendre non applicable la règle, dans le doute elle reste applicable (sinon cela voudrait dire que l'on désactive toutes les règles sauf si elles sont explicitement applicable).

Mais du coup, ça dépasse le cas de l’applicabilité, puisqu'avec mon exemple de `régime social` on a un cas de `variations` qui devient non-défini parce que l’une des conditions utilise une règle non définie …

C’est le comportement voulu aujourd’hui en V1 ?

**Comment by JalilArfaoui** [comment]
Ce que je veux dire, c'est que : que la règle reste applicable parce qu'on a pas assez d'éléments pour la rendre non applicable, d'accord, mais pourquoi est-ce que ça fait sauter la valeur de la règle, qui elle est bien définie ?

**Comment by johangirod** [comment]
> Mais du coup, ça dépasse le cas de l’applicabilité, puisqu'avec mon exemple de régime social on a un cas de variations qui devient non-défini parce que l’une des conditions utilise une règle non définie …

Dans ce cas, oui, c'est voulu : dès qu'une valeur non définie est utilisée dans un mécanisme, elle « contamine » le résultat du mécanisme comme indéfini. 

> Ce que je veux dire, c'est que : que la règle reste applicable parce qu'on a pas assez d'éléments pour la rendre non applicable, d'accord, mais pourquoi est-ce que ça fait sauter la valeur de la règle, qui elle est bien définie ?

Voici comment est implémenté le mécanisme `applicable si` aujourd'hui : 
```yaml
variations:
  - si: ${applicable si} != non
    alors: ${valeur}
  - sinon: nonApplicable
```

[Voir le code](https://github.com/publicodes/publicodes/blob/wip/packages/core/src/mecanisms/applicable.ts#L10)

Si la condition de `applicable si` renvoie `non défini`, dans l'état actuel, cela se propage. Pour corriger ce problème, il faudrait implémenter le mécanisme comme ceci : 

```yaml
variations:
  - si: 
      valeur: ${applicable si} != non
      par défaut: oui
    alors: ${valeur}
  - sinon: nonApplicable
```

Cela garantirait que la règle soit applicable *par défaut* si la condition d'applicabilité n'est pas définie, et ce serait un bon comportement je pense (cf mon message précédent).
