### ISSUE TITLE
L'inversion renvoie `non défini` si utilisée avec le mécanisme `contexte`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#560]
## Bug

Lorsque la valeur de la variable avec laquelle inverser est précisée grâce à un `contexte` plutôt que directement dans une situation, l'inversion renvoie  `non défini`.

```yaml
a: 5 * b
b: 
  inversion numérique: 
    - a
  contexte: 
    a: 10
```
[:point_right:  Voir l'exemple dans le studio](https://publi.codes/studio/b#a%3A%204%20*%20b%0Ab%3A%20%0A%20%20inversion%20num%C3%A9rique%3A%20%0A%20%20%20%20-%20a%0A%20%20contexte%3A%20%0A%20%20%20%20a%3A%2010)

## Attendu

On s'attend à ce que l'inversion utilise le contexte pour calculer la bonne valeur. Dans l'exemple ci-dessus, `b` devrait valoir `2`.

@eweap @fmata
