### ISSUE TITLE
`résoudre la référence circulaire` does not seem to work with evaluation with  spécific `contexte`

### ISSUE THREAD

**Issue by JalilArfaoui** [publicodes/publicodes#654]
Giving this working evaluation : 

```ts
engine.setSituation({
  "entreprise . chiffre d'affaires": '50000 €/an',
  'dirigeant . régime social': "'indépendant'",
  'entreprise . imposition': "'IR'",
})
engine.evaluate('dirigeant . indépendant . cotisations et contributions') // 15_276
```

I expect that I should have the same result with evaluation in context : 

```yaml
location de logement meublé . cotisations . régime travailleur indépendant:
  titre: Cotisations dues pour la location d’un logement meublé au régime du travailleur indépendant
  valeur: dirigeant . indépendant . cotisations et contributions
  contexte:
    entreprise . chiffre d'affaires: recettes
    dirigeant . régime social: "'indépendant'"
    entreprise . imposition: "'IR'"
```

```ts
engine.setSituation({ 'location de logement meublé . recettes': '50000 €/an' })
engine.evaluate('location de logement meublé . cotisations . régime travailleur indépendant')
```

But this evaluates to another value (19633) !

Here is a [reproduction](https://github.com/betagouv/mon-entreprise/blob/repro/contexte_publicodes/site/test/modele-social/%C3%A9conomie-collaborative.test.ts) as 2 unit tests in mon-entreprise repo.

I’m not sure if it has to do with circular reference …

**Comment by johangirod** [comment]
I'm not sure if it comes from the imbrication of these two mecanism, or at least, I did'nt succeed in finding a minimal reproducible case.

[Indeed the following code works](https://publi.codes/studio/x#%0Aa%3A%20%0A%20%20valeur%3A%2010%20%2B%20b%0A%0Ab%3A%20%0A%20%20valeur%3A%20a%20*%200.1%0A%20%20r%C3%A9soudre%20la%20r%C3%A9f%C3%A9rence%20circulaire%3A%20oui%0A%0Ax%3A%20%0A%20%20valeur%3A%20b%0A%20%20contexte%3A%0A%20%20%20%20a%3A%2050%0A%20%20%20%20)

```yaml
a: 
  valeur: 10 + b

b: 
  valeur: a * 0.1
  résoudre la référence circulaire: oui

x: 
  valeur: b
  contexte:
    a: 50
```

It might be another instance of problem due to #655 . The mon-entreprise codebase is filled with cycles.
