### ISSUE TITLE
Gestion du contexte d'une règle qui possède elle-même un contexte

### ISSUE THREAD

**Issue by Clemog** [publicodes/publicodes#669]
Petit cas de test [ici](https://publi.codes/studio/d#%0Aa%3A%0A%20%20formule%3A%20b%20*%202%0A%0Ab%3A%2050%0A%0Ac%3A%0A%20%20valeur%3A%20a%0A%20%20contexte%3A%0A%20%20%20%20b%3A%2010%0A%0Ad%3A%0A%20%20valeur%3A%20c%0A%20%20contexte%3A%0A%20%20%20%20b%3A%20100)

De mon point de vue, le "dernier" contexte renseigné devrait prévaloir, on devrait avoir ici `d` à 200 non ?

**Comment by EmileRolley** [comment]
La valeur de `c` ici me semble correcte. En effet, nous pouvons considérer ici l'utilisation du mécanisme `contexte` comme un appel de fonction.

```yaml
a: b * 2

b: 50

c:
  valeur: a
  contexte:
    b: 10

d:
  valeur: c
  contexte:
    b: 100
```

Ce programme pourrait donc s'écrire en JavaScript de la façon suivante :

```js
const a = ({ b: b_local } = b) => b_local * 2

const b = 50

const c = (_) => a({ b: 10 })

const d = (_) => c({ b: 100 })
```

Ce qui donne bien `d` évalué à 20 comme attendu.

**Comment by Clemog** [comment]
Est-ce qu'on ne devrait pas vérifier justement la présence d'un contexte lors de l'évaluation ?

En mode (sorry pour l'écriture 😅).

```js
const c = (context = {}) => a({...{ b: 10}, ...{context}})
```

**Comment by johangirod** [comment]
> En effet, nous pouvons considérer ici l'utilisation du mécanisme contexte comme un appel de fonction.

J'allais répondre exactement la même chose ^^. Tel qu'on le lit, tu « override » lors de l'appel de c toutes les valeur précédentes de b. C'est logique, le contexte racine, c'est la situation, et ensuite, on a envie de venir override chacun des contexte parent.

Si tu souhaite avoir l'ancien contexte si il est définit, alors c'est un comportement à préciser dans c.

```yaml
a: b * 2

b: 
  par défaut: 50

c:
  valeur: a
  contexte:
    b: 
      valeur: b
      par défaut: 10



d:
  valeur: c
  contexte:
    b: 100

```

**Comment by Clemog** [comment]
J'ai l'impression que je vois la logique inverse. Pour moi, le parent (`d`) possède le nouveau contexte et écrase le reste .. Mais je comprends

**Comment by EmileRolley** [comment]
> J'ai l'impression que je vois la logique inverse. Pour moi, le parent (`d`) possède le nouveau contexte et écrase le reste ..

Cela voudrait dire que pour toi, avoir la règle : 

```yaml
a:
  valeur: b
  contexte:
    b: 10
```

Ne te donnerais aucune garantie sur le fait que `a` vaut 10 ? Avec ton approche, la valeur de `b` pouvant se faire écraser depuis n'importe où, `a` pourrait valoir n'importe quelle valeur.
