### ISSUE TITLE
Contexte et variables manquantes

### ISSUE THREAD

**Issue by Clemog** [publicodes/publicodes#683]
Il semble qu'on a un souci au niveau des variables manquantes lors du passage d'un contexte.

Visiblement, une règle passée dans un contexte dont la valeur par défaut est identique à la valeur passée dans le contexte ne le rend pas "non manquante" contrairement à une valeur passée différente de celle par défaut :/

Exemple avec:

```
a:
  formule: b + c
  contexte:
    b: 10
    c: 50

b:
  par défaut: 10

c:
  par défaut: 20
````

![Image](https://github.com/user-attachments/assets/10ac1f95-38cb-4ab5-a14b-ca8c01da6523)
