### ISSUE TITLE
Ajouter l'interpolation de chaine de caractère dans Publicodes

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#704]
# Mécanisme `texte` et interpolation de texte

## Mécanisme `texte`

Actuellement, le mécanisme [`texte`](https://publi.codes/docs/mecanismes#texte) permet de faire de l'interpolation de texte et en particulier de pouvoir afficher des messages dynamiquement. Ce qui est principalement utilisé lors du prototypage lorsque l'on ne veut pas avoir à implémenter de la logique dans le langage hôte.

Par exemple :

```yaml
aide . résultat:
  texte: Vous êtes éligible à une aide de {{ montant }} euros avec un plafond de {{ plafond }} euros.
  avec:
    montant: # ...
    plafond: # ...
```

Une première question se pose alors : 

**Question 1. Souhaitons-nous garder la possibilité de pouvoir prototyper et éditorialiser directement en Publicodes, ou bien, voulons-nous garder un périmètre délibérément restreint et systèmatiquement déléguer la gestion de l'UI au langage hôte ?**

Par ailleurs, il manque aujourd'hui la possibilité de référencer d'autres règles dans les métadonnées de documentation (description et note). De plus, ces champs ne sont pas dynamiques.

**Question 2. Souhaitons-nous améliorer l'expressivité des métadonnées de documentation ?**

## Choix pour Publicodes 2

_discuté lors du Publicodes café du 26 juin 2025_

- On doit pouvoir ajouter des liens dans les descriptions et les notes, comme on pourrait le faire avec dans une doc JS/TSDoc. Les liens sont uniquement vers d'autres règles (pas d'expression calculées) et sont affichée dans la doc sous forme de lien, avec la valeur à côté (comme dans l'explication actuelle). En revanche il n'est pas possible de créer des description qui change en fonction du contexte d'évaluation.
- Le type `texte` (différent du type `enum`) doit être présent dans le langage, et supporter des opérations basique (égalité, expression régulières? [#452], sous-chaine, commence par / termine par...).

La question d'un mécanisme d'interpolation de chaîne de charactère (et du mécanisme `texte`) reste en suspens, en attendant d'avoir plus de remontées de cas d'usage, autres que de créer des interface directement via publicodes.

On cherche notamment des cas métiers où cela aurait un sens.

<details>

<summary> Historique des propositions </summary>

## Option 1. Statut quo avec liens entre règles

1. Autoriser l'interpolation de chaine de charactère avec le mécanisme `texte`. Comme actuellement, toute règle peut être évaluée à un type `texte` (`string` en js).
2. Ajouter uniquement la possibilité de définir des liens vers d'autres règles dans les champs de métadonnées (avec une syntaxe inspirée markdown par exemple)

```yaml
rentabilité passage à l'électrique . durée de détention:
  description: >
    Calcul de durée de la durée de détention à partir de laquelle l'alternative
    électrique de même gabarit devient rentable avec le [nombre de km parcouru annuellement](usage . km . annuels).
```

## Option 2. L'interpolation de texte est possible uniquement dans les métadonnées 

La possibilité d'éditorialiser est limitées aux métadonnées de documentations (`description`, `note` et `titre`) en rajoutant la possibilité d'évaluer des expressions Publicodes grâce au `{{ }}` (syntaxe à définir).

```yaml
rentabilité passage à l'électrique . durée de détention:
  description: >
    Calcul de durée de la durée de détention à partir de laquelle l'alternative
    électrique de même gabarit devient rentable en parcourant {{ usage . km
    annuels }}.
```

On peut accéder aux métadonnées évaluées selon un certain contexte depuis le JS.

**Variante ** : Doit-on autoriser l'utilisation de mécanisme comme variation en premier niveau ?

```yaml
aide:
  description:
    variations:
      - si: est éligible
        alors: Vous êtes éligible à {{ aide }} euros, plafonné à {{ plafond }} euros.
      - sinon: Vous n'êtes pas éligible pour cette aide, car {{ conditions d'éligiblités }}.
```

## Option 3. Tout est règle

Garder le mécanisme et le type `texte` valide pour toute règle et l'étendre à toutes les métas. 
Les méta deviennent des sous-règles de type "texte". 

```yaml
entreprise . statut juridique:
  question: Quelle est le type d'activité de votre {{ entreprise . statut juridique }} ?
  
entreprise:
  titre: 
    variations: 
      - si: 
            est défini: SIREN
        alors: {{nom}} ({{SIREN}})
      - sinon: Entreprise (en création)
  description: 
    Toutes les informations liées à votre entreprise.
  
```

On peut maintenant évaluer `entreprise . titre` et `entreprise . question`.

</details>

---

Autres questions subsidiaires :
1. Devons-nous attendre un format markdown par défaut ? Un mécanisme markdown ?
2. Quid de la gestion de la gestion des _literal/folded block scalar_ (`>`/`|`) ?
3. Si on garde l'interpolation de chaine de charactère, comment gérer : 
    - la pluralisation
    - la traduction 
    - les valeurs non applicable 
    - les valeurs non définies
4. Quel api pour accéder aux valeurs non évaluées de l'AST si interpolation (que ce soit avec le mécanisme `texte` ou `description` pour l'option 2.)
