### ISSUE TITLE
Add `remplace`

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#715]
# Mécanisme `remplace`

## Contexte

Le principe de [remplacement](https://publi.codes/docs/manuel/principe-de-base#remplacement) mécanisme `remplace` est une force majeure de Publicodes permettant de facilement modéliser le domaine socio-fiscale grâce à une logique _non-monotone par défaut priorisée_[^1]. Concrètement, cela permet de modéliser un **cas de base avec plusieurs exceptions** qui peuvent _remplacer_ sa définition et éviter de se retrouver avec des variations à rallonges.

[^1]: Denis Merigoux, Nicolas Chataing, Jonathan Protzenko. Catala: A Programming Language for the Law. _Proceedings of the ACM on Programming Languages_, 2021, 5 (ICFP), pp.77:1-29. [⟨10.1145/3473582⟩](https://dl.acm.org/doi/10.1145/3473582). [⟨hal-03159939v2⟩](https://inria.hal.science/hal-03159939)

Bien que très utiles, l'utilisation du mécanisme `remplace` peut rapidement compliquer le débugage des programmes. C'est pourquoi il est nécessaire d'en définir précisément le comportement.

## Limitations

Les principales limitations connues sont :

- le manque de [transitivité](https://fr.wikipedia.org/wiki/Relation_transitive) du mécanisme (cf. https://github.com/publicodes/publicodes/issues/55)
- une priorisation implicite par défaut des exceptions par ordre alphabétique sur le nom des règles, ce qui ne permet pas de facilement repérer de potentiels conflits.

### Questionnement des choix de sémantique

Actuellement, ce sont les références qui sont remplacées et non la règle en elle-même, c'est-à-dire, que pour :

```yaml
a: 0

b: a

c:
  valeur: a + 1
  remplace: a
```

`evaluate('a')` vaudra `0` là où `evaluate('b')` vaudra `1` (à noter, que la référence remplacée est ignorée si elle apparait dans l'expression à remplacer).

## A définir collectivement

- Souhaitons-nous garder un remplacement des références et non des règles ?
- Ajouter la transitivité, c'est-à-dire que si `a` remplace `b` qui remplace `c`, alors `a` remplace `c`.
- Pouvoir facilement récupérer pour une règle donnée, la liste des règles qui peuvent la remplacer et celle qui la remplace dans un contexte donné (à l'évaluation, à la compilation, dans l'éditeur, la doc ?).
- Souhaitons-nous garder un ordre de priorité par défaut, ou souhaitons-nous lever une erreur/warning, à l'évaluation/compilation ?

## Cas

<details>

#### Remplacement d'une constante par une autre

```yaml
a: 0

b: a

c:
  valeur: 2
  remplace: a
```

Pour tout contexte,

- `evaluate('a') === 2`
- `evaluate('b') === 2`
- `evaluate('c') === 2`

#### Cas 1

```yaml
a: 0

b: a

c:
  valeur: 2
  remplace:
    références à: a
    sauf dans: b
```

Pour tout contexte,

- `evaluate('a') === 2`
- `evaluate('b') === 0`
- `evaluate('c') === 2`

#### Cas 2

```yaml
a: 0

b: a

c:
  valeur: 2
  remplace:
    références à: a
    sauf dans:
      - b
      - a
```

Pour tout contexte,

- `evaluate('a') === 0`
- `evaluate('b') === 0`
- `evaluate('c') === 2`

#### Cas 3

```yaml
a: 0

b: d + a

d: a

c:
  valeur: 2
  remplace:
    références à: a
    sauf dans: d
```

Pour tout contexte,

- `evaluate('a') === 2`
- `evaluate('b') === 2`
- `evaluate('c') === 2`
- `evaluate('d') === 0`

#### Cas 1

```yaml
a: 0

b: a

c:
  valeur: 2
  remplace: a

d:
  valeur: 3
  remplace: c
```

Pour tout contexte,

- `evaluate('a') === 2`
- `evaluate('b') === 2`
- `evaluate('c') === 2`
- `evaluate('d') === 0`

#### Cas 1

```yaml
a: 0

b: a

c:
  valeur: 2
  remplace: a

e:
  valeur: 3
  remplace: a
```

Pour tout contexte,

- `evaluate('a') === 2`
- `evaluate('b') === 2`
- `evaluate('c') === 2`
- `evaluate('d') === 0`

</details>

### Tutoriel Catala

Implémentation équivalente en Publicodes de l'[exemple sur les exceptions](https://book.catala-lang.org/2-2-conditionals-exceptions.html) de Catala.

En bref, les étiquettes des exceptions de Catala correspondent aux règles Publicodes. La différence principale réside dans le fait qu'en Catala, contrairement à Publicodes, il n'est possible d'accéder uniquement à la valeur finale qui est remplacée, alors qu'en Publicodes, la définition d'une exception se fait au sein d'une règle.

```yaml
taux d'imposition:
  valeur: 20 %

taux d'imposition . avec deux enfants:
  applicable si: individu . nombre d'enfant >= 2
  valeur: 15 %
  remplace: taux d'imposition
  note: |
    ### Article 3

    Si l'individu a la charge de 2 enfants ou plus, le pourcentage fixe
    mentionné à l'article 1 est égal à 15 %.

taux d'imposition . moins de 10 000 euros:
  applicable si: individu . revenus <= 10000 €
  valeur: 0 %
  remplace: avec deux enfants
  note: |
    ### Article 4

    Les personnes qui gagnent moins de 10 000 euros sont exemptées de l'impôt
    sur le revenu mentionné à l'article 1.

taux d'imposition . plus de 100 000 euros:
  applicable si: individu . revenus >= 100000 €
  valeur: 30 %
  remplace: avec deux enfants
  note: |
    ### Article 5

    Les personnes qui gagnent plus de 100 000 dollars sont soumises à un taux
    d'imposition de 30 %, quel que soit le nombre d'enfants.

taux d'imposition . plus de 100 000 euros . outre-mer:
  applicable si: individu . est habitant d'outre-mer
  # sans condition de branches:
  # applicable si:
  #   toutes ces conditions:
  #     - individu . revenus >= 100000 €
  #     - individu . est habitant d'outre-mer
  valeur: 25 %
  remplace: plus de 100 000 euros
  note: |
    ### Article 6

    Dans les territoires d'outre-mer, le taux d'imposition des personnes
    physiques gagnant plus de 100 000 dollars, prévu à l'article 5, est réduit
    à 25 %.
```
