### ISSUE TITLE
Add branch disactivation mechanism

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#719]
## Syntax 
The syntax has yet to be defined. Propositions : 

### With a new key
```yaml
aide vélo: 
  applicable si: eligible
  désactive l'espace de nom: oui
```

### With a new mechanism

```yaml
aide vélo: 
  ensemble applicable si: eligible
```

### With a key inside `applicable si`
```yaml
aide vélo: 
  applicable si: 
    espace de nom: oui
    valeur: eligible
```

### With a new mechanism in a object
```yaml
a: 
  toutes les règles enfants:
     applicable si: 
     non applicable si: 
```
### With a `conditionne l'applicabilité` mechanism
This mechanism would be the opposite of `rend non applicable`
```yaml
contrat . CDD
   conditionne l'applicabilité: 
      règles: CDD . *
      sauf dans: CDD . *
```

```yaml
aide . éligible:
   conditionne l'applicabilité: 
      règles: aide . *
      dans: calcul . *
```

### Other ?

Don't hesitate to submit propositions here

## Behaviour

The new branch disactivation should replace all reference to any subrule by `non applicable`.
