### ISSUE TITLE
Allow to share context between rules

### ISSUE THREAD

**Issue by johangirod** [publicodes/publicodes#736]
We should allow several rules to share the same context to limit code repeat.

One of the possibility could be to have a `contexte général` mecanism that would apply to a whole namespace. 

```yaml
voiture éléctrique: 
  contexte général: 
    NGC . voiture . type = 'electrique'

voiture éléctrique . empreinte: NGC . voiture . empreinte
```

The other would be to reference context directly (with a rule name ?).

```yaml
voiture éléctrique: 
  contexte: 
    NGC . voiture . type = 'electrique'

voiture éléctrique . empreinte: 
  valeur: NGC . voiture . empreinte
  contexte: voiture éléctrique
```
